### PR TITLE
Fix checkfail in QuantizedConv2D with invalid input shape dimensions

### LINKED ISSUE #59927: A crash due to check-fail can be triggered in QuantizedConv2D
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

2.13.0.dev20230307

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

_No response_

### Python version

3.8

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

CUDA 11.5

### GPU model and memory

_No response_

### Current Behaviour?

```shell
A crash due to check-fail can be triggered in QuantizedConv2D and its external api `tf.compat.v1.nn.quantized_conv2d`.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
print(tf.__version__)
strides = [1, 128, 128, 1]
padding = "SAME"
dilations = [1, 1, 1, 1]
input = tf.cast(tf.random.uniform([2, 1, 0, 1], minval=0, maxval=64, dtype=tf.int64), dtype=tf.quint8)
filter = tf.cast(tf.random.uniform([1, 1, 1, 1], minval=0, maxval=64, dtype=tf.int64), dtype=tf.quint8)
min_input = tf.random.uniform([], dtype=tf.float32)
max_input = tf.random.uniform([], dtype=tf.float32)
min_filter = tf.random.uniform([], dtype=tf.float32)
max_filter = tf.random.uniform([], dtype=tf.float32)
# res = tf.raw_ops.QuantizedConv2D(
res = tf.compat.v1.nn.quantized_conv2d(
    strides=strides,
    padding=padding,
    dilations=dilations,
    input=input,
    filter=filter,
    min_input=min_input,
    max_input=max_input,
    min_filter=min_filter,
    max_filter=max_filter,
)
```

### Relevant log output

```shell
2023-03-08 10:44:27.398763: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-08 10:44:27.448284: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-08 10:44:28.229207: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2.13.0-dev20230307
2023-03-08 10:44:29.975476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7865 MB memory:  -> device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0000:2f:00.0, compute capability: 7.0
2023-03-08 10:44:30.000649: I tensorflow/core/common_runtime/process_function_library_runtime.cc:586] Finished graph optimizations for MultiDevice function "__wrapped____EagerConst_device_/job:localhost/replica:0/task:0/device:GPU:0" with target device "/job:localhost/replica:0/task:0/device:GPU:0". Took 0 secs.
2023-03-08 10:44:30.179857: I tensorflow/core/common_runtime/process_function_library_runtime.cc:586] Finished graph optimizations for MultiDevice function "__wrapped____EagerConst_device_/job:localhost/replica:0/task:0/device:GPU:0" with target device "/job:localhost/replica:0/task:0/device:GPU:0". Took 0 secs.
2023-03-08 10:44:30.185432: I tensorflow/core/common_runtime/process_function_library_runtime.cc:586] Finished graph optimizations for MultiDevice function "__wrapped__RandomUniformInt_device_/job:localhost/replica:0/task:0/device:GPU:0" with target device "/job:localhost/replica:0/task:0/device:GPU:0". Took 0 secs.
2023-03-08 10:44:30.193600: I tensorflow/core/common_runtime/process_function_library_runtime.cc:586] Finished graph optimizations for MultiDevice function "__wrapped__Cast_device_/job:localhost/replica:0/task:0/device:CPU:0" with target device "/job:localhost/replica:0/task:0/device:CPU:0". Took 0 secs.
2023-03-08 10:44:30.195940: I tensorflow/core/common_runtime/process_function_library_runtime.cc:586] Finished graph optimizations for MultiDevice function "__wrapped__RandomUniform_device_/job:localhost/replica:0/task:0/device:GPU:0" with target device "/job:localhost/replica:0/task:0/device:GPU:0". Took 0 secs.
2023-03-08 10:44:30.201918: I tensorflow/core/common_runtime/process_function_library_runtime.cc:586] Finished graph optimizations for MultiDevice function "__wrapped__QuantizedConv2D_device_/job:localhost/replica:0/task:0/device:CPU:0" with target device "/job:localhost/replica:0/task:0/device:CPU:0". Took 0 secs.
2023-03-08 10:44:30.202557: F tensorflow/core/kernels/quantized_conv_ops.cc:572] Check failed: out_cols > 0 (0 vs. 0)
Aborted (core dumped)
```
</details>

### PR DESCRIPTION
**Pull request by SuryanarayanaY**
A checkfail can happen in `raw_ops.QuantizedConv2D` with invalid input shape i.e presence of `0` in input shape dimensions. Repro [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/96418887bc380751c49ce3206d6382df/nightly.ipynb).

Fixes #59927 .

### CODE REVIEW

File: tensorflow/core/kernels/quantized_conv_ops.cc [hunk 1]
```diff
@@ -492,6 +493,13 @@ class QuantizedConv2DOp : public OpKernel {
     // [ batch, in_rows, in_cols, in_depth ]
     const Tensor& input = context->input(0);
 
+    // validate for non zero dimensions of input.
+    int input_dims = input.shape().dims();
+    for (int i = 0; i < input_dims; ++i) {
+      OP_REQUIRES(context, input.shape().dim_size(i) != 0,
+                  absl::InvalidArgumentError(
+                      "Invalid input: Shapes dimension cannot be 0."));
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/quantized_conv_ops.cc:501]:
```suggestion
    for (int i = 0; i < input_dims; ++i) {
      OP_REQUIRES(context, input.shape().dim_size(i) != 0,
                  absl::InvalidArgumentError(
                      "Invalid input: Shapes dimension cannot be 0."));
    }
```

(missing closing brace)

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]

File: tensorflow/core/kernels/quantized_conv_ops.cc [hunk 2]
```diff
@@ -492,6 +493,14 @@ class QuantizedConv2DOp : public OpKernel {
     // [ batch, in_rows, in_cols, in_depth ]
     const Tensor& input = context->input(0);
 
+    // validate for non zero dimensions of input.
+    int input_dims = input.shape().dims();
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/quantized_conv_ops.cc:497]: Nit: input_dims here is the rank of the tensor, that is a more readable name

(don't change now, only if we need to do other changes to the PR)

**Review by mihaimaruseac — APPROVED** [review]
