### PR TITLE
Validate null pointer dereference

### LINKED ISSUE #60220: Null pointer dereference in conv_ops_fused_int8.cc
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.12

### Custom Code

No

### OS Platform and Distribution

_No response_

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current Behaviour?

```shell
Pointer `side_input_ptr` is dereferenced and passed as the first argument into a call to `std::fmaf` in `tensorflow/core/kernels/conv_ops_fused_int8.cc`.  

If we are at 0th iteration in a `for`-loop (line 210) and `side_input_base == nullptr` then `col == 0` and `side_input_ptr` will also equal `nullptr` (line 265). After assign to `side_input_ptr`, this pointer is dereferenced on line 269.
```

### Standalone code to reproduce the issue

```shell
Bug was found by Svace static analysis tool.
```

### Relevant log output

_No response_</details>

### PR DESCRIPTION
**Pull request by sachinprasadhs**
Added validation to check if the null pointer is dereferenced before executing the code.
Fixes: https://github.com/tensorflow/tensorflow/issues/60220

### CODE REVIEW

File: tensorflow/core/kernels/conv_ops_fused_int8.cc [hunk 1]
```diff
@@ -261,7 +261,7 @@ struct LaunchFusedConv2DOpCpuInt8Helper {
         }
 
         // (2) Side input.
-        if (side_input_scale != 0.0f) {
+        if (side_input_scale != 0.0f && side_input_ptr != nullptr) {
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/conv_ops_fused_int8.cc:264]: `side_input_ptr` undefined at this line

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]

File: tensorflow/core/kernels/conv_ops_fused_int8.cc (hunk 1 above)
Comment (sachinprasadhs) [reply tensorflow/core/kernels/conv_ops_fused_int8.cc]: My bad, I corrected it to refer `side_input_base` instead of `side_input_ptr`

File: tensorflow/core/kernels/conv_ops_fused_int8.cc [hunk 2]
```diff
@@ -261,7 +261,7 @@ struct LaunchFusedConv2DOpCpuInt8Helper {
         }
 
         // (2) Side input.
-        if (side_input_scale != 0.0f) {
+        if (side_input_scale != 0.0f && side_input_base != nullptr) {
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/conv_ops_fused_int8.cc:264]: Now this will be a silent error and an additional condition check in a tight loop (perf degradation).

Instead, we should validate this as soon as it is initialized (line 208), return an error status (requires refactoring function to actually return Status instead of silently failing).

**Comment by mihaimaruseac** [comment]
Let's try with this fix, but if test fail let's do the real larger change that handles this better (https://github.com/tensorflow/tensorflow/pull/60296#discussion_r1163413390)

**Review by mihaimaruseac — APPROVED** [review]
