### PR TITLE
Fix #41630: include max_seq_length in cudnn descriptor cache key

### LINKED ISSUE #41630: CudnnLSTM variable sequence length sometimes fails with CUDNN_STATUS_EXECUTION_FAILED
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian/Sid (2020-07-01), Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source and binary
- TensorFlow version (use command below): 1.15
- Python version: 3.6, 3.7.8
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 9.0
- CUDA/cuDNN version: 10.0/7.4.1 ; 10.0/7.4.2.1 ; 10.0/7.5.1.10 ; 10.0/7.6.5.32
- GPU model and memory: 2x RTX 2080 Ti ; 4x GTX 1080 Ti ; 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`: v1.15.3-0-g4386a6640c

**Describe the current behavior**
Training with some dataset triggers:
```
2020-07-22 16:15:42.108252: E tensorflow/stream_executor/dnn.cc:588] CUDNN_STATUS_EXECUTION_FAILED                                                                                                          
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1778): 'cudnnRNNForwardTrainingEx( cudnn.handle(), rnn_desc.handle(), input_desc.data_handle(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), rnn_desc.params_handle(), params.opaque(), output_desc.data_handle(), output_data->opaque(), output_h_desc.handle(), output_h_data->opaque(), output_c_de
sc.handle(), output_c_data->opaque(), nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'
2020-07-22 16:15:42.108385: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at cudnn_rnn_ops.cc:1527 : Internal: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 2048, 2048, 1, 75, 2, 2048] 
```

**Describe the expected behavior**
Training should succeed, or TensorFlow or CUDNN should expose a more actionable error

**Standalone code to reproduce the issue**
Will be provided after.

**Other info / logs**
Will be provided after. Some noisy debugging session can be seen at https://github.com/mozilla/DeepSpeech/issues/3088

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

File: tensorflow/core/kernels/cudnn_rnn_ops.cc [hunk 1]
```diff
@@ -508,7 +508,7 @@ struct CudnnRnnModelShapes {
   bool IsCompatibleWith(const CudnnRnnModelShapes& rhs) const {
     return num_layers == rhs.num_layers && input_size == rhs.input_size &&
            num_units == rhs.num_units && dir_count == rhs.dir_count &&
-           cell_num_units == rhs.cell_num_units;
+           cell_num_units == rhs.cell_num_units && max_seq_length == rhs.max_seq_length;
```
Comment (sanjoy) [inline tensorflow/core/kernels/cudnn_rnn_ops.cc:511]: Let's add a `static_assert` on the size of the struct here so that we're reminded to update this method if we ever add new fields.

Comment (lissyx) [reply tensorflow/core/kernels/cudnn_rnn_ops.cc:511]: @sanjoy Sure, something like `static_assert(sizeof(*this) == x);` ?

Comment (lissyx) [reply tensorflow/core/kernels/cudnn_rnn_ops.cc:511]: That might sound a bit stupid, but I'm unsure whether you refer to `sizeof()` or something else more tensorflow specific: to the best of my knowledge sizeof(struct) has no guarantee to the the sum of its members size, so I'm unsure exactly what you have in mind here when you refer to "the size of the struct" :/

Comment (sanjoy) [reply tensorflow/core/kernels/cudnn_rnn_ops.cc:511]: I was talking about `sizeof`.  It is true that adding a new field will not necessarily increase the `sizeof` value, but it usually will and can be a good "quick and dirty" way to ensure that someone adding a new field remembers to update `IsCompatibleWith` and `CudnnRnnConfigHasher`.

Comment (lissyx) [reply tensorflow/core/kernels/cudnn_rnn_ops.cc:511]: Hm, basic strict equality does not work for me at all :[
```
diff --git a/tensorflow/core/kernels/cudnn_rnn_ops.cc b/tensorflow/core/kernels/cudnn_rnn_ops.cc
index a7a80e25f4..503cc9cd6d 100644
--- a/tensorflow/core/kernels/cudnn_rnn_ops.cc
+++ b/tensorflow/core/kernels/cudnn_rnn_ops.cc
@@ -506,6 +506,20 @@ struct CudnnRnnModelShapes {
   TensorShape cell_state_shape;
   // At present only fields related to cached RnnDescriptor are concerned.
   bool IsCompatibleWith(const CudnnRnnModelShapes& rhs) const {
+    // Ensure the size of structure does not change, this will help
+    // people adding new field not forgetting about adding those fields to
+    // IsCompatibleWith()
+    static_assert(sizeof(struct CudnnRnnModelShapes) == sizeof(int /* num_layers */)
+                                 + sizeof(int /* input_size */)
+                                + sizeof(int /* num_units */)
+                                + sizeof(int /* dir_count */)
+                                + sizeof(int /* max_seq_length */)
+                                + sizeof(int /* batch_size */)
+                                + sizeof(int /* cell_num_units */)
+                                + sizeof(TensorShape /* input_shape */)
+                                + sizeof(TensorShape /* output_shape */)
+                                + sizeof(TensorShape /* hidden_state_shape */)
+                                + sizeof(TensorShape /* cell_state_shape */), "check struct CudnnRnnModelShapes members");
     return num_layers == rhs.num_layers && input_size == rhs.input_size &&
            num_units == rhs.num_units && dir_count == rhs.dir_count &&
            cell_num_units == rhs.cell_num_units && max_seq_length == rhs.max_seq_length;
```

Comment (lissyx) [reply tensorflow/core/kernels/cudnn_rnn_ops.cc:511]: Greater or equal works, but I don't think it's really a useful check here :/

Comment (lissyx) [reply tensorflow/core/kernels/cudnn_rnn_ops.cc:511]: FTR:
```
sizeof(struct CudnnRnnModelShapes) == 128
sizeof(int) * 7 == 28
sizeof(TensorShape) * 4 == 96
```

We could test for `sizeof(struct CudnnRnnModelShapes) >= 124 && sizeof(struct CudnnRnnModelShapes) <= 128`, but I feel it might blow easily :/

Comment (lissyx) [reply tensorflow/core/kernels/cudnn_rnn_ops.cc:511]: Like, the static assert still works if I add a `char` or even an `int`, since the compiler can fit in the new entry within the padding it seems to have added. If you have a better idea, I'd be happy to implement it.

Comment (sanjoy) [reply tensorflow/core/kernels/cudnn_rnn_ops.cc:521]: Ok, probably then just a comment under `int cell_num_units = 0;` stating that if someone adds a new field they should also update the equality and hash functions?

Comment (lissyx) [reply tensorflow/core/kernels/cudnn_rnn_ops.cc:521]: Done :)

File: tensorflow/core/kernels/cudnn_rnn_ops.cc [hunk 2]
```diff
@@ -500,6 +500,9 @@ struct CudnnRnnModelShapes {
   int max_seq_length;
   int batch_size;
   int cell_num_units = 0;
+  // TODO: If you add new field to that structure, please take care of
```
Comment (sanjoy) [inline tensorflow/core/kernels/cudnn_rnn_ops.cc:503]: Please delete the `TODO` since that has a very specific meaning.  And s/that/this/

**Review by sanjoy — COMMENTED** [review]
Looks fine to me, but I'll wait for @kaixih to LGTM also.

**Review by sanjoy — CHANGES_REQUESTED** [review]
Actually, can you please also add a test case?

**Comment by lissyx** [comment]
> Actually, can you please also add a test case?

I can't find any existing test file supporting what is in `tensorflow/core/kernels/cudnn_rnn_ops.cc`, and the coverage of `CONTRIBUTING.md` for tests is quite scarce, it just covers how to run them. Would you have some pointers on where I should add test case?

**Comment by lissyx** [comment]
> > Actually, can you please also add a test case?
> 
> I can't find any existing test file supporting what is in `tensorflow/core/kernels/cudnn_rnn_ops.cc`, and the coverage of `CONTRIBUTING.md` for tests is quite scarce, it just covers how to run them. Would you have some pointers on where I should add test case?

Managed to add something as a new `tf_cuda_cc_test`, so it required some new headers and moving the two structs into that. It gets more invasise of a patch than I hoped for at the begining, but locally tests runs well and catches the regression.

**Comment by kaixih** [comment]
I am wondering if it is possible to limit the test into the python test, like in the lstm_v2_test.py. All we need to do is to design a simple training as in the issue 41630 that uses [1, 2048, 2048, 1, **74**, 2, 2048] in the first step and store it to the cache but [1, 2048, 2048, 1, **75**, 2, 2048] in the second step. If this can be successfully trained on GPU, we can view it as passed. How do you think?

**Comment by lissyx** [comment]
> I am wondering if it is possible to limit the test into the python test, like in the lstm_v2_test.py. All we need to do is to design a simple training as in the issue 41630 that uses [1, 2048, 2048, 1, **74**, 2, 2048] in the first step and store it to the cache but [1, 2048, 2048, 1, **75**, 2, 2048] in the second step. If this can be successfully trained on GPU, we can view it as passed. How do you think?

I can look into that, it would sounds like a better option than the current test I wrote.

**Comment by lissyx** [comment]
>  lstm_v2_test.py.

Do you know if there's any magic to run python tests required? I've followed `CONTRIBUTING.md` section about running unit tests, but
```
bazel test -s --verbose_failures --config=noaws --config=nogcp --config=nohdfs --config=nonccl -c opt --config=cuda -k //tensorflow/python/keras/layers
[...]
INFO: Analyzed target //tensorflow/python/keras/layers:layers (0 packages loaded, 0 targets configured).
INFO: Found 1 target and 0 test targets...
Target //tensorflow/python/keras/layers:layers up-to-date (nothing to build)
INFO: Elapsed time: 0.336s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
```

**Comment by kaixih** [comment]
Have you tried to simply run `python lstm_v2_test.py`?

**Comment by lissyx** [comment]
> Have you tried to simply run `python lstm_v2_test.py`?

Even simpler: ` //tensorflow/python/keras/layers:lstm_v2_test` bazel target, I assumed passing the directory would run all tests there.

**Comment by lissyx** [comment]
@kaixih Having a look around, I'm wondering if `tensorflow/python/keras/layers/cudnn_recurrent_test.py` would not be a better fit ?

**Comment by lissyx** [comment]
I'm not sure what I'm doing wrong, but running either `lstm_v2_test` or `cudnn_recurrent_test` with CUDA is not really working as expected, I'm having a ton of CUDA/CUDNN errors not to mention reports of GPU being out of memory (and yet I have 2x RTX2080 Ti).

I'm just running following the docs:
```
LD_LIBRARY_PATH=$HOME/Documents/codaz/Mozilla/DeepSpeech/CUDA-10.1/lib64 bazel test -s --verbose_failures --config=noaws --config=nogcp --config=nohdfs --config=nonccl -c opt --config=cuda -k //tensorflow/python/keras/layers:lstm_v2_test
LD_LIBRARY_PATH=$HOME/Documents/codaz/Mozilla/DeepSpeech/CUDA-10.1/lib64 bazel test -s --verbose_failures --config=noaws --config=nogcp --config=nohdfs --config=nonccl -c opt --config=cuda -k //tensorflow/python/keras/layers:cudnn_recurrent_test
```

And running those generates already a ton of errors (not to mention it requires several minutes to run), so I'm not 100% certain of what I am doing.

**Comment by lissyx** [comment]
> I'm not sure what I'm doing wrong, but running either `lstm_v2_test` or `cudnn_recurrent_test` with CUDA is not really working as expected, I'm having a ton of CUDA/CUDNN errors not to mention reports of GPU being out of memory (and yet I have 2x RTX2080 Ti).
> 
> I'm just running following the docs:
> 
> ```
> LD_LIBRARY_PATH=$HOME/Documents/codaz/Mozilla/DeepSpeech/CUDA-10.1/lib64 bazel test -s --verbose_failures --config=noaws --config=nogcp --config=nohdfs --config=nonccl -c opt --config=cuda -k //tensorflow/python/keras/layers:lstm_v2_test
> LD_LIBRARY_PATH=$HOME/Documents/codaz/Mozilla/DeepSpeech/CUDA-10.1/lib64 bazel test -s --verbose_failures --config=noaws --config=nogcp --config=nohdfs --config=nonccl -c opt --config=cuda -k //tensorflow/python/keras/layers:cudnn_recurrent_test
> ```
> 
> And running those generates already a ton of errors (not to mention it requires several minutes to run), so I'm not 100% certain of what I am doing.

Ok, at least adding a new dedicated file `cudnn_var_seq_length.py` to run the test locally works, so I can use that to run it locally and when it's good put the test in `lstm_v2_test.py`

**Comment by lissyx** [comment]
@kaixih Do you think this https://github.com/tensorflow/tensorflow/blob/deba51f80e05775bb4cc83647b475802be58f1e4/tensorflow/python/keras/layers/lstm_v2_test.py#L344-L345 would be a good start for exposing variable sequence length issue?

**Comment by lissyx** [comment]
@kaixih I'm really sorry, I'm trying to hack something based on the test linked above, but:
 - I know nothing about the Keras API
 - And our current code that triggers the issue is for 1.15, so it relies on directly calling `CudnnLSTM` from `tensorflow.contrib`, which is not possible anymore, so it's hard to have a 1:1 parity here
 - I can't figure out how in the linked test above this is acting on the variable sequence length
 - Even running the test on the GPU, it does not look like this code triggers `IsCompatibleWith` from `CudnnRnnModelShapes`

So to be able to write this test, I think I'd need more guidance on how to do things ...

**Comment by lissyx** [comment]
Trying something like:
```
  @test_util.run_gpu_only
  def test_lstm_variable_sequence_length(self):
    if test.is_built_with_rocm():
      self.skipTest('Skipping the test as ROCm MIOpen does not '
                    'support padded input yet.')
    input_shape = 10
    rnn_state_size = 8
    timestep = 1
    batch = 2

    (x_train, y_train), _ = testing_utils.get_test_data(
        train_samples=batch,
        test_samples=0,
        input_shape=(timestep, input_shape),
        num_classes=rnn_state_size,
        random_seed=random_seed.DEFAULT_GRAPH_SEED)

    input_shape = 11
    rnn_state_size = 8
    timestep = 1
    batch = 2

    (x2_train, y2_train), _ = testing_utils.get_test_data(
        train_samples=batch,
        test_samples=0,
        input_shape=(timestep, input_shape),
        num_classes=rnn_state_size,
        random_seed=random_seed.DEFAULT_GRAPH_SEED)

    inputs = keras.layers.Input(
        shape=[timestep, input_shape], dtype=dtypes.float32)
    masked_input = keras.layers.Masking()(inputs)

    with test_util.device(use_gpu=True):
      cudnn_layer = rnn_v1.LSTM(rnn_state_size)
      cudnn_model = keras.models.Model(inputs, cudnn_layer(masked_input))

    cudnn_model.compile('rmsprop', 'mse')
    cudnn_model.fit(x_train, y_train)
    cudnn_model.fit(x2_train, y2_train)
```

Does not work at all: `ValueError: Input 0 is incompatible with layer lstm: expected shape=(None, None, 11), found shape=[None, 1, 10]` but I have a hard time being sure this `input_shape` is actually where the change of dimension should happen.

**Comment by lissyx** [comment]
Making progresses:
```
  @test_util.run_gpu_only
  def test_lstm_variable_sequence_length(self):
    if test.is_built_with_rocm():
      self.skipTest('Skipping the test as ROCm MIOpen does not '
                    'support padded input yet.')
    input_shape = 2048
    rnn_state_size = 2048
    batch = 2

    timestep = 1

    (x_train, y_train), _ = testing_utils.get_test_data(
        train_samples=batch,
        test_samples=0,
        input_shape=(timestep, input_shape),
        num_classes=rnn_state_size,
        random_seed=random_seed.DEFAULT_GRAPH_SEED)

    timestep = 1

    (x2_train, y2_train), _ = testing_utils.get_test_data(
        train_samples=batch,
        test_samples=0,
        input_shape=(timestep, input_shape),
        num_classes=rnn_state_size,
        random_seed=random_seed.DEFAULT_GRAPH_SEED)

    inputs = keras.layers.Input(
        shape=[timestep, input_shape], dtype=dtypes.float32)
    masked_input = keras.layers.Masking()(inputs)

    with test_util.device(use_gpu=True):
      cudnn_layer = rnn.LSTM(rnn_state_size,
                             activation='tanh',
                             recurrent_activation='sigmoid',
                             recurrent_dropout=0,
                             unroll=False,
                             use_bias=True)
      cudnn_model = keras.models.Model(inputs, cudnn_layer(masked_input))

    cudnn_model.compile('rmsprop', 'mse')
    cudnn_model.fit(x_train, y_train)
    cudnn_model.fit(x2_train, y2_train)
```

With that, I can assert that it is going through the layers and reaches `IsCompatibleWith`:
```

IsCompatibleWith -> [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 2048, 2048, 1, 1, 2, 2048] 
IsCompatibleWith -> [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 2048, 2048, 1, 1, 2, 2048] 
IsCompatibleWith -> [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 2048, 2048, 1, 1, 2, 2048] 
IsCompatibleWith -> [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 2048, 2048, 1, 1, 2, 2048] 
IsCompatibleWith -> [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 2048, 2048, 1, 1, 2, 2048] 
IsCompatibleWith -> [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 2048, 2048, 1, 1, 2, 2048] 
```

However, changing `timestep` to be `74` on `x_train` and `75` on `x2_train` seems to bypass the GPU implementation, because I can't see any `IsCompatibleWith` output in the log but I see:
```
WARNING:tensorflow:Model was constructed with shape (None, 75, 2048) for input Tensor("input_1:0", shape=(None, 75, 2048), dtype=float32), but it was called on an input with incompatible shape (None, 74, 2048).
W0731 11:00:01.229415 139681924948352 functional.py:583] Model was constructed with shape (None, 75, 2048) for input Tensor("input_1:0", shape=(None, 75, 2048), dtype=float32), but it was called on an input with incompatible shape (None, 74, 2048).
```

**Comment by lissyx** [comment]
Even directly calling `CuDNNLSTM` from `tensorflow/python/keras/layers/cudnn_recurrent.py` I'm blocked at Keras level when adding the 74/75 dimensional difference.

**Comment by lissyx** [comment]
So @kaixih I force-pushed removing the C++ test, and I'm unsure how to pursue and add a proper test, since the Keras layers appears to be blocking me, and that seems completely un-avoidable, and it does not seems that v2.x allows for very raw graph creation (and I have to be honest, it would take me a lot of time to get up to speed because all my reading points to the fact all the code we did cannot be used as a source of inspiration).

**Comment by kaixih** [comment]
@lissyx For the test you pasted above, I think giving the input tensors with different shapes ([xx, 74, xx] vs [xx, 75, xx] will trigger TF function retracing and creating different graphs for the two inputs. So, there is no cached rnn states in the second case.

For the cudnn_recurrent.py, I think it doesn't support the variable sequence lengths. So, maybe it is not for this case.

It seems that you can repro it with TF1 script. Can you share the TF code snippet to repro the issue? Then, we can see how to make it into python test.

**Comment by lissyx** [comment]
> Can you share the TF code snippet to repro the issue? Then, we can see how to make it into python test.

Unfortunately, it's not just isolated as a snippet, one would need to re-write it from scratch in tensorflow 1.15, but if that helps, I'll do it

**Comment by kaixih** [comment]
I am wondering how hard it would be to extract it as a unit test. Actually, I attempted to make a new test by giving a graph containing one lstm node the 74 shape and then 75 shape, but it seems the graph can always create a new rnn descriptor for it. So, I am kind of curious how you hit the error and if this case can be extracted, that would be helpful.

**Comment by lissyx** [comment]
> I am wondering how hard it would be to extract it as a unit test. Actually, I attempted to make a new test by giving a graph containing one lstm node the 74 shape and then 75 shape, but it seems the graph can always create a new rnn descriptor for it. So, I am kind of curious how you hit the error and if this case can be extracted, that would be helpful.

Ok, that is what I was trying to do. We hit the error when running training using deepspeech, using repro material from https://github.com/tensorflow/tensorflow/issues/41630#issuecomment-662491897

**Review by kaixih — APPROVED** [review]

**Review by sanjoy — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by lissyx** [comment]
Can we hope for a 1.15.4 to include that fix ?

**Comment by sanjoy** [comment]
> Can we hope for a 1.15.4 to include that fix ?

CC @goldiegadde

**Comment by lissyx** [comment]
> > Can we hope for a 1.15.4 to include that fix ?
> 
> CC @goldiegadde

Gentle ping, can we hope for 1.15.4 or should we direct people hitting this issue to use the magic reset state env variable?

**Comment by lissyx** [comment]
@sanjoy @kaixih @goldiegadde Gentle ping? There has been several commit pushed to r1.15, so it would really be nice to include this one if you are preparing a 1.15.4. I can send the PR if you'd like.

**Comment by goldiegadde** [comment]
@lissyx Sorry for the delayed response, can you please open a PR against the 1.15 branch. cc @mihaimaruseac as well.

**Comment by mihaimaruseac** [comment]
Apologies, I missed this myself too. Yes, please, let's open a PR against the branch

**Comment by lissyx** [comment]
> @lissyx Sorry for the delayed response, can you please open a PR against the 1.15 branch. cc @mihaimaruseac as well.

https://github.com/tensorflow/tensorflow/pull/42634
