### PR TITLE
Fix LSTMBlockCell Check Fail

### LINKED ISSUE #58270: A check fail can be triggered in LSTMBlockCell
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.12.0-dev20221018

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

_No response_

### Python version

3.8

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

CUDA 11.5

### GPU model and memory

_No response_

### Current Behaviour?

```shell
A crash due to check fail can be trigerred.
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
import numpy as np
print(tf.__version__)
for _ in range(20):
    try:
        forget_bias = 112.66590343649887
        cell_clip = 67.12389445926587
        use_peephole = False
        x = tf.saturate_cast(tf.random.uniform([2, 16], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        cs_prev = tf.saturate_cast(tf.random.uniform([2, 0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        h_prev = tf.saturate_cast(tf.random.uniform([2, 0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        w = tf.saturate_cast(tf.random.uniform([16, 0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        wci = tf.saturate_cast(tf.random.uniform([5], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        wcf = tf.saturate_cast(tf.random.uniform([16], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        wco = tf.saturate_cast(tf.random.uniform([13], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        b = tf.saturate_cast(tf.random.uniform([0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        res = tf.raw_ops.LSTMBlockCell(
            forget_bias=forget_bias,
            cell_clip=cell_clip,
            use_peephole=use_peephole,
            x=x,
            cs_prev=cs_prev,
            h_prev=h_prev,
            w=w,
            wci=wci,
            wcf=wcf,
            wco=wco,
            b=b,
        )
    except:
        pass
```

### Relevant log output

```shell
F tensorflow/core/kernels/rnn/lstm_ops_gpu.cu.cc:277] Non-OK-status: GpuLaunchKernel( lstm_gates<T, false, gate_layout>, grid_dim_2d, block_dim_2d, 0, cu_stream, gates.data(), b.data(), cs_prev.data(), wci.data(), wcf.data(), wco.data(), o.data(), h.data(), ci.data(), cs.data(), co.data(), i.data(), f.data(), forget_bias, cell_clip, batch_size, cell_size) status: INTERNAL: invalid configuration argument
Aborted (core dumped)
```
</details>

### PR DESCRIPTION
**Pull request by mattbahr**
Fixes #58270

### CODE REVIEW

**Comment by mattbahr** [comment]
Forgot to include the first argument for `OP_REQUIRES_OK`. I think that should fix the build

**Review by mihaimaruseac — COMMENTED** [review]
Looks good so far, but only hides the check fail and opens the potential for more vulns as it is. We need to stop execution of the kernel, not just this function

**Comment by mattbahr** [comment]
@mihaimaruseac thanks for the review! I am not sure I understand the difference between what you are asking for and the original behavior where the check fail would trigger a crash. Do you mind expanding on that a little bit?

**Comment by mihaimaruseac** [comment]
`CHECK` fail results in a crash. `OP_REQUIRES_OK` sets `ctx->Status` to return it to client and finishes execution of current function (it is a macro that ends with `return;`).

Basically the issue is

```cc
void LSTMBlockCellFpropWithCUDA(OpKernelContext* ctx,,...) {
  CHECK(expr);
  ...
}

void LSTMBlockCell::Compute(OpKernelContext* ctx,...) {
  // do some validation
  LSTMBlockCellFpropWithCUDA(ctx, ...);
  // assume validation passed
  RunSomeOtherCode(...);
}
```

Right now, `RunSomeOtherCode` does not run because the `CHECK`-fail terminates the process. What we want is still for `RunSomeOtherCode` to not run! If you just replace it with `OP_REQUIRES`, after expanding the macros the code would be

```cc
void LSTMBlockCellFpropWithCUDA(OpKernelContext* ctx,,...) {
  if(expr) {
     ctx->Status = errors::InvalidArgument(...);
     return; // <----------- this line
  }
  ...
}

void LSTMBlockCell::Compute(OpKernelContext* ctx,...) {
  // do some validation
  LSTMBlockCellFpropWithCUDA(ctx, ...);
  // !!!!! You still need to stop executing the kernel here if ctx->Status is not Ok !!!
  // assume validation passed
  RunSomeOtherCode(...);
}
```

Now how the `return` will just terminate `LSTMBlockCellFpropWithCUDA` but if you don't change the `Compute` call then `RunSomeOtherCode` would run when we know that validation already failed. So this causes more harm than just a process crash

**Comment by mattbahr** [comment]
Ok, that makes sense. Thanks for your help! I didn't realize how the macro worked. I think this latest commit accomplishes what you're saying, but just let me know if you think anything needs to change

**Comment by swachhandl** [comment]
Were you able to test your changes and see if the check fail isn't being triggered anymore? 
Please also add unit tests that test your change. 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/nn_ops/rnn_cell_test.py or
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/cudnn_rnn_ops_test.cc could be relevant places to add them.

**Comment by mattbahr** [comment]
Thanks for the pointers on the unit tests! I'll get those added soon. When I test locally against the error case from the related issue, I get the following error logs, but Python no longer crashes:
` ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.460448: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.460510: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.465759: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.465774: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.470031: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.470046: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.474474: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.474486: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.478711: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.478723: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.482907: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.482920: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.487107: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.487120: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.492341: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.492353: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.496483: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.496495: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.500759: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.500771: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.504896: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.504908: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.508996: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.509008: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.513247: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.513259: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.517478: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.517490: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.522420: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.522433: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.526810: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.526822: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.530964: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.530976: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.535143: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.535155: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.539309: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.539321: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument
 ** On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-10 06:55:35.543485: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: cublas error
2023-02-10 06:55:35.543498: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at lstm_ops_gpu.cu.cc:277 : INTERNAL: invalid configuration argument`

File: tensorflow/core/kernels/rnn/lstm_ops.cc [hunk 1]
```diff
@@ -1046,7 +1046,7 @@ class BlockLSTMOp : public OpKernel {
       Tensor co_tensor = slicer.OutputSlice(co_out, t, "co_out");
       Tensor h_tensor = slicer.OutputSlice(h_out, t, "h_out");
 
-      functor::LSTMBlockCellFprop<Device, T, USE_CUBLAS, gate_layout>(
+      OP_REQUIRES_OK(ctx, functor::LSTMBlockCellFprop<Device, T, USE_CUBLAS, gate_layout>(
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/rnn/lstm_ops.cc]: Since this is in a helper, you must also validate `ctx->Status` after each call of the helper, since `OP_REQUIRES_OK` in the end is just setting `ctx->Status` and then `return`-ing

Comment (mattbahr) [reply tensorflow/core/kernels/rnn/lstm_ops.cc]: So I actually altered this in a more recent commit because the build fails when I call `OP_REQUIRES_OK` here with an `error: invalid use of void expression`. Instead, I implemented a check on `ctx->Status` like you're saying.

**Comment by mattbahr** [comment]
@swachhandl My ARM CI build is failing for the `testLSTMBlockCellErrorHandling2` unit test that I added to `rnn_cell_test.py`. Do you have any suggestions for things I could try to fix it? Could it be that maybe I'm using the wrong `@test_util` annotation? When I run the unit test locally it passes.

**Review by mihaimaruseac — APPROVED** [review]
This looks good, thank you.

Approving so it also gets imported internally and more tests run on it.

**Comment by swachhandl** [comment]
> @swachhandl My ARM CI build is failing for the `testLSTMBlockCellErrorHandling2` unit test that I added to `rnn_cell_test.py`. Do you have any suggestions for things I could try to fix it? Could it be that maybe I'm using the wrong `@test_util` annotation? When I run the unit test locally it passes.

It seems your test is failing on ARM/Ubuntu/Mac CPU CI but passes on Ubuntu GPU. Can you check if the CPU version is failing because it's not throwing any error (and hence, failing the assert)? 

If the CPU version isn't throwing _any_ error, I think the ideal solution would be to make the GPU version also return the same result as the CPU counterpart (instead of returning an error).

**Comment by mattbahr** [comment]
> > @swachhandl My ARM CI build is failing for the `testLSTMBlockCellErrorHandling2` unit test that I added to `rnn_cell_test.py`. Do you have any suggestions for things I could try to fix it? Could it be that maybe I'm using the wrong `@test_util` annotation? When I run the unit test locally it passes.
> 
> It seems your test is failing on ARM/Ubuntu/Mac CPU CI but passes on Ubuntu GPU. Can you check if the CPU version is failing because it's not throwing any error (and hence, failing the assert)?
> 
> If the CPU version isn't throwing _any_ error, I think the ideal solution would be to make the GPU version also return the same result as the CPU counterpart (instead of returning an error).

So this is the CPU variant of the code:
https://github.com/tensorflow/tensorflow/blob/ed3e77f858fdba02e6cc402ddb9a9d722c9d158e/tensorflow/core/kernels/rnn/lstm_ops.cc#L73-L126

And then this is the GPU code:
https://github.com/tensorflow/tensorflow/blob/ed3e77f858fdba02e6cc402ddb9a9d722c9d158e/tensorflow/core/kernels/rnn/lstm_ops_gpu.cu.cc#L98-L194

I guess one or more of the assumptions spelled out in the comment are causing the error. I try to add some validations and see how that affects things.

**Comment by mattbahr** [comment]
@swachhandl I confirmed that when run on the CPU, no error is thrown, but I'm having a hard time finding a way to get the GPU code to behave in same way. Would it be valid to mark this test case to run only on GPU?

**Comment by swachhandl** [comment]
Can you pull master and see if the error for GPU still persists? A recent commit (https://github.com/tensorflow/tensorflow/commit/764eae38919b45556373a320af1079ac54e70521) might have fixed it. Even if it's been fixed, propagating the error/checking the status is still useful.

**Comment by mattbahr** [comment]
@swachhandl I've been having issues building from source on my machine after merging master into my branch, so I figured I'd just test with the nightly build. The core is no longer being dumped, but an internal error is still being thrown when I run on GPU:
`On entry to SGEMM_EX  parameter number 8 had an illegal value
2023-02-20 02:32:30.937716: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: an unsupported value or parameter was passed to the function
`
No error is thrown on CPU, just as before.

**Comment by swachhandl** [comment]
> @swachhandl I've been having issues building from source on my machine after merging master into my branch, so I figured I'd just test with the nightly build. The core is no longer being dumped, but an internal error is still being thrown when I run on GPU:
> 
> ```
> 2023-02-20 02:32:30.937716: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: an unsupported value or parameter was passed to the function
> ```
> 
> No error is thrown on CPU, just as before.

Are you getting the internal error even after your changes related to error propagation? What's the result when you run this on CPU?

**Comment by mattbahr** [comment]
> > @swachhandl I've been having issues building from source on my machine after merging master into my branch, so I figured I'd just test with the nightly build. The core is no longer being dumped, but an internal error is still being thrown when I run on GPU:
> > ```
> > 2023-02-20 02:32:30.937716: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at blas_gemm.cc:52 : INTERNAL: an unsupported value or parameter was passed to the function
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No error is thrown on CPU, just as before.
> 
> Are you getting the internal error even after your changes related to error propagation? What's the result when you run this on CPU?

Ok, I got the build working after merging master into my branch earlier today. With my error propagation code in place it's still behaving the same way. I get the internal error when I run the on the GPU, but no error is produced when I run the same code on the CPU.

**Comment by swachhandl** [comment]
>  I get the internal error when I run the on the GPU, but no error is produced when I run the same code on the CPU.

Did you try investigating where the error is originating from? I'm not sure why it isn't being propagated with your changes in place.

**Comment by mattbahr** [comment]
> Did you try investigating where the error is originating from? I'm not sure why it isn't being propagated with your changes in place.

I tracked it down to this block of code, but I'm not sure exactly which line:
https://github.com/tensorflow/tensorflow/blob/ed3e77f858fdba02e6cc402ddb9a9d722c9d158e/tensorflow/core/kernels/rnn/lstm_ops_gpu.cu.cc#L98-L194

The CPU variant of the same code is a little different. I posted it in a comment earlier in the thread, so that might explain why the error is only being thrown on GPU.

**Comment by mattbahr** [comment]
> Did you try investigating where the error is originating from? I'm not sure why it isn't being propagated with your changes in place.

I was on the wrong track comparing those two functions in `lstm_ops.cc` and `lstm_ops_gpu.cu.cc`. The internal error is originating here:
https://github.com/tensorflow/tensorflow/blob/4139a2ada21479f923a850bf2708dfe077a22254/tensorflow/core/kernels/rnn/blas_gemm.cc#L52-L56

**Comment by mattbahr** [comment]
@swachhandl I think I'm getting closer. I found the line of code where the internal error is being thrown: 
https://github.com/tensorflow/tensorflow/blob/c99a73e9ee06d254ec5cafe4183d98342421827b/tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc#L388
That function is being called here with `cublasSgemmEx` acting as the `cublas_func`:
https://github.com/tensorflow/tensorflow/blob/c99a73e9ee06d254ec5cafe4183d98342421827b/tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc#L653-L658
From the error message: `** On entry to SGEMM_EX  parameter number 8 had an illegal value`, it looks like `a.opaque()` is returning an invalid value for the function `SGEMM_EX`

**Comment by mattbahr** [comment]
It looks like `a.opaque()` is returning a null pointer. I tried adding the following lines of code before the call to `DoBlasInternalImpl`, and my test error was triggered.

```
const void *test = a.opaque();

  if (!test) {
    return tsl::errors::Internal("TEST ERROR TRIGGERED");
  }
```

@swachhandl do you have any ideas on how we might handle this better?

**Comment by mattbahr** [comment]
The line in the `lstm_ops_gpu.cu.cc` file where the internal error is getting thrown seems to be this one:
https://github.com/tensorflow/tensorflow/blob/b9a128ea6397f3d49211bff68563846254734d5b/tensorflow/core/kernels/rnn/lstm_ops_gpu.cu.cc#L256-L258
It used to crash a few lines beyond that:
https://github.com/tensorflow/tensorflow/blob/b9a128ea6397f3d49211bff68563846254734d5b/tensorflow/core/kernels/rnn/lstm_ops_gpu.cu.cc#L269-L283
So that might explain why we're no longer seeing the core dump. I wonder if it has to do with this commit where `port::InternalError` was switched to `tsl::errors::Internal`: https://github.com/tensorflow/tensorflow/commit/a801af081952535b541852ad6ad96e0d536f2965#diff-9a98b7aa9b93a7357e8bbcdfc82739ef47c69251c684c6c4e58b3b1ff9cd4ac3

**Comment by swachhandl** [comment]
Apologies for the late response. I'm not quite sure that it could be happening due to switching out `port::InternalError` with `tsl::errors::Internal`. Are you able to check why `a.opaque()` is a nullptr? And how does it (or whether it even does) map to the input arguments to the op? If we can, we might be able to put a check in the op.

**Comment by cantonios** [comment]
I haven't looked into this deeply, but `nullptr`s usually come up with 0-sized inputs, and that has often been a cause of these CPU vs GPU different error behaviors, where the CPU returns a (valid) empty result, but the GPU crashes because CUDA doesn't often properly handle empty inputs.

**Comment by mattbahr** [comment]
> Apologies for the late response. I'm not quite sure that it could be happening due to switching out `port::InternalError` with `tsl::errors::Internal`. Are you able to check why `a.opaque()` is a nullptr? And how does it (or whether it even does) map to the input arguments to the op? If we can, we might be able to put a check in the op.

No problem! I'm pretty confident `a.opaque()` is our problem parameter. It is the 11th parameter for the call to `DoBlasInternalImpl`, which has four defined parameters, and then the rest of the `args` are passed to the `cublas_func`, which has one other parameter... 11 - 4 = 8 - 1

https://github.com/tensorflow/tensorflow/blob/c99a73e9ee06d254ec5cafe4183d98342421827b/tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc#L653-L658

https://github.com/tensorflow/tensorflow/blob/c99a73e9ee06d254ec5cafe4183d98342421827b/tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc#L356-L358

https://github.com/tensorflow/tensorflow/blob/c99a73e9ee06d254ec5cafe4183d98342421827b/tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc#L384

When I add the `CHECK(a.opaque() != nullptr)` the `InternalError` no longer gets thrown, and the behavior matches what I see on CPU.

File: tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc [hunk 2]
```diff
@@ -679,6 +679,8 @@ tsl::Status CUDABlas::DoBlasGemm(Stream *stream, blas::Transpose transa,
       static_cast<int>(transa), static_cast<int>(transb), m, n, k, alpha,
       a.opaque(), lda, b.opaque(), ldb, beta, c->opaque(), ldc);
 
+  CHECK(a.opaque() != nullptr);
+
```
Comment (mihaimaruseac) [inline tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:683]: This is adding a check fail back

**Comment by cantonios** [comment]
> When I add the `CHECK(a.opaque() != nullptr)` the `InternalError` no longer gets thrown, and the behavior matches what I see on CPU.

How can it match CPU?  I thought the CPU behavior _didn't_ crash.

File: tensorflow/python/kernel_tests/nn_ops/rnn_cell_test.py [hunk 3]
```diff
@@ -1354,6 +1354,35 @@ def testLSTMBlockCellErrorHandling(self):
               forget_bias=forget_bias,
               cell_clip=cell_clip,
               use_peephole=use_peephole))
+      
+  @test_util.run_gpu_only
```
Comment (cantonios) [inline tensorflow/python/kernel_tests/nn_ops/rnn_cell_test.py:1358]: We should have the same behavior between CPU and GPU - so the test should be common.  There may be differences in error messages, but this is usually handled by using a regex that accounts for both down below.

File: tensorflow/python/kernel_tests/nn_ops/rnn_cell_test.py [hunk 4]
```diff
@@ -1354,6 +1354,35 @@ def testLSTMBlockCellErrorHandling(self):
...
+    use_peephole = False
+    x = constant_op.constant(0, shape=[2, 16], dtype=dtypes.half)
+    cs_prev = constant_op.constant(0, shape=[2, 0], dtype=dtypes.half)
+    h_prev = constant_op.constant(0, shape=[2, 0], dtype=dtypes.half)
+    w = constant_op.constant(0, shape=[16, 0], dtype=dtypes.half)
+    wci = constant_op.constant(0, shape=[5], dtype=dtypes.half)
+    wcf = constant_op.constant(0, shape=[16], dtype=dtypes.half)
+    wco = constant_op.constant(0, shape=[13], dtype=dtypes.half)
+    b = constant_op.constant(0, shape=[0], dtype=dtypes.half)
+    with self.assertRaises(errors_impl.InternalError):
```
Comment (cantonios) [inline tensorflow/python/kernel_tests/nn_ops/rnn_cell_test.py:1372]: use `assertRaisesRegex` to ensure we're triggering the desired error.

**Review by cantonios — CHANGES_REQUESTED** [review]

File: tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc (hunk 2 above)
Comment (mattbahr) [reply tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc]: my mistake. just removed

**Comment by cantonios** [comment]
> And that's correct - it does not crash on CPU. It doesn't throw any error at all on CPU. I'm still kind of stumped as to how to get the behaviors to match.

What's the output on CPU?

**Comment by mattbahr** [comment]
> What's the output on CPU?

Here's what I get when I print the result on CPU:

```LSTMBlockCell(i=<tf.Tensor: shape=(2, 0), dtype=float16, numpy=array([], shape=(2, 0), dtype=float16)>, cs=<tf.Tensor: shape=(2, 0), dtype=float16, numpy=array([], shape=(2, 0), dtype=float16)>, f=<tf.Tensor: shape=(2, 0), dtype=float16, numpy=array([], shape=(2, 0), dtype=float16)>, o=<tf.Tensor: shape=(2, 0), dtype=float16, numpy=array([], shape=(2, 0), dtype=float16)>, ci=<tf.Tensor: shape=(2, 0), dtype=float16, numpy=array([], shape=(2, 0), dtype=float16)>, co=<tf.Tensor: shape=(2, 0), dtype=float16, numpy=array([], shape=(2, 0), dtype=float16)>, h=<tf.Tensor: shape=(2, 0), dtype=float16, numpy=array([], shape=(2, 0), dtype=float16)>)```

File: tensorflow/core/kernels/rnn/lstm_ops.cc [hunk 5]
```diff
@@ -424,6 +424,10 @@ class LSTMBlockCellOp : public OpKernel {
         ctx, cs_prev_tensor->dims() == 2,
         errors::InvalidArgument("cs_prev_tensor must be rank 2 but is rank ",
                                 cs_prev_tensor->dims(), "."));
+    OP_REQUIRES(ctx,
```
Comment (cantonios) [inline tensorflow/core/kernels/rnn/lstm_ops.cc:427]: This will now return an error if the tensor is empty - is this what we want?  And is this a breaking change if the original CPU kernel previously returned empty tensors?

We should also add a test for this.

**Review by cantonios — CHANGES_REQUESTED** [review]

File: tensorflow/core/kernels/rnn/lstm_ops.cc (hunk 5 above)
Comment (mattbahr) [reply tensorflow/core/kernels/rnn/lstm_ops.cc:427]: Ok, yea, I'm actually not sure what we want here either, but `cs_prev_tensor` is the input that is causing the issue. From what I got testing, there are validations that prevent the other inputs from being empty unless this one is empty. I take it instead of returning an error we want to return an empty tensor for GPU as well as CPU?

Comment (cantonios) [reply tensorflow/core/kernels/rnn/lstm_ops.cc:427]: Well, I guess that depends... if there's precedent here for returning an error for all empty tensors, then we can do that - and just hope that nobody was relying on the previous behavior on CPU.  I'm okay with that.

Let's add some tests for it though.

Comment (mattbahr) [reply tensorflow/core/kernels/rnn/lstm_ops.cc:427]: Ok, sounds good. I'll add some tests. I did just confirm it fails with the invalid argument on CPU as well so the behavior is at least the same.

File: tensorflow/python/kernel_tests/nn_ops/rnn_cell_test.py [hunk 6]
```diff
@@ -1354,6 +1354,62 @@ def testLSTMBlockCellErrorHandling(self):
               forget_bias=forget_bias,
               cell_clip=cell_clip,
               use_peephole=use_peephole))
+      
+  @test_util.run_in_graph_and_eager_modes
+  def testLSTMBlockCellErrorHandling2(self):
```
Comment (cantonios) [inline tensorflow/python/kernel_tests/nn_ops/rnn_cell_test.py:1359]: Make the names more descriptive - like `testLSTMBlockCellEmptyInputRaisesError`

You can also put the inputs directly into the `gen_rnn_ops.lstm_block_cell` call, rather than defining them first and repeating them in `x=x, cs_prev=cs_prev,...`.

I'm not sure you need two tests.

**Review by cantonios — APPROVED** [review]

**Comment by mattbahr** [comment]
ROCm CI build failure appears to be due to the removal of this constructor from `status.h` in commit: https://github.com/tensorflow/tensorflow/commit/667081b1c3d84c8fee4b5965d5e151158c74d4f8#diff-2497c155e2f97993a2cea18969d80f2d414e2f1b346cf006d8a8b655a8316b1d

Looks like other pull request builds are failing with the same errors.

**Review by cantonios — APPROVED** [review]

**Comment by mattbahr** [comment]
Just because I'm new to the project, would anybody mind filling me in on how the import/copybara works? At this point is it pending because the AMD ROCm and the MacOS CPU builds failed? I'm seeing other pull requests for which the import completed even though various builds failed

**Comment by mihaimaruseac** [comment]
The full process is at

image

Right now, this is pending Gerrit review. CC @gbaned
