### PR TITLE
 Fix crash in tf.nn.conv2d_transpose when output shape is invalid

### LINKED ISSUE #57958: tf.nn.conv2d_transpose abort with large `output_shape`
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Mobile device

_No response_

### Python version

3.7.6

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

N/A

### GPU model and memory

_No response_

### Current Behaviour?

```shell
tf.nn.conv2d_transpose crash with abort with large `output_shape`
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
tf.nn.conv2d_transpose(input=np.ones((2,2,2,2)), output_shape=[114078056, 179835296], strides=[10], filters=1)
```

### Relevant log output

```shell
2022-10-03 23:45:34.556541: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-10-03 23:45:34.556569: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2022-10-03 23:45:34.556596: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2022-10-03 23:45:34.556893: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-03 23:45:34.595200: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 41030521935729152 with 22001, result: -1
Aborted (core dumped)
```
</details>

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to address the issue in #57958 where tf.nn.conv2d_transpose will crash when output shape is invalid.

This PR adds a warpper ShapeFromFormatWithStatus (previously ShapeFromFormat) so that it is possible to return status.

Note the change can be applied to other places to address similar crashs. Will create follow up PRs to cover other places once this PR is merged.

This PR fixes #57958.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: tensorflow/core/util/tensor_format.h [hunk 1]
```diff
@@ -574,9 +583,17 @@ inline TensorShape ShapeFromFilterTensorFormat(FilterTensorFormat format,
...
+                                         int64_t W, int64_t C, TensorShape *shape) {
+  return ShapeFromFormatWithStatus(format, N, {H, W}, C, shape);
+}
+
 inline TensorShape ShapeFromFormat(TensorFormat format, int64_t N, int64_t H,
                                    int64_t W, int64_t C) {
-  return ShapeFromFormat(format, N, {H, W}, C);
+  TensorShape shape;
+  Status status = ShapeFromFormatWithStatus(format, N, H, W, C, &shape);
+  CHECK(status.ok());
```
Comment (cantonios) [inline tensorflow/core/util/tensor_format.h:595]: We want to avoid these kinds of `CHECK`s in general.  Ideally we would eliminate all uses of `ShapeFromFormat`, instead using your new `Status` version..  There doesn't seem to be _too_ many usages in TensorFlow, but I'm not sure how large of a change it would be to eliminate this entirely.  Can you investigate?

**Comment by yongtang** [comment]
Thanks @cantonios  for the help! I went over all places within source code and now all unsafe `ShapeFromFormat` have been replaced with `ShapeFromFormatWithStatus`. Can you take a look and see if this is good enough?

**Comment by yongtang** [comment]
@cantonios @mihaimaruseac @penpornk wondering if there is any update on this PR?

**Review by cantonios — APPROVED** [review]
Thanks for updating these call sites.

Can the original `ShapeWithFormat` be removed now, or are there still other users?

**Comment by yongtang** [comment]
@cantonios I did a search and believe there is no uses (other than the definition itself) within public tensorflow code base. However, I am not sure if there is any internal code inside google that is still using `ShapeFromFormat`, it will be a little harder to debug if internal tests are failing.

**Comment by cantonios** [comment]
> I did a search and believe there is no uses (other than the definition itself) within public tensorflow code base. However, I am not sure if there is any internal code inside google that is still using `ShapeFromFormat`, it will be a little harder to debug if internal tests are failing.

Let's try to remove it then.  If there are any internal failures, I can update those on my end.

File: tensorflow/core/util/tensor_format.h (hunk 1 above)
Comment (cantonios) [reply tensorflow/core/util/tensor_format.h:595]: Let's remove this, and see what the damage is.

File: tensorflow/core/util/tensor_format.h [hunk 2]
```diff
@@ -546,7 +546,16 @@ inline TensorShape ShapeFromFormat(TensorFormat format, int64_t N,
     dim_sizes[GetTensorInnerFeatureDimIndex(dims, format)] = 4;
   }
   dim_sizes[feature_index] = C;
-  return TensorShape(dim_sizes);
+  return TensorShapeUtils::MakeShape(dim_sizes, shape);
+}
+
+inline TensorShape ShapeFromFormat(TensorFormat format, int64_t N,
```
Comment (cantonios) [inline tensorflow/core/util/tensor_format.h:552]: Were these ones replaced as well?

**Review by cantonios — CHANGES_REQUESTED** [review]

**Comment by yongtang** [comment]
@cantonios Thanks for the help! I have removed the remaining instances of `ShapeFromFormat`. Would you mind to take a look and see if this works?

**Review by cantonios — APPROVED** [review]

**Comment by gbaned** [comment]
@yongtang Can you please resolve conflicts? Thank you!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by yongtang** [comment]
@cantonios @gbaned @mihaimaruseac I have rebased the PR and resolved the conflict. Can you take a look and give it a try?

It will be good if this PR can be merged sooner, as the merge conflicts happens very frequently recently (due to the number of files touched).

Thanks a lot and appreciate all the help.

**Review by cantonios — APPROVED** [review]

**Comment by gbaned** [comment]
@yongtang Can you please resolve conflicts? Thank you!

**Review by cantonios — APPROVED** [review]

**Review by cantonios — APPROVED** [review]
