### PR TITLE
Fix Checkfail in MatrixDiagV3

### LINKED ISSUE #62984: C++ API `MatrixDiagV3` aborts with tensor type of `k`
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.17

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 22.04 LTS

### Mobile device

_No response_

### Python version

3.11.7

### Bazel version

6.5.0

### GCC/compiler version

clang 16

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current behavior?

C++ API `MatrixDiagV3` aborts with tensor type of `k`.
Usually `k` would be given as an array of integers. But it can also accept a tensor, and it can lead to crash.
Suspected code location is [here](https://github.com/tensorflow/tensorflow/blob/e193d8ea7776ef5c6f5d769b6fb9c070213e737a/tensorflow/core/kernels/linalg/matrix_diag_op.cc#L241),
But I have no idea why it is not triggered when it runs with an integer array `k`.

### Standalone code to reproduce the issue
Note: You may have to run it several times to see crash.

```C++
#include "tensorflow/cc/framework/scope.h"
#include "tensorflow/core/graph/graph.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/cc/ops/array_ops.h"
#include "tensorflow/cc/ops/standard_ops.h"

using namespace tensorflow;

int main() {
  SessionOptions options;
  ConfigProto & config = options.config;
  config.set_inter_op_parallelism_threads(1);
  config.set_intra_op_parallelism_threads(1);
  config.set_use_per_session_threads(false);
  std::unique_ptr<tensorflow::Session>
    session(tensorflow::NewSession(options));
  Scope scope = Scope::NewRootScope();

  Input k = ops::RandomUniformInt(scope, {2}, 0, (1 << 15) - 1);
  auto target = ops::MatrixDiagV3(scope.WithOpName("target"), {0.0f}, k, 1, 1, 0.0f);

  GraphDef graph_def;
  TF_CHECK_OK(scope.ToGraphDef(&graph_def));

  Status status = session->Create(graph_def);
  if (!status.ok()) {
    LOG(WARNING) << "Could not create session: " << status.message();
  }

  std::vector<Tensor> outputs;
  status = session->Run({}, {"target"}, {"target"}, &outputs);
  if (!status.ok()) {
    LOG(WARNING) << "Could not run session: " << status.message();
  }

  return 0;
}
```

### Relevant log output

```shell
2024-02-18 02:54:37.171134: F tensorflow/core/framework/tensor_shape.cc:356] Check failed: d >= 0 (0 vs. -1)
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by SuryanarayanaY**
The Op raw_ops.MatrixDiagV3 terminates due to checkfail when the input `diagonal` is of `rank=1` and `k[0] != k[1]`.

This happens at this line below which is trying to access `diagonal_shape.dim_size(-1)` when rank=1 . Currently API will not work with Rank=1 and k[0] != k[1] due to this check fail.

https://github.com/tensorflow/tensorflow/blob/e193d8ea7776ef5c6f5d769b6fb9c070213e737a/tensorflow/core/kernels/linalg/matrix_diag_op.cc#L241

Proposed a fix for same.

Fixes #62984 .

### CODE REVIEW

File: tensorflow/core/kernels/linalg/matrix_diag_op.cc [hunk 1]
```diff
@@ -236,13 +236,21 @@ class MatrixDiagOp : public OpKernel {
         errors::InvalidArgument(
             "lower_diag_index must not be larger than upper_diag_index: ",
             lower_diag_index, " > ", upper_diag_index));
-    OP_REQUIRES(context,
-                lower_diag_index == upper_diag_index ||
-                    diagonal_shape.dim_size(diag_rank - 2) == num_diags,
```
Comment (cantonios) [inline tensorflow/core/kernels/linalg/matrix_diag_op.cc:241]: `max(diag_rank - 2, 0)`?

Comment (SuryanarayanaY) [reply tensorflow/core/kernels/linalg/matrix_diag_op.cc:241]: > `max(diag_rank - 2, 0)`?

Oh.You mean instead of validating for diag_rank==1 and diag_rank>1 separately, we can do it in simple way by taking  `max(diag_rank - 2, 0)`. It seems better and avoid redundancy. 

May be this check works now. I am assuming `max` should be from `std` ?

```
OP_REQUIRES(context,
    lower_diag_index == upper_diag_index ||
        diagonal_shape.dim_size(std::max(diag_rank - 2, 0)) == num_diags,
    errors::InvalidArgument(
        "The number of diagonals provided in the input does not "
        "match the lower_diag_index and upper_diag_index range."));
```

Comment (cantonios) [reply tensorflow/core/kernels/linalg/matrix_diag_op.cc:241]: yes

**Comment by SuryanarayanaY** [comment]
Done the suggested changes.

**Review by cantonios — APPROVED** [review]

**Review by cantonios — APPROVED** [review]
