### PR TITLE
[ROCM] Move ROCm builds to 5.3; Fix build failures

### LINKED ISSUE #58348: Failed to build TF with ROCm >=5.2
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF 2.10

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04.4 LTS

### Mobile device

_No response_

### Python version

3.8.10

### Bazel version

5.3.0

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

_No response_

### GPU model and memory

AMD MI210

### Current Behaviour?

When I build TF from source with ROCm 5.3.0, the error happens:

```
ERROR: An error occurred during the fetch of repository 'local_config_rocm':
   Traceback (most recent call last):
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/gpus/rocm_configure.bzl", line 869, column 38, in _rocm_autoconf_impl
		_create_local_rocm_repository(repository_ctx)
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/gpus/rocm_configure.bzl", line 547, column 35, in _create_local_rocm_repository
		rocm_config = _get_rocm_config(repository_ctx, bash_bin, find_rocm_config_script)
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/gpus/rocm_configure.bzl", line 395, column 30, in _get_rocm_config
		config = find_rocm_config(repository_ctx, find_rocm_config_script)
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/gpus/rocm_configure.bzl", line 373, column 41, in find_rocm_config
		exec_result = _exec_find_rocm_config(repository_ctx, script_path)
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/gpus/rocm_configure.bzl", line 369, column 19, in _exec_find_rocm_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed

A bug happened!ERROR: #define "ROCRAND_VERSION" is either
not present in file /global/software/rocm/rocm-5.3.0/rocrand/include/rocrand_version.h OR
its value is not an integer literal
```

`/global/software/rocm/rocm-5.3.0/rocrand/include/rocrand_version.h` gives:

```
/*
    Copyright (c) 2022 Advanced Micro Devices, Inc. All rights reserved.
*/

#ifndef ROCM_WRAPPER_ROCRAND_VERSION_H
#define ROCM_WRAPPER_ROCRAND_VERSION_H

#if defined(ROCM_NO_WRAPPER_HEADER_WARNING) || defined(ROCM_WRAPPER_GAVE_WARNING)
/* include file */
#include "../../include/rocrand/rocrand_version.h"
#else
/* give warning */
#if defined(_MSC_VER)
#pragma message(": warning:This file is deprecated. Use the header file from /opt/rocm-5.3.0/include/rocrand/rocrand_version.h by using #include <rocrand/rocrand_version.h>")
#elif defined(__GNUC__)
#pragma message(": warning : This file is deprecated. Use the header file from /opt/rocm-5.3.0/include/rocrand/rocrand_version.h by using #include <rocrand/rocrand_version.h>")
#endif
/* include file */
#define ROCM_WRAPPER_GAVE_WARNING
#include "../../include/rocrand/rocrand_version.h"
#undef ROCM_WRAPPER_GAVE_WARNING
#endif /* defined(ROCM_NO_WRAPPER_HEADER_WARNING) || defined(ROCM_WRAPPER_GAVE_WARNING) */

#endif /* ROCM_WRAPPER_ROCRAND_VERSION_H */
```

So in ROCm >=5.2, the version should be read from `include/rocrand/rocrand_version.h` instead of `rocrand/include/rocrand_version.h`. It looks that TensorFlow does not handle this thing.

Note that in ROCm 5.1, `rocrand/include/rocrand_version.h` does have version information.

### Standalone code to reproduce the issue

```shell
Build from source against ROCm >=5.2
```

### Relevant log output

_No response_</details>

### PR DESCRIPTION
**Pull request by jayfurmanek**
This PR includes a number of updates and fixes for the ROCm build. I plan on splitting this into separate PRs, but at the moment all of this is needed to get the CI working, so I'll use this PR as reference and open separate PRs once this one shows a clean CI run.

- ROCm ~~5.2~~ 5.3 support
- Update Dockerfile.rocm to Ubuntu20.04 including some updates related to the newer compiler
- Some build fixes related to hipsparse and hipsolver/rocsolver
~~Unit test fixes for a handful of tests~~
~~ROCM registration for the custom ops for GPU assert and GenericTfCallback~~

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@cheshire @gbaned Do you have a preference on how/if this should be split up?  thx!

File: tensorflow/compiler/tf2xla/kernels/gpu_tf_kernel_custom_call.cc [hunk 1]
```diff
@@ -513,8 +513,13 @@ void GenericTfCallback(void* stream_handle, void** buffers, const char* opaque,
   }
 }
 
+#if GOOGLE_CUDA
 XLA_REGISTER_CUSTOM_CALL_TARGET_WITH_SYM(kTfCallbackCustomCall,
                                          GenericTfCallback, "CUDA");
```
Comment (cheshire) [inline tensorflow/compiler/tf2xla/kernels/gpu_tf_kernel_custom_call.cc:518]: Maybe we could unify it with a single variable defined in a common header?

File: tensorflow/compiler/xla/service/gpu/tests/gpu_atomic_test.cc [hunk 2]
```diff
@@ -104,7 +104,7 @@ TEST_F(GpuAtomicTest, TestAddAtomicF32) {
 )";
 
   CompileAndVerifyIr(hlo_string, is_built_with_rocm_ ? R"(
-CHECK: atomicrmw fadd float addrspace{{.*}}, float {{.*}} seq_cst, align 4
+CHECK: atomicrmw fadd ptr addrspace(1) %[[ADDR:.*]], float %[[VALUE:.*]] syncscope("agent") seq_cst
```
Comment (cheshire) [inline tensorflow/compiler/xla/service/gpu/tests/gpu_atomic_test.cc:107]: Would that fail in NVIDIA?

File: tensorflow/core/kernels/gpu_prim.h [hunk 3]
```diff
@@ -80,11 +80,29 @@ struct NumericTraits<tensorflow::bfloat16>
 }  // namespace cub
 #elif TENSORFLOW_USE_ROCM
 #include "rocm/include/hipcub/hipcub.hpp"
+#include "rocm/rocm_config.h"
 namespace gpuprim = ::hipcub;
 
 // Required for sorting Eigen::half and bfloat16.
 namespace rocprim {
 namespace detail {
+#if (TF_ROCM_VERSION >= 50200)
```
Comment (cheshire) [inline tensorflow/core/kernels/gpu_prim.h:89]: Can we separate TF fixes out?

**Review by cheshire — CHANGES_REQUESTED** [review]
Generally, let's separate XLA/TF2XLA/infra/TF.

**Comment by jayfurmanek** [comment]
Split off PRs:
https://github.com/tensorflow/tensorflow/pull/56779
https://github.com/tensorflow/tensorflow/pull/56780
https://github.com/tensorflow/tensorflow/pull/56781

File: tensorflow/core/kernels/gpu_prim.h (hunk 3 above)
Comment (rahulbatra85) [reply tensorflow/core/kernels/gpu_prim.h:89]: yes, split it into multiple PRs. Please see the list below.

**Comment by rahulbatra85** [comment]
@r4nt @penpornk @cheshire  Can you please review this? 
I have addressed the comment to split this PR into separate ones and all the checks so far are passing. This PR now just addresses ROCm build issues which are needed to get the AMD ROCm- Community CI build working again
Thanks!

**Comment by rahulbatra85** [comment]
> Split off PRs: #56779 #56780 #56781

@jayfurmanek  Can you please update this list to

https://github.com/tensorflow/tensorflow/pull/56793
https://github.com/tensorflow/tensorflow/pull/56780
https://github.com/tensorflow/tensorflow/pull/56788

**Comment by rahulbatra85** [comment]
@r4nt @penpornk @cheshire  Can you please review this soon? This fixes the AMD ROCm - Community CI Build and unblocks other PRs
Thanks!

**Comment by rahulbatra85** [comment]
@r4nt @penpornk @cheshire Hi, can you please provide feedback on this? 
We are trying to get this merged before the TF2.10 cutoff next week. Thanks!

**Review by cheshire — APPROVED** [review]

**Comment by rahulbatra85** [comment]
@r4nt @penpornk @cheshire
Hi, sorry to keep bothering about this PR. Like I said, we are trying to get this merged before the TF2.10 cutoff tomorrow. Can you please approve it once again and let the other CIs run. Thanks!

**Comment by rahulbatra85** [comment]
@r4nt  @penpornk @cheshire
Hi can you please review? 
Thanks!

**Comment by rahulbatra85** [comment]
@r4nt @penpornk @cheshire
Hi, can you please look into this one and get this merged?

Thanks!

**Comment by gbaned** [comment]
> @r4nt @penpornk @cheshire Hi, can you please look into this one and get this merged?
> 
> Thanks!

Hi @rahulbatra85 Sorry for the delay. 
Hello @cheshire  Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hello @r4nt, @cheshire Can you please review this PR ? Thank you!

**Comment by rahulbatra85** [comment]
@r4nt  @cheshire  Please review. Thanks!

**Comment by gbaned** [comment]
Hello @r4nt, @cheshire Can you please review this PR ? Thank you!

**Comment by cheshire** [comment]
This PR changes very many different things, is it possible to split this up?

**Review by cheshire — APPROVED** [review]

**Comment by cheshire** [comment]
@SandSnip3r

**Comment by SandSnip3r** [comment]
I see that the Internal CI build (Py+CPP Test Suite - Ubuntu GPU, Python 3.9) fails. I think you can see the results. The failures are in the same files that you have changed. Have you tried resolving this issue?

**Comment by rahulbatra85** [comment]
> I see that the Internal CI build (Py+CPP Test Suite - Ubuntu GPU, Python 3.9) fails. I think you can see the results. The failures are in the same files that you have changed. Have you tried resolving this issue?

@SandSnip3r  Thanks for the feedback!
Sorry,I thought that CI is failing because not all tests pass which is expected for ROCm platform, but I see there are build errors also. 

One question, this Py+CPP Test Suite - Ubuntu GPU, Python 3.9 is attempting CUDA/Nvidia build/execution. Correct?

**Comment by SandSnip3r** [comment]
@rahulbatra85 it looks like its trying to build all of OSS Tensorflow and run enabled tests. Cuda included.

**Comment by rahulbatra85** [comment]
@SandSnip3r  I pushed a fix for Nvidia/CUDA build failure. Can you please kick off(or is that done automatically?) the next set of CIs for this PR?

**Comment by SandSnip3r** [comment]
@rahulbatra85 sorry about the delay. It looks like all the shared CI state is good. I think that should be enough for you to move forward and split this into separate PRs now.

**Comment by rahulbatra85** [comment]
> @rahulbatra85 sorry about the delay. It looks like all the shared CI state is good. I think that should be enough for you to move forward and split this into separate PRs now.

@SandSnip3r  I have split as much as possible. The rest of the changes need to go together. 

Actually, AMD has now officially released ROCm5.3, so would like to get this ROCm5.2 merged soon. Actually, couple of times it was all ready to merge, but the ask to split it further required a rebase and then CIs started failing again with all the other changes. I hope all the required CIs pass and we can get this merged by early next week.

Thanks!

**Comment by SandSnip3r** [comment]
@rahulbatra85 The description says that this will be split. @cheshire asked if it could be split. I suspect the reason this is taking so long is because its so large. Smaller PRs are substantially easy to get in.

Let me check what internal CI looks like.

**Comment by rahulbatra85** [comment]
Yeah, we already split it into other PRs. It much larger. Actually, most of the code changes are ROCm specific. About half(may be more) the files touched are only for ROCm. In common files, almost all the changes are again ROCm specific.

**Comment by SandSnip3r** [comment]
This is currently pending approval from some Tensorflow reviewers

**Comment by SandSnip3r** [comment]
I am seeing a ton of failures in our internal CI build of Tensorflow as OSS.
They are all errors that rocm headers can't be found. The offending headers are:
rocm/include/hipfft/hipfft.h
rocm/include/hipsparse/hipsparse.h
rocm/include/rccl/rccl.h
rocm/include/rocsolver/rocsolver.h

Do you have any intuition as to what could be wrong?

**Comment by rahulbatra85** [comment]
@SandSnip3r  As Jason mentioned above the headers did move when going from ROCm5.1 to ROCm5.2. He just happens to show the output from ROCm5.3, but they are in same paths for ROCm5.2 as well.

What ROCm version is your internal CI building against? Can you share some more details?

**Comment by SandSnip3r** [comment]
Sorry, I've been looking around and cant find the version number. Is there a specific file in rocm which has this version number inside it?

**Comment by jayfurmanek** [comment]
oh you can check in: $ROCM_PATH/.info/version:

```
cat /opt/rocm-5.3.0/.info/version
5.3.0-63
```

**Comment by rahulbatra85** [comment]
@SandSnip3r  
Hi, any update on this?  Is there anything we can do to get this merged?
Thanks!

**Comment by SandSnip3r** [comment]
@rahulbatra85 our internal CI also needs to be updated to use 5.2. Working on that right now.

**Comment by rahulbatra85** [comment]
@SandSnip3r  Looks like all checks are passing now!
Can we please merge this?

**Comment by SandSnip3r** [comment]
All tests are not passing. Still working on this. Sorry it's taking so long.

**Comment by SandSnip3r** [comment]
Unfortunately, this item is taking a back seat to some other higher priority issues. Also, I am having trouble getting permissions to update our internal rocm testing version. I am trying to pass this off to someone who has permissions and time to help. Sorry about the delay.

**Comment by rahulbatra85** [comment]
> Unfortunately, this item is taking a back seat to some other higher priority issues. Also, I am having trouble getting permissions to update our internal rocm testing version. I am trying to pass this off to someone who has permissions and time to help. Sorry about the delay.

Ok, thanks for the update!

**Comment by njzjz** [comment]
I got a link error when using this patch:

```
ERROR: /global/home/jzzeng/packages/tensorflow/tensorflow-upstream-fix-upstream-rocm/tensorflow/BUILD:1177:21: Linking tensorflow/libtensorflow_cc.so.2.11.0 failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /global/home/jzzeng/packages/bazelcache/_bazel_jzzeng/9eb7c223209da752c6ae3e91633931e1/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/global/software/rocm/rocm-5.3.0/lib:/global/software/rocm/rocm-5.3.0/lib64:/global/software/rocm/rocm-5.3.0/hip/lib:/global/software/rocm/rocm-5.3.0/llvm/lib:/global/software/rocm/rocm-5.3.0/opencl/lib:/global/software/rocm/rocm-5.3.0/hcc/lib:/global/software/rocm/rocm-5.3.0/opencl/lib/x86_64 \
    PATH=/global/home/jzzeng/.cache/bazelisk/downloads/bazelbuild/bazel-5.3.0-linux-x86_64/bin:/usr/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/global/home/jzzeng/anaconda3/bin/python \
    PYTHON_LIB_PATH=/global/home/jzzeng/anaconda3/lib/python3.9/site-packages \
    ROCM_PATH=/global/software/rocm/rocm-5.3.0 \
    TF2_BEHAVIOR=1 \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-opt/bin/tensorflow/libtensorflow_cc.so.2.11.0-2.params)
# Configuration: 9e3351ef38ce425e2c9e0fc21db336cdf284c59ddf32b6bdcedb947b33c0b340
# Execution platform: @local_execution_config_platform//:platform
bazel-out/k8-opt/bin/tensorflow/core/profiler/backends/gpu/_objs/rocm_tracer/rocm_tracer.pic.o:rocm_tracer.cc:function tensorflow::profiler::RocmTracer::ActivityCallbackHandler(char const*, char const*) [clone .part.0]: error: undefined reference to 'roctracer_next_record'
bazel-out/k8-opt/bin/tensorflow/core/profiler/backends/gpu/_objs/rocm_tracer/rocm_tracer.pic.o:rocm_tracer.cc:function tensorflow::profiler::RocmActivityCallbackImpl::operator()(char const*, char const*): error: undefined reference to 'roctracer_next_record'
collect2: error: ld returned 1 exit status
```

**Comment by jayfurmanek** [comment]
yeah - that's a ROCM 5.3 specific change. We have a commit for that as well:

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/25cb2fc873086069f0b93e4b356e62ebd00289ca

I think that's the only 5.3 specific one. Shall we refresh this PR to be 5.3?

**Comment by rahulbatra85** [comment]
@njzjz Thanks for looking into this PR. We first pushed this PR back in July, but since then ROCm5.3 have been released and we have few changes for that too. I think at this point it's best is to include ROCm5.3 changes as well. They are anyways much less than ROCm5.2 changes

I will push an updated PR soon

**Comment by rahulbatra85** [comment]
@njzjz  Can you please start the next set of CIs against this PR?
Thanks!

**Comment by njzjz** [comment]
Hi @rahulbatra85, now it works for me.

```
INFO: Elapsed time: 1443.239s, Critical Path: 373.18s
INFO: 16816 processes: 1676 internal, 15140 local.
INFO: Build completed successfully, 16816 total actions
INFO: Build completed successfully, 16816 total actions
```

File: tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh [hunk 4]
```diff
@@ -27,7 +27,7 @@ echo "Bazel will use ${N_BUILD_JOBS} concurrent build job(s) and ${N_TEST_JOBS}
 echo ""
 
 # First positional argument (if any) specifies the ROCM_INSTALL_DIR
-ROCM_INSTALL_DIR=/opt/rocm-5.1.0
+ROCM_INSTALL_DIR=/opt/rocm-5.2.0
```
Comment (akuegel) [inline tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh:30]: Should this be also changed to rocm-5.3.0?

Comment (rahulbatra85) [reply tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh]: @akuegel Yes, just pushed an update.

Thanks!

**Review by akuegel — APPROVED** [review]

**Comment by rahulbatra85** [comment]
> @akuegel Hi, thanks for your help on this PR. Is it now good to merge?

ah never mind, looks like a commit from few minutes ago broke this PR. I will rebase

**Review by akuegel — APPROVED** [review]

File: third_party/gpus/rocm_configure.bzl [hunk 5]
```diff
@@ -561,69 +573,14 @@ def _create_local_rocm_repository(repository_ctx):
             out_dir = "rocm/include",
             exceptions = ["gtest", "gmock"],
         ),
-        make_copy_dir_rule(
```
Comment (akuegel) [inline third_party/gpus/rocm_configure.bzl:564]: In our internal ROCM build, we now get failures which seem to point to removing these rules.
We still run with ROCM 5.0, maybe these rules are still needed for that system?

File: third_party/gpus/find_rocm_config.py [hunk 6]
```diff
@@ -69,36 +69,28 @@ def _get_header_version(path, name):
...
-      version_string = f.read().strip()
-      version_numbers = version_string.split(".")
-    major = int(version_numbers[0])
-    minor = int(version_numbers[1])
-    patch = int(version_numbers[2].split("-")[0])
-    return major, minor, patch
+  def rocm_version_numbers(path):
+    possible_version_files = [
+        "include/rocm-core/rocm_version.h",  # ROCm 5.2
+        "include/rocm_version.h",  # ROCm 5.1 and prior
```
Comment (akuegel) [inline third_party/gpus/find_rocm_config.py:75]: If I read the change correctly, actually this should be ROCm 5.0 and 5.1
Because it seems pre ROCm 5.0 there was a different version file, which is now not supported anymore?

**Review by akuegel — CHANGES_REQUESTED** [review]
Unfortunately we have run into issues with our internal ROCM build. Can you please check whether you unintentionally removed some backward compatibility stuff?
I can also try to update our internal ROCM build to 5.1, maybe then the change would work as-is? Or do we need to switch to 5.3 at the same time when this PR is merged?

File: third_party/gpus/rocm_configure.bzl (hunk 5 above)
Comment (rahulbatra85) [reply third_party/gpus/rocm_configure.bzl:564]: Some of the backward compatibility for ROCm5.0 was missing from this PR. Sorry for the troubles. Can you try again?

File: third_party/gpus/find_rocm_config.py (hunk 6 above)
Comment (rahulbatra85) [reply third_party/gpus/find_rocm_config.py:75]: The file is the same, but some paths for headers files changed when going from ROCm 5.0 to 5.1 and then 5.1 to 5.2. If you plan on switching your internal CI, then it's best to move to ROCm5.2 or 5.3. Try to avoid ROCm5.1 with Tensorflow

File: third_party/gpus/rocm_configure.bzl (hunk 5 above)
Comment (akuegel) [reply third_party/gpus/rocm_configure.bzl:564]: Thanks, I will give it another try :) It might take some time though because I am out of office next week, and not sure whether it will go through all approvals today. But maybe someone else will make sure this gets merged while I am away.

File: third_party/gpus/find_rocm_config.py (hunk 6 above)
Comment (akuegel) [reply third_party/gpus/find_rocm_config.py:75]: Thanks for confirming, I also thought it would be best to directly move to 5.3. And I guess I can do that after this PR has been merged.

**Review by akuegel — APPROVED** [review]

File: third_party/gpus/rocm_configure.bzl (hunk 5 above)
Comment (akuegel) [reply third_party/gpus/rocm_configure.bzl:564]: And it is merged :) Thanks for making it backwards compatible with ROCM 5.0, this made it much easier. Now I can move our internal build to ROCM 5.3 without having to do it at the same time.

File: third_party/gpus/find_rocm_config.py (hunk 6 above)
Comment (rahulbatra85) [reply third_party/gpus/find_rocm_config.py:75]: @akuegel  Finally, we have this merged! Thanks for you all your help here!

Comment (akuegel) [reply third_party/gpus/find_rocm_config.py:75]: I tried moving our build to ROCM 5.3, but then ran into this error:

```
@local_config_rocm//rocm:rocblas-hsaco: illegal output file name 'find: 'rocm/lib/rocblas/lib/library': No such file or directory' in rule @local_config_rocm//rocm:rocblas-hsaco: invalid target name 'find: 'rocm/lib/rocblas/lib/library': No such file or directory': target names may not contain ':'
```

This seems to indicate that it failed to find this directory when running the make_copy_dir rule in rocm_configure.bzl, but I am not quite sure. Maybe you have seen a similar error before and know what the problem is?
I also noticed that you deleted many make_copy_dir calls in your PR, but not this one. Why is this still needed, but not the others?

Comment (akuegel) [reply third_party/gpus/find_rocm_config.py:75]: Thank you for your help, deleting that make_copy_dir_rule seems to have fixed the issue :)

Comment (akuegel) [reply third_party/gpus/find_rocm_config.py:75]: @jayfurmanek @rahulbatra85

I noticed by now that by mistake I didn't roll forward the attempt to move our Kokoro to ROCM 5.3. I did this again today, and ran into a different error now:

```
this rule is missing dependency declarations for the following files included by 'tensorflow/compiler/xla/stream_executor/rocm/[rocm_helpers.cu.cc](https://www.google.com/url?q=http://rocm_helpers.cu.cc&sa=D)':
  '/opt/rocm/hip/include/hip/hip_version.h'
  '/opt/rocm/hip/include/hip/hip_runtime.h'
  '/opt/rocm/hip/include/hip/hip_common.h'
  '/opt/rocm/hip/include/hip/amd_detail/amd_hip_runtime.h'
  '/opt/rocm/hip/include/hip/amd_detail/amd_hip_common.h'
  '/opt/rocm/hip/include/hip/hip_runtime_api.h'
  '/opt/rocm/hip/include/hip/amd_detail/host_defines.h'
  '/opt/rocm/hip/include/hip/driver_types.h'
  '/opt/rocm/hip/include/hip/texture_types.h'
  '/opt/rocm/hip/include/hip/channel_descriptor.h'
  '/opt/rocm/hip/include/hip/amd_detail/amd_channel_descriptor.h'
  '/opt/rocm/hip/include/hip/amd_detail/amd_hip_vector_types.h'
  '/opt/rocm/hip/include/hip/surface_types.h'
  '/opt/rocm/hip/include/hip/amd_detail/amd_hip_runtime_pt_api.h'
  '/opt/rocm/hip/include/hip/amd_detail/hip_ldg.h'
  '/opt/rocm/hip/include/hip/amd_detail/amd_hip_atomic.h'
  '/opt/rocm/hip/include/hip/hip_vector_types.h'
  '/opt/rocm/hip/include/hip/amd_detail/device_library_decls.h'
  '/opt/rocm/hip/include/hip/amd_detail/llvm_intrinsics.h'
  '/opt/rocm/hip/include/hip/amd_detail/amd_device_functions.h'
  '/opt/rocm/hip/include/hip/amd_detail/amd_surface_functions.h'
  '/opt/rocm/hip/include/hip/amd_detail/ockl_image.h'
  '/opt/rocm/hip/include/hip/amd_detail/texture_fetch_functions.h'
  '/opt/rocm/hip/include/hip/hip_texture_types.h'
  '/opt/rocm/hip/include/hip/amd_detail/texture_indirect_functions.h'
  '/opt/rocm/hip/include/hip/amd_detail/amd_math_functions.h'
  '/opt/rocm/hip/include/hip/library_types.h'
```

Any idea what could be the reason?
It seems previously we have added hip/include to inc_dirs:

```
inc_dirs.append(rocm_config.rocm_toolkit_path + "/hip/include")
```

Now we add several other directories instead. I wonder whether we need to adjust this rule somehow?

```
make_copy_dir_rule(
            repository_ctx,
            name = "rocm-include",
            src_dir = rocm_toolkit_path + "/include",
            out_dir = "rocm/include",
            exceptions = ["gtest", "gmock"],
        ),
```

Comment (njzjz) [reply third_party/gpus/find_rocm_config.py:75]: > Any idea what could be the reason?

I guess there are symbolic links here. See also #35122 and #37006. If so, the resolution is to use `realpath`.

Comment (akuegel) [reply third_party/gpus/find_rocm_config.py:75]: I tried with realpath, but that did not help. But what seems to help is to still add inc_dirs.append(rocm_config.rocm_toolkit_path + "/hip/include") even for the new ROCM version (in addition to the other directories).
Not sure whether that would break the AMD community build though.

Comment (akuegel) [reply third_party/gpus/find_rocm_config.py:75]: FYI, now with https://github.com/tensorflow/tensorflow/commit/d21b5574c580ad8d58850d142fbf9984403e22c0 our Kokoro also uses ROCM 5.3
The title of that commit is wrong, forgot to update it when I rolled forward.
