### PR TITLE
[TFL] Optimize ArgMinMax for float when axis=dims-1.

### LINKED ISSUE #47555: Optimize TFLite argmin/argmax
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Pixel 3a Android 11
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): nightly

**Standalone code to reproduce the issue** 

```python
model = tf.keras.Sequential([
  tf.keras.Input(shape=(512,), batch_size=1, dtype=tf.int32),
  tf.keras.layers.Embedding(1000, 128),
  tf.keras.layers.LSTM(64, return_sequences=True),
  tf.keras.layers.Dense(5000),
  tf.keras.layers.Lambda(lambda x: tf.math.argmax(x, axis=-1)),
])
```

Given a simple sequence model with 5000 output labels, ArgMax takes as much time as computation-intense ops like FullyConnected and LSTM. Here is my benchmark on pixel 3a

```
                     [Node type]          [count]         [avg ms]          [avg %]         [cdf %]       [mem KB]      [times called]
        UNIDIRECTIONAL_SEQUENCE_LSTM            1           27.552          33.447%         33.447%          0.000              1
                 FULLY_CONNECTED                1           27.474          33.353%         66.800%          0.000              1
                         ARG_MAX                1           24.868          30.189%         96.989%          0.000              1
                         RESHAPE                1            2.343           2.844%         99.834%          0.000              1
                          GATHER                1            0.137           0.166%        100.000%          0.000              1
```

Looks like compiler is not smart enough to vectorize naive-for-loop argmin-max reduction. In order to improve the performance, we should at least specialize the implementation when `axis=dims-1`, that is, `inner_size=1` in the following code snippet. If the request is valid, I can try to handcraft some Neon intrinsics to see if the performance is better.

https://github.com/tensorflow/tensorflow/blob/ea49c350b3b812bd852ae8456d2c8cc29aff6c95/tensorflow/lite/kernels/internal/reference/arg_min_max.h#L49-L63

### PR DESCRIPTION
**Pull request by WindQAQ**
Fixes #47555.

Benchmark on argmax of 1-D float32 tensor on Pixel 3a android 11:

| Size   | Reference (min/max/avg microsecs) | Optimized (min/max/avg microsecs) |
| ------ | --------------------------------- | --------------------------------- |
| 10     | 0/63/0.260737                     | 0/49/0.216432                     |
| 100    | 1/101/1.17919                     | 0/77/0.271518                     |
| 1000   | 9/98/9.80665                      | 0/65/1.07653                      |
| 10000  | 95/190/96.2557                    | 8/110/9.63559                     |
| 100000 | 952/1102/967.445                  | 88/215/94.8766                    |

/cc @abattery for visibility.

### CODE REVIEW

**Comment by abattery** [comment]
@renjie-liu could you review this performance improvement proposal?

File: tensorflow/lite/kernels/internal/optimized/optimized_ops.h [hunk 1]
```diff
@@ -7730,6 +7728,217 @@ inline void BroadcastPReluDispatch(
...
 
+// Returns the index with minimum value within `input_data`.
+// If there is a tie, returns the smaller index.
+template <typename T>
+inline int ArgMinVector(const T* input_data, int n) {
+  T min_value = input_data[0];
+  int min_index = 0;
+  for (int i = 1; i < n; ++i) {
+    const T curr_value = input_data[i];
+    if (curr_value < min_value) {
```
Comment (abattery) [inline tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7739]: can we make additional improvement by turning this into Neon instructions?

File: tensorflow/lite/kernels/internal/optimized/optimized_ops.h [hunk 2]
```diff
@@ -7730,6 +7728,217 @@ inline void BroadcastPReluDispatch(
...
+  float max_value = input_data[0];
+  int32_t i = 1;
+  if (size >= 4) {
+    float32x4_t max_value_f32x4 = vld1q_f32(input_data);
+    const int32_t index_init[4] = {0, 1, 2, 3};
+    int32x4_t max_index_s32x4 = vld1q_s32(index_init);
+    int32x4_t index_s32x4 = max_index_s32x4;
+    int32x4_t inc = vdupq_n_s32(4);
+    for (i = 4; i < size - 3; i += 4) {
+      // Increase indices by 4.
```
Comment (abattery) [inline tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7830]: How the size of loading values at once can affect the performance. Could you experiment loading 8 indices and 16 indices at once? since the parallel loading/storing invocations can hide the calculation times.

File: tensorflow/lite/kernels/internal/optimized/optimized_ops.h [hunk 3]
```diff
@@ -7730,6 +7728,217 @@ inline void BroadcastPReluDispatch(
...
+                              T2* output_data) {
+  TFLITE_DCHECK_EQ(input_shape.DimensionsCount(), 2);
+  TFLITE_DCHECK_EQ(output_shape.DimensionsCount(), 1);
+  TFLITE_DCHECK_EQ(input_shape.Dims(0), output_shape.Dims(0));
+
+  int outer_size = input_shape.Dims(0);
+  int axis_size = input_shape.Dims(1);
+  for (int outer = 0; outer < outer_size; ++outer) {
+    if (is_arg_max) {
+      output_data[outer] = static_cast<T2>(
```
Comment (abattery) [inline tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7888]: can we have two for-loop to remove the unnecessary if condition every time?

**Comment by abattery** [comment]
@WindQAQ do you think the current set of test cases for arg min max covers the cases for float when axis=dim - 1? If not, please add some test cases.

File: tensorflow/lite/kernels/internal/optimized/optimized_ops.h (hunk 2 above)
Comment (WindQAQ) [reply tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7830]: Sure, I'll do some experiments.

File: tensorflow/lite/kernels/internal/optimized/optimized_ops.h (hunk 3 above)
Comment (WindQAQ) [reply tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7888]: `is_arg_max` here is a template argument. Compiler should be able to avoid the condition?

**Comment by WindQAQ** [comment]
> @WindQAQ do you think the current set of test cases for arg min max covers the cases for float when axis=dim - 1? If not, please add some test cases.

There is one test, but I can add more. BTW, do you think it's better to put `ArgMaxVector` to `tensor_utils`? Though there is no other uses other than in `ArgMinMax` I think.

File: tensorflow/lite/kernels/internal/optimized/optimized_ops.h (hunk 2 above)
Comment (WindQAQ) [reply tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7830]: Unfortunately, unrolling the loop does not gain the performance. I think it's because this is a reduction task, there are many true dependencies on registers (for example, `max_value_f32x4`), which make instructions hard to interleave

**Comment by abattery** [comment]
> do you think it's better to put ArgMaxVector to tensor_utils?

I think we don't need to move them to the tensor_utils as you said.

**Comment by abattery** [comment]
Generally, LGTM. To make sure the validity of the implementation, could you add some test cases under lite/op_tests for cases when axis = dims - 1?

**Review by abattery — APPROVED** [review]

File: tensorflow/lite/kernels/internal/optimized/optimized_ops.h [hunk 4]
```diff
@@ -7730,6 +7728,217 @@ inline void BroadcastPReluDispatch(
...
+#ifdef USE_NEON
+template <>
+inline int ArgMinVector(const float* input_data, int size) {
+  int32_t min_index = 0;
+  float min_value = input_data[0];
+  int32_t i = 1;
+  if (size >= 4) {
+    float32x4_t min_value_f32x4 = vld1q_f32(input_data);
+    const int32_t index_init[4] = {0, 1, 2, 3};
+    int32x4_t min_index_s32x4 = vld1q_s32(index_init);
```
[the remark this answers is not in the document]
Comment (WindQAQ) [reply tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7772]: It does not work unfornately. Looks like compiler used in build tools does not support this yet.

**Review by abattery — APPROVED** [review]

**Comment by abattery** [comment]
Resolve the conflict problem in the internal/optimized/legacy_optimized_ops.h. There are two ArgMinMax ops.

File: tensorflow/lite/kernels/internal/optimized/optimized_ops.h [hunk 5]
```diff
@@ -7730,6 +7728,219 @@ inline void BroadcastPReluDispatch(
...
+    if (curr_value > max_value) {
+      max_value = curr_value;
+      max_index = i;
+    }
+  }
+  return max_index;
+}
+
+template <>
+inline int ArgMinVector(const float* input_data, int size) {
```
Comment (abattery) [inline tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7764]: Choose the only one keyword from among the `n` or `size` keywords for the template functions consistently.

Comment (abattery) [reply tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7764]: My recommendation is using the size keyword.

**Comment by WindQAQ** [comment]
> Resolve the conflict problem in the internal/optimized/legacy_optimized_ops.h. There are two ArgMinMax declarations from the headers for reference ops and optimized ops.

Should we modify the input arguments to legacy_reference_ops as well? It takes a cmp functor but this PR adds a boolean argument in optimized version.

**Comment by WindQAQ** [comment]
Legacy ops cannot use optimized version because they accepts a function as argument. I add a function that takes bool as argument, which is the same as the one in reference_ops. Let me know if it's correct. Also port ArgMax for backward compatibility. Reference ops have ArgMax function that is separate from ArgMinMax.

**Review by abattery — APPROVED** [review]

**Comment by abattery** [comment]
tensorflow/lite/testing:zip_test_arg_min_max is not buildable.

**Comment by WindQAQ** [comment]
> tensorflow/lite/testing:zip_test_arg_min_max is not buildable.

Do you have error msg? Thanks!

**Comment by abattery** [comment]
tensorflow/lite/testing/generate_examples_report.py, in make_report_table
    fp.write("  <td>%s</td>\n" % html.escape(repr(params[p]), quote=True))
KeyError: 'axis'

**Comment by WindQAQ** [comment]
Let's see if it works 😃

**Review by abattery — APPROVED** [review]

**Review by walli55 — APPROVED** [review]

**Comment by WindQAQ** [comment]
Looks like the PR gets rolled back. Let me know if anything I can help.

File: tensorflow/lite/kernels/internal/optimized/optimized_ops.h [hunk 6]
```diff
@@ -7730,6 +7728,238 @@ inline void BroadcastPReluDispatch(
...
+    // Mask indices of non-min values with max int32_t.
+    float32x4_t fill_min_value_f32x4 = vdupq_n_f32(min_value);
+    uint32x4_t mask = vceqq_f32(min_value_f32x4, fill_min_value_f32x4);
+    int32x4_t all_set = vdupq_n_s32(std::numeric_limits<int>::max());
+    min_index_s32x4 = vbslq_s32(mask, min_index_s32x4, all_set);
+    // Find min index of min values.
+#ifdef __aarch64__
+    min_index = vminvq_s32(min_index_s32x4);
+#else
+    uint32x2_t min_index_s32x2 = vpmin_s32(vget_low_s32(min_index_s32x4),
```
Comment (WindQAQ) [inline tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7801]: Here is an error: `uint32x2_t` -> `int32x2_t`.

File: tensorflow/lite/kernels/internal/optimized/optimized_ops.h [hunk 7]
```diff
@@ -7730,6 +7728,238 @@ inline void BroadcastPReluDispatch(
...
+    // Mask indices of non-max values with max int32_t.
+    float32x4_t fill_max_value_f32x4 = vdupq_n_f32(max_value);
+    uint32x4_t mask = vceqq_f32(max_value_f32x4, fill_max_value_f32x4);
+    int32x4_t all_set = vdupq_n_s32(std::numeric_limits<int>::max());
+    max_index_s32x4 = vbslq_s32(mask, max_index_s32x4, all_set);
+    // Find min index of max values.
+#ifdef __aarch64__
+    max_index = vminvq_s32(max_index_s32x4);
+#else
+    uint32x2_t max_index_s32x2 = vpmin_s32(vget_low_s32(max_index_s32x4),
```
Comment (WindQAQ) [inline tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7857]: ditto
