### PR TITLE
Fix for incorrect type and size calculated in ctstring_test on s390x

### LINKED ISSUE #56046: Test for TStrings of type "Offset" returns incorrect size on s390x arch
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

NA

### Python version

Python 3.8.10

### Bazel version

4.2.2

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

NA

### GPU model and memory

NA

### Current Behaviour?

```shell
TF_CTStringTest OffsetType fails as size or TF_TSTR_OFFSET are 0 on big endian.
As per analysis done, TF_TString_ToInternalSizeT calls from TF_TString_ResizeUninitialized as well as in test file(https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/core/platform/ctstring_test.cc#L397) returns a very high number but it is not decoded correctly.
Hence all calls such as TF_TString_GetSize, TF_TString_GetType return value of 0 on s390x.

Expected behaviour: This test should pass on BE systems as well.
```

### Standalone code to reproduce the issue

```shell
On s390x, run:
`bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test --strip never --jobs=10 --verbose_failures //tensorflow/core/platform:ctstring_test`
```

### Relevant log output

```shell
tensorflow/core/platform/ctstring_test.cc:401: Failure
Expected equality of these values:
  size
    Which is: 8
  TF_TString_GetSize(&s71)
    Which is: 0
tensorflow/core/platform/ctstring_test.cc:402: Failure
Expected equality of these values:
  TF_TSTR_OFFSET
    Which is: 2
  TF_TString_GetType(&s71)
    Which is: 0
[  FAILED  ] TF_CTStringTest.OffsetType (0 ms)
```
```
</details>

### PR DESCRIPTION
**Pull request by namrata-ibm**
The `OffsetType` test fails on s390x as it returns 0 for type/size. This is happening because [TF_TString_ToInternalSizeT](https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/core/platform/ctstring_internal.h#L158) returns 8 bytes(size_t is 8 bytes on s390x), however offset type has "size" which is uint32. Thus the data containing 'type' information is lost. This further causes wrong 'size' calculation [here](https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/core/platform/ctstring_internal.h#L184).  

The mark and other calculations work for Large type strings as the 'size' is 8bytes.
Fixes #56046. More details in that issue.

### CODE REVIEW

**Comment by namrata-ibm** [comment]
@gharibian could you please take a look?

**Comment by namrata-ibm** [comment]
@gbaned @gharibian Could you please check?

File: tensorflow/core/platform/ctstring_internal.h [hunk 1]
```diff
@@ -162,6 +162,14 @@ static inline size_t TF_TString_ToInternalSizeT(size_t size,
 #else   // TF_TSTRING_LITTLE_ENDIAN
   // 0xFF000000 or 0xFF00000000000000 depending on platform
   static const size_t mask = ~((~(size_t)0) >> 8);
+#if defined(__s390x__)
```
Comment (cantonios) [inline tensorflow/core/platform/ctstring_internal.h:165]: Judging from the description, this issue is not only present for s390x, we have the same thing for any big-endian system with 64-bit `size_t`.  In the case of big-endian and `TF_TSTR_OFFSET`, instead of putting the type in the MSB byte, we should *always* be putting it in the 4th byte from the right.

File: tensorflow/core/platform/ctstring_internal.h [hunk 2]
```diff
@@ -162,6 +162,14 @@ static inline size_t TF_TString_ToInternalSizeT(size_t size,
...
+  if (type == TF_TSTR_OFFSET) {
+    return (mask & (size << 2)) | (~mask & (size << 2)) |
```
Comment (cantonios) [inline tensorflow/core/platform/ctstring_internal.h:167]: This doesn't look right... I think the `type` information will be merged with existing (non-masked) bits.

Let's say the`size` is `0x00000000 3FFFFFFF`, and the type is `0x02` (offset)
```
size = 0x00000000 3FFFFFFF
mask = 0xFF000000 00000000

 mask & (size << 2) = 0x00000000 00000000
~mask & (size << 2) = 0x00000000 FFFFFFFC
         type << 24 = 0x00000000 20000000
                   _______________________
or                  = 0x00000000 FFFFFFFC
```
The type information is then corrupted.  I believe you want the mask to always be `0xFF000000` in the case of offset.

File: tensorflow/core/platform/ctstring_internal.h [hunk 3]
```diff
@@ -187,7 +195,11 @@ static inline size_t TF_TString_GetSize(const TF_TString *str) {
     case TF_TSTR_LARGE:
       return TF_TString_ToActualSizeT(str->u.large.size);
     case TF_TSTR_OFFSET:
+#if defined(__s390x__)
```
Comment (cantonios) [inline tensorflow/core/platform/ctstring_internal.h:198]: Shouldn't this be some kind of `TF_TString_ToActualSize_T`?

File: tensorflow/core/platform/ctstring_internal.h [hunk 4]
```diff
@@ -162,6 +162,14 @@ static inline size_t TF_TString_ToInternalSizeT(size_t size,
 #else   // TF_TSTRING_LITTLE_ENDIAN
   // 0xFF000000 or 0xFF00000000000000 depending on platform
   static const size_t mask = ~((~(size_t)0) >> 8);
+#if defined(__s390x__)
+  if (type == TF_TSTR_OFFSET) {
```
Comment (SeeForTwo) [inline tensorflow/core/platform/ctstring_internal.h:166]: Thank you for finding and reporting this bug!
My current understanding is that `TF_TString_ToInternalSizeT` should only be used with "large" and "view" representations that use `size_t size`. The "offset" representation uses "uint32_t size". My thought is that the issue should be solved by creating a `TF_TString_ToInternalUint32T` function (which uses `uint32_t` and not `size_t`) and have the test use this new function.

Comment (gharibian) [reply tensorflow/core/platform/ctstring_internal.h:166]: To clarify, the bug here is in the test; ctstring_test.cc is the only user of `TF_TString_ToInternalSizeT(..., TF_TSTR_OFFSET);` which as @SeeForTwo  mentioned is an invalid use.  This test was added after the original implementation.

The test should not be using internal functions for generating offset types.  Offset types were written as a placeholder for a future potential need for memory map-able tstrings, and as such, generation of offset types was not implemented, as they would need to be done with a series of tstrings in mind in order to generate an offset table and its associated packed contiguous data segement.  Generating a single OFFSET type doesn't have much use.

To resolve this either: 1) remove the test, or since OFFSET types are expected to be little-endian u32, 2) construct a byte sequence by hand for size and offset.

Comment (SeeForTwo) [reply tensorflow/core/platform/ctstring_internal.h:166]: Good summary.

> 2) construct a byte sequence by hand for size and offset.

This seems reasonable. While Offset types are currently a placeholder, some code for them exists and at can be exercised, so I see advantage in keeping and fixing the test.

Any other thoughts?

Comment (cantonios) [reply tensorflow/core/platform/ctstring_internal.h:166]: I have no preference.

Comment (gharibian) [reply tensorflow/core/platform/ctstring_internal.h:166]: Looking closer at the existing test, there are several issues with it. @namrata-ibm please replace the OffsetType test with the following and try it out on your big-endian arch.   If there are no issues, please update your pull request to include:

```
 TEST(TF_CTStringTest, OffsetType) {
    {
      uint8_t str[] = "test";
      constexpr size_t str_size = sizeof(str) / sizeof(str[0]);
   
      uint8_t buf[sizeof(TF_TString) + str_size];
   
      memcpy(buf + sizeof(TF_TString), str, str_size);
   
      TF_TString *offsets = (TF_TString *)buf;
      TF_TString_Init(offsets);
   
      offsets[0].u.offset.size = TF_le32toh(str_size << 2 | TF_TSTR_OFFSET);
      offsets[0].u.offset.offset = TF_le32toh(sizeof(TF_TString));
      offsets[0].u.offset.count = TF_le32toh(1);
                                                                                                                                                                                                                   
      EXPECT_EQ(str_size, TF_TString_GetSize(offsets));
      EXPECT_EQ(TF_TSTR_OFFSET, TF_TString_GetType(offsets));
      EXPECT_EQ(0, ::memcmp(str, TF_TString_GetDataPointer(offsets), str_size));
    }
  }
```

Comment (gharibian) [reply tensorflow/core/platform/ctstring_internal.h:166]: Note that we are 'technically' doing 'TF_htole32', but a macro with that name doesn't currently exist.  It would be the same exact function though. Feel free to add one in ctstring_internal.h or keep as is (and maybe make a comment)

Comment (namrata-ibm) [reply tensorflow/core/platform/ctstring_internal.h:166]: Thank you @cantonios @SeeForTwo @gharibian for your valuable comments. 
@gharibian I tried above test on BE, however `EXPECT_EQ(0, ::memcmp(str, TF_TString_GetDataPointer(offsets), str_size));` this check produces a crash on BE.

Comment (SeeForTwo) [reply tensorflow/core/platform/ctstring_internal.h:166]: @namrata-ibm, thank you for your patience! I would defer to @gharibian, but I think that in TF_TString_GetDataPointer the current:
```
    case TF_TSTR_OFFSET:
      return (const char *)str + str->u.offset.offset;  // NOLINT
```

should be changed to use TF_le32toh:

```
    case TF_TSTR_OFFSET:
      return (const char *)str + TF_le32toh(str->u.offset.offset);  // NOLINT
```

Comment (namrata-ibm) [reply tensorflow/core/platform/ctstring_internal.h:166]: @SeeForTwo Yes, that works on LE and BE.

Comment (gharibian) [reply tensorflow/core/platform/ctstring_internal.h:166]: That looks good, thanks for catching that @SeeForTwo

Comment (SeeForTwo) [reply tensorflow/core/platform/ctstring_internal.h:166]: > Yes, that works on LE and BE.

@namrata-ibm, wonderful! If you are happy with the working software that you have, could you please update the PR when you have time?  (My apologies if you've already updated and I'm just confused by how to see it in github.)

Comment (namrata-ibm) [reply tensorflow/core/platform/ctstring_internal.h]: @SeeForTwo Updated the PR, Thank you!

**Comment by gharibian** [comment]
Looks good, but can you squash this into a single commit?

**Comment by namrata-ibm** [comment]
> Looks good, but can you squash this into a single commit?

Done @gharibian , Apologies I missed it earlier.

**Review by gharibian — APPROVED** [review]

**Review by SeeForTwo — APPROVED** [review]
LGTM

**Comment by SeeForTwo** [comment]
Sorry for the inconvenience, but could please update the commit description to reflect what it currently is, i.e. this is now a fix for TF_TString_GetDataPointer method for the OffsetType, and fix for TEST(TF_CTStringTest, OffsetType)?

**Comment by namrata-ibm** [comment]
> Sorry for the inconvenience, but could please update the commit description to reflect what it currently is, i.e. this is now a fix for TF_TString_GetDataPointer method for the OffsetType, and fix for TEST(TF_CTStringTest, OffsetType)?

Updated the description. Thank you.

**Review by SeeForTwo — APPROVED** [review]
