### PR TITLE
Resolves: tf.raw_ops.ResourceSparseApplyAdagradV2 crashes when grad shape does not match indices and variable shape #106494

### LINKED ISSUE #106494: `tf.raw_ops.ResourceSparseApplyAdagradV2` crashes when `grad` shape does not match indices and variable shape
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf-2.19

### Custom code

Yes

### OS platform and distribution

_No response_

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current behavior?

Calling `tf.raw_ops.ResourceSparseApplyAdagradV2` with a grad tensor whose shape is incompatible with indices and the underlying resource variable can lead to a crash, instead of raising a clear Python exception.

The bug can be reproduced on tf-2.19. Here is the [gist](https://colab.research.google.com/drive/1x5H8BsCo4tBiQLzx5u6nig3RPMKFVU-w?usp=sharing).

### Standalone code to reproduce the issue

```shell
# BUG: tf.raw_ops.ResourceSparseApplyAdagradV2, grad shape mismatch
import tensorflow as tf

# Create resource variable
var = tf.Variable(tf.ones([3, 3], dtype=tf.float32))
# Create accumulators
accum = tf.Variable(tf.zeros([3, 3], dtype=tf.float32))

# Sparse indices and values
indices = tf.constant([0, 2], dtype=tf.int64)
values = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=tf.float32)

# Learning rate and epsilon
lr = tf.constant(0.01, dtype=tf.float32)
epsilon = tf.constant(1e-8, dtype=tf.float32)

# Invoke the operation
result = tf.raw_ops.ResourceSparseApplyAdagradV2(
    var=var.handle,
    accum=accum.handle,
    lr=lr,
    epsilon=epsilon,
    grad=tf.reshape(values, [-1]),  # Mismatched shape, crash
    # grad=values,  # success
    indices=indices,
    use_locking=False,
    update_slots=True
)
```

### Relevant log output

```shell
> 2025-12-17 15:21:00.264948: F tensorflow/core/framework/tensor_shape.cc:357] Check failed: d < dims() (1 vs. 1)
> [1]    3374216 abort (core dumped)
```

### PR DESCRIPTION
**Pull request by gagankonana**
This change adds an validation check to ensure the grad tensor has the same number of dimensions as the var tensor in SparseApplyAdagradOp and SparseApplyAdagradV2Op. This prevents accessing out of scope grad in the following for loop in case of var dimension being greater than grad's dim

Fixes #106494

### CODE REVIEW

File: tensorflow/core/kernels/training_ops.cc [hunk 1]
```diff
@@ -1923,7 +1923,10 @@ class SparseApplyAdagradOp : public OpKernel {
     const Tensor& indices = ctx->input(4);
     OP_REQUIRES(ctx, TensorShapeUtils::IsVector(indices.shape()),
                 errors::InvalidArgument("indices must be one-dimensional"));
-
+    
+    OP_REQUIRES(ctx, grad.dims() == var.dims(),
+                errors::InvalidArgument("grad must have the same number of "
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/training_ops.cc]: Please use absl errors instead of TF ones.

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]

File: tensorflow/core/kernels/training_ops.cc (hunk 1 above)
Comment (gagankonana) [reply tensorflow/core/kernels/training_ops.cc]: Got it, updated the PR to use absl errors

**Review by mihaimaruseac — APPROVED** [review]
