### PR TITLE
Pylint upgrade 2.6.2

### LINKED ISSUE #43038: Pylint incorrectly identifies tensorflow public API functions in tensorflow 2.2+
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Apart from the example below, no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04/OSX 10.15.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: :x:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2+
- Python version: 3.7.4
- Bazel version (if compiling from source): :x:
- GCC/Compiler version (if compiling from source): :x:
- CUDA/cuDNN version: :x:
- GPU model and memory: :x:

**Describe the current behavior**
When using pylint, a lot of functions from the public API are misidentified.
For example, the public api function `tf.split`, which is publicly defined as `tensorflow/python/ops/array_ops.split` is misidentified (I think as `tensorflow/python/ops/gen_array_ops.split`).

Other examples include `tf.random.uniform`, `tf.concat` and the list goes on.

Let's take the code snipped below:

`example.py`:
```python
import tensorflow as tf

tensor = tf.random.uniform((2, 4), minval=0, maxval=256)
tf.split(tensor, num_or_size_splits=2, axis=-1)
```

This is perfectly fine code, it runs as expected.

However, when running pylint both functions are misidentified and lots of linting errors are raised.
Running pylint on the module (`pylint -E example.py`) gives:
```
example.py:3:9: E1123: Unexpected keyword argument 'minval' in function call (unexpected-keyword-arg)
example.py:3:9: E1123: Unexpected keyword argument 'maxval' in function call (unexpected-keyword-arg)
example.py:3:9: E1120: No value for argument 'dtype' in function call (no-value-for-parameter)
example.py:4:0: E1123: Unexpected keyword argument 'num_or_size_splits' in function call (unexpected-keyword-arg)
example.py:4:0: E1124: Argument 'axis' passed by position and keyword in function call (redundant-keyword-arg)
example.py:4:0: E1120: No value for argument 'value' in function call (no-value-for-parameter)
example.py:4:0: E1120: No value for argument 'num_split' in function call (no-value-for-parameter)
```

**Describe the expected behavior**
Running `pylint -E example.py` should not give any errors.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

tensor = tf.random.uniform((2, 4), minval=0, maxval=256)
tf.split(tensor, num_or_size_splits=2, axis=-1)
```

**Other info / logs**
This occurs with `tensorflow>=2.2.0`.
Previous versions of tensorflow `2.X` (e.g. tensorflow `2.1.X` and tensorflow `2.0.X`) do not have these problems.

I have used `pylint==2.6.0` for the example, but previous versions have the same behaviour.

One of the things that might have caused this (just a guess) is the upgrade to a new version of `gast` that occurred in tensorflow `2.2`, where they went from `gast==0.2.2` to `gast==0.3.3`.

Now, I know that this issue is not a code breaking issue, but it is a workflow breaking issue when using tensorflow in a professional setting. For example, one of the requirements for passing all steps in the CI may be running pylint, which now fails. Pylint allow disabling errors for specific third-party packages, so really the only solution is to add a `pylint: disable=...` comment every time you use a tensorflow function which is misidentified or to disable pylint for the project all together. Both options aren't desirable.

This issue was also raised in the `pylint` repo (https://github.com/PyCQA/pylint/issues/3613) and probably also related to https://github.com/PyCQA/pylint/issues/3596. But I don't think these issues belong in the `pylint` repo` (or `astroid` for that matter), but here in the tensorflow repo as it's probably caused by the import structure of tensorflow.

One lead might be that a wildstar import overwrites functions. An examples might be the wildstar import in https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/ops/array_ops.py#L40 which overwrites `tensorflow/python/ops/array_ops.split` with the starred import `tensorflow/python/ops/gen_array_ops.split`. I'm not sure, but not performing wildstar imports might solve this linter problem.

### PR DESCRIPTION
**Pull request by bhack**
Re-submit https://github.com/tensorflow/tensorflow/pull/43040

Fixes https://github.com/tensorflow/tensorflow/issues/43038

/cc @mihaimaruseac Please discuss what we want as in  https://github.com/tensorflow/tensorflow/issues/43038#issuecomment-752186887

### CODE REVIEW

**Comment by bhack** [comment]
@mihaimaruseac It is failing cause we have `W9015(missing-param-doc)` also for private methods for  `accept-no-param-doc=no` in https://github.com/tensorflow/tensorflow/pull/45427.

Does we need to remove https://github.com/tensorflow/tensorflow/pull/45427/files#diff-ff33f686d9a6e4bde2c8f550590725560242378668dd748c3aaa193e166aef0aR213-R214? Or do you have a better idea to restrict this only on public classes?

**Comment by bhack** [comment]
Ok I've temp disabled `W9015` also for https://github.com/PyCQA/pylint/issues/2738

Now we have a nice list  of **4342** `non-allowlisted pylint errors`

https://source.cloud.google.com/results/invocations/9e90bea9-6dcb-4dcd-a95f-3db876d9b268/targets/%2F%2Ftensorflow%2Ftools%2Fci_build:gen_ci_sanity_out/log

File: tensorflow/tools/ci_build/install/install_pip_packages.sh [hunk 1]
```diff
@@ -94,7 +94,7 @@ pip3 install psutil
 pip2 install py-cpuinfo
 pip3 install py-cpuinfo
 
-# pylint==1.6.4 requires python-astroid (>= 1.4.5) requires lazy-object-proxy
+# pylint==2.6.0 requires python-astroid (>= 1.4.5) requires lazy-object-proxy
```
Comment (mihaimaruseac) [inline tensorflow/tools/ci_build/install/install_pip_packages.sh:97]:
```suggestion
# pylint==1.6.4 requires python-astroid (>= 1.4.5) requires lazy-object-proxy
```

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Now it's

```
FAIL: Found 64 non-allowlisted errors and 181 allowlisted errors
```

and a crash.

**Comment by bhack** [comment]
Is this https://github.com/PyCQA/pylint/issues/3686 ?

**Comment by mihaimaruseac** [comment]
Looks relevant. Will take a look

**Comment by mihaimaruseac** [comment]
Indeed, most of the errors, including some where seeing internally are caused by that one

**Comment by gbaned** [comment]
@mihaimaruseac Any update on this PR? Please. Thanks!

File: tensorflow/tools/ci_build/install/install_pip_packages.sh [hunk 2]
```diff
@@ -86,7 +86,8 @@ pip3 install lazy-object-proxy==1.4.3
 # pylint tests require the following version. pylint==1.6.4 hangs erratically,
 # thus using the updated version of 2.5.3 only for python3 as python2 is EOL
 # and this version is not available.
-pip3 install pylint==2.5.3
+pip3 install pylint==2.6.2
+pip3 install astroid==2.5
```
Comment (mihaimaruseac) [inline tensorflow/tools/ci_build/install/install_pip_packages.sh:90]: Let's put these on the same line, here and elsewhere.

This would make pip install them in a single pass and use a common set of dependencies.

**Review by mihaimaruseac — APPROVED** [review]

File: tensorflow/tools/ci_build/install/install_pip_packages.sh (hunk 2 above)
Comment (bhack) [reply tensorflow/tools/ci_build/install/install_pip_packages.sh:90]: That was the original idea but I don't know if it violated any policies :winkle:

**Review by mihaimaruseac — APPROVED** [review]

**Comment by bhack** [comment]
Now we have :
> FAIL: Found 2657 non-allowlisted errors and 13231 allowlisted errors

**Comment by bhack** [comment]
We have this histogram for the new non-allowlisted errors:

```
     37 E1121
     63 E0306
    158 E1102
    498 E1111
    877 E1123
   1024 E1120
```

**Comment by bhack** [comment]
Another view is:
```
     11 tensorflow/python/distribute/parameter_server_strategy_test.py:788: [E1111(assignment-from-no-return)
     11 tensorflow/python/distribute/parameter_server_strategy_test.py:810: [E1111(assignment-from-no-return)
     25 tensorflow/python/kernel_tests/random/multinomial_op_big_test.py:44: [E1123(unexpected-keyword-arg)
     25 tensorflow/python/kernel_tests/random/multinomial_op_big_test.py:62: [E1123(unexpected-keyword-arg)
     25 tensorflow/python/kernel_tests/random/multinomial_op_big_test.py:85: [E1123(unexpected-keyword-arg)
     37 tensorflow/python/ops/linalg/linear_operator_test_util.py:745: [E1121(too-many-function-args)
     53 tensorflow/python/keras/datasets/imdb.py:112: [E1123(unexpected-keyword-arg)
     59 tensorflow/python/tools/saved_model_cli.py:663: [E1123(unexpected-keyword-arg)
     60 tensorflow/python/training/tracking/python_state_test.py:131: [E1123(unexpected-keyword-arg)
     63 tensorflow/python/autograph/pyct/static_analysis/annos.py:29: [E0306(invalid-repr-returned)
     67 tensorflow/python/keras/datasets/boston_housing.py:66: [E1123(unexpected-keyword-arg)
     69 tensorflow/python/keras/datasets/mnist.py:63: [E1123(unexpected-keyword-arg)
     77 tensorflow/python/keras/utils/composite_tensor_support_test.py:363: [E1123(unexpected-keyword-arg)
     77 tensorflow/python/keras/utils/composite_tensor_support_test.py:366: [E1123(unexpected-keyword-arg)
     77 tensorflow/python/keras/utils/composite_tensor_support_test.py:601: [E1123(unexpected-keyword-arg)
     79 tensorflow/python/framework/dtypes.py:483: [E1120(no-value-for-parameter)
     79 tensorflow/python/framework/op_callbacks_test.py:671: [E1102(not-callable)
     79 tensorflow/python/framework/op_callbacks_test.py:672: [E1102(not-callable)
     85 tensorflow/python/lib/io/file_io_test.py:673: [E1123(unexpected-keyword-arg)
     87 tensorflow/python/data/kernel_tests/iterator_test.py:894: [E1123(unexpected-keyword-arg)
     91 tensorflow/python/keras/datasets/reuters.py:119: [E1123(unexpected-keyword-arg)
     98 tensorflow/python/framework/test_util_test.py:719: [E1111(assignment-from-no-return)
    126 tensorflow/python/summary/writer/event_file_writer_v2.py:93: [E1111(assignment-from-no-return)
    126 tensorflow/python/summary/writer/event_file_writer_v2.py:94: [E1111(assignment-from-no-return)
    126 tensorflow/python/summary/writer/event_file_writer_v2.py:95: [E1111(assignment-from-no-return)
    189 tensorflow/python/platform/flags_test.py:29: [E1120(no-value-for-parameter)
    189 tensorflow/python/platform/flags_test.py:33: [E1120(no-value-for-parameter)
    189 tensorflow/python/platform/flags_test.py:37: [E1120(no-value-for-parameter)
    189 tensorflow/python/platform/flags_test.py:41: [E1120(no-value-for-parameter)
    189 tensorflow/python/platform/flags_test.py:45: [E1120(no-value-for-parameter)
```

**Review by mihaimaruseac — APPROVED** [review]

**Comment by bhack** [comment]
Now Ubuntu sanity is ok.

**Comment by mihaimaruseac** [comment]
Then we can merge this. Thank you

**Review by mihaimaruseac — APPROVED** [review]
