### PR TITLE
Fix of issue #13164 (Merges #13382)

### LINKED ISSUE #13164: BUG: No GPU kernel for tf.scatter_nd and tf.gather_nd with int32 or int64 tensors
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
binary (pip)
- **TensorFlow version (use command below)**:
v1.3.0-rc2-20-g0787eee 1.3.0
- **Python version**: 
Python 3.5.2
- **Bazel version (if compiling from source)**:
n/a
- **CUDA/cuDNN version**:
CUDA-8.0 / cuDNN-5.1
- **GPU model and memory**:
NVidia GeForce GTX TITAN with 5.93GiB
- **Exact command to reproduce**:
```
import tensorflow as tf
import numpy as np

val_num = 5
val_dim = 2

with tf.device("/gpu:0"):
    indices = tf.reshape(tf.range(val_num, dtype=tf.int64), [-1, 1])
    updates = tf.constant(np.tile(np.expand_dims(np.arange(val_num, dtype=np.int64), 1), [1, val_dim]))

    res = tf.scatter_nd(indices, updates, [val_num, val_dim])
    #res = tf.gather_nd(updates, indices)

    sess = tf.Session()
    sess.run(tf.global_variables_initializer())

    print(sess.run(res))
```

### Describe the problem
**tf.scatter_nd** and **tf.gather_nd** do not support **int32** or **int64** tensors on GPU.

### Source code / logs
tf.scatter_nd:
```
2017-09-19 22:33:55.447883: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 22:33:55.447965: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 22:33:55.649706: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-09-19 22:33:55.650199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
name: GeForce GTX TITAN
major: 3 minor: 5 memoryClockRate (GHz) 0.8755
pciBusID 0000:04:00.0
Total memory: 5.93GiB
Free memory: 5.63GiB
2017-09-19 22:33:55.650286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0
2017-09-19 22:33:55.650299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y
2017-09-19 22:33:55.650316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN, pci bus id: 0000:04:00.0)
Traceback (most recent call last):
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1297, in _run_fn
    self._extend_graph()
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'ScatterNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScatterNd = ScatterNd[T=DT_INT64, Tindices=DT_INT64, _device="/device:GPU:0"](Reshape, Const, ScatterNd/shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 15, in <module>
    sess.run(tf.global_variables_initializer())
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'ScatterNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScatterNd = ScatterNd[T=DT_INT64, Tindices=DT_INT64, _device="/device:GPU:0"](Reshape, Const, ScatterNd/shape)]]

Caused by op 'ScatterNd', defined at:
  File "bug.py", line 11, in <module>
    res = tf.scatter_nd(indices, updates, [val_num, val_dim])
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2961, in scatter_nd
    shape=shape, name=name)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'ScatterNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScatterNd = ScatterNd[T=DT_INT64, Tindices=DT_INT64, _device="/device:GPU:0"](Reshape, Const, ScatterNd/shape)]]

```

tf.gather_nd:
```
2017-09-19 22:34:26.298344: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 22:34:26.298436: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 22:34:26.504483: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-09-19 22:34:26.504948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
name: GeForce GTX TITAN
major: 3 minor: 5 memoryClockRate (GHz) 0.8755
pciBusID 0000:04:00.0
Total memory: 5.93GiB
Free memory: 5.61GiB
2017-09-19 22:34:26.505032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0
2017-09-19 22:34:26.505044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y
2017-09-19 22:34:26.505061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN, pci bus id: 0000:04:00.0)
Traceback (most recent call last):
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1297, in _run_fn
    self._extend_graph()
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'GatherNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: GatherNd = GatherNd[Tindices=DT_INT64, Tparams=DT_INT64, _device="/device:GPU:0"](Const, Reshape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 15, in <module>
    sess.run(tf.global_variables_initializer())
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'GatherNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: GatherNd = GatherNd[Tindices=DT_INT64, Tparams=DT_INT64, _device="/device:GPU:0"](Const, Reshape)]]

Caused by op 'GatherNd', defined at:
  File "bug.py", line 12, in <module>
    res = tf.gather_nd(updates, indices)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1338, in gather_nd
    name=name)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'GatherNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: GatherNd = GatherNd[Tindices=DT_INT64, Tparams=DT_INT64, _device="/device:GPU:0"](Const, Reshape)]]

```

### PR DESCRIPTION
**Pull request by Androbin**
Deconflicts #13382
Fixes #13164
@dantkz /cc
@ebrevdo /cc

### CODE REVIEW

**Comment by rmlarsen** [comment]
Could the authors please sign the CLA?

File: tensorflow/core/common_runtime/gpu/process_state.cc [hunk 1]
```diff
@@ -207,7 +207,8 @@ Allocator* ProcessState::GetCPUAllocator(int numa_node) {
               << cpu_mem_limit_in_mb << " MB for ProcessState CPU allocator";
     } else {
       allocator = new PoolAllocator(
-          100 /*pool_size_limit*/, true /*auto_resize*/,
+          //100 /*pool_size_limit*/, true /*auto_resize*/,
+          30000 /*pool_size_limit*/, false /*auto_resize*/,
```
Comment (ebrevdo) [inline tensorflow/core/common_runtime/gpu/process_state.cc]: you probably want to revert this?

File: tensorflow/core/kernels/gather_nd_op.cc [hunk 2]
```diff
@@ -228,6 +228,8 @@ namespace functor {
   DECLARE_GPU_SPECS_INDEX(T, int32); \
   DECLARE_GPU_SPECS_INDEX(T, int64)
 
+TF_CALL_int32(DECLARE_GPU_SPECS);
```
Comment (ebrevdo) [inline tensorflow/core/kernels/gather_nd_op.cc]: this seems out of scope.  i'm ok with the int64 version, but we tend to not provide int32 variants on gpu.  for example, see gather() which doesn't allow gathers into int32 tensors on gpu.

File: tensorflow/core/kernels/gather_nd_op.cc [hunk 3]
```diff
@@ -239,6 +241,8 @@ TF_CALL_complex128(DECLARE_GPU_SPECS);
 // Registration of the GPU implementations.
 #define REGISTER_GATHER_ND_GPU(type) REGISTER_GATHER_ND_ALL_INDICES(GPU, type)
 
+TF_CALL_int32(REGISTER_GATHER_ND_GPU);
```
Comment (ebrevdo) [inline tensorflow/core/kernels/gather_nd_op.cc]: ditto

File: tensorflow/core/kernels/gather_nd_op_gpu.cu.cc [hunk 4]
```diff
@@ -119,6 +119,8 @@ struct GatherNdSlice<GPUDevice, T, Index, IXDIM> {
   DEFINE_GPU_SPECS_INDEX(T, int32); \
   DEFINE_GPU_SPECS_INDEX(T, int64);
 
+TF_CALL_int32(DEFINE_GPU_SPECS);
```
Comment (ebrevdo) [inline tensorflow/core/kernels/gather_nd_op_gpu.cu.cc]: ditto

File: tensorflow/core/kernels/gather_op.cc [hunk 5]
```diff
@@ -150,6 +150,8 @@ TF_CALL_qint16(REGISTER_GATHER_CPU);
 // Registration of the GPU implementations.
 #define REGISTER_GATHER_GPU(type) REGISTER_GATHER_ALL_INDICES(GPU, type)
 
+TF_CALL_int32(REGISTER_GATHER_GPU);
```
Comment (ebrevdo) [inline tensorflow/core/kernels/gather_op.cc]: ditto

File: tensorflow/core/kernels/scatter_functor.cc [hunk 6]
```diff
@@ -46,6 +46,8 @@ namespace functor {
   DECLARE_GPU_SPECS_INDEX(T, int32); \
   DECLARE_GPU_SPECS_INDEX(T, int64);
 
+TF_CALL_int32(DECLARE_GPU_SPECS);
```
Comment (ebrevdo) [inline tensorflow/core/kernels/scatter_functor.cc]: ditto; here and below.

File: tensorflow/core/kernels/scatter_functor_gpu.cu.cc [hunk 7]
```diff
@@ -37,6 +37,9 @@ typedef Eigen::GpuDevice GPUDevice;
   DEFINE_GPU_SPECS_INDEX(T, int32); \
   DEFINE_GPU_SPECS_INDEX(T, int64);
 
+DEFINE_GPU_SPECS(int32);
```
Comment (ebrevdo) [inline tensorflow/core/kernels/scatter_functor_gpu.cu.cc]: ditto

File: tensorflow/core/kernels/scatter_nd_op.cc [hunk 8]
```diff
@@ -270,6 +271,9 @@ TF_CALL_complex128(REGISTER_SCATTER_ND_ALL_GPU);
 #define REGISTER_SCATTER_ND_UPDATE_SYCL(type) \
   REGISTER_SCATTER_ND_UPDATE(type, SYCL);
 
+// TODO: check if SYCL supports these
+TF_CALL_int32(REGISTER_SCATTER_ND_ADD_SUB_SYCL);
```
Comment (ebrevdo) [inline tensorflow/core/kernels/scatter_nd_op.cc]: remove

File: tensorflow/core/kernels/scatter_nd_op.cc [hunk 9]
```diff
@@ -540,6 +544,7 @@ namespace functor {
   DECLARE_GPU_SPECS_INDEX(T, int32); \
   DECLARE_GPU_SPECS_INDEX(T, int64)
 
+TF_CALL_int32(DECLARE_GPU_SPECS);
```
Comment (ebrevdo) [inline tensorflow/core/kernels/scatter_nd_op.cc]: remove

File: tensorflow/core/kernels/scatter_nd_op_gpu.cu.cc [hunk 10]
```diff
@@ -149,6 +149,7 @@ struct ScatterNdFunctor<GPUDevice, T, Index, op, IXDIM> {
   DECLARE_GPU_SPECS_INDEX(T, int32); \
   DECLARE_GPU_SPECS_INDEX(T, int64)
 
+TF_CALL_int32(DECLARE_GPU_SPECS);
```
Comment (ebrevdo) [inline tensorflow/core/kernels/scatter_nd_op_gpu.cu.cc]: remove

File: tensorflow/python/kernel_tests/gather_nd_op_test.py [hunk 11]
```diff
@@ -207,7 +219,20 @@ def testBadIndices(self):
...
+    with self.test_session(use_gpu=False):
+      params = [[0, 1, 2]]
+      indices = [[[0], [0], [1]]]  # Make this one higher rank
+      gather_nd = array_ops.gather_nd(params, indices)
+      with self.assertRaisesOpError(
+          r"flat indices\[2, :\] = \[1\] does not index into param "
+          r"\(shape: \[1,3\]\)"):
+        gather_nd.eval()
+
+  def _disabledTestBadIndicesWithSlicesGPU(self):
```
Comment (ebrevdo) [inline tensorflow/python/kernel_tests/gather_nd_op_test.py]: check if a gpu is available, and if not then return.

Comment (ebrevdo) [reply tensorflow/python/kernel_tests/gather_nd_op_test.py]: (re-enable the test)

**Review by ebrevdo — CHANGES_REQUESTED** [review]

File: tensorflow/python/kernel_tests/gather_nd_op_test.py (hunk 11 above)
Comment (Androbin) [reply tensorflow/python/kernel_tests/gather_nd_op_test.py]: @dantkz How would we address the TODO?

Comment (dantkz) [reply tensorflow/python/kernel_tests/gather_nd_op_test.py]: @Androbin Do you mean "TODO: check if SYCL supports these"? It's fine to remove the changes and remove the TODO comment.

Comment (Androbin) [reply tensorflow/python/kernel_tests/gather_nd_op_test.py]: No, I mean these:
```
TODO disabled due to different behavior of gather_nd and gather on GPU and CPU
On GPU the bad indices do not raise error but fetch 0 values
```

**Comment by rmlarsen** [comment]
@Androbin Before we can merge, we need all authors to confirm in this thread that they are OK with submitting the code to TensorFlow.

**Review by ebrevdo — DISMISSED** [review]
Use `test.is_gpu_available()` to see if you should run the GPU test or return early.

**Comment by Androbin** [comment]
@rmlarsen Sure. @dantkz Are you okay with it?

File: tensorflow/python/kernel_tests/gather_nd_op_test.py (hunk 11 above)
Comment (dantkz) [reply tensorflow/python/kernel_tests/gather_nd_op_test.py]: Oh, I don't think there is anything that can be done. That test function is there in case the default behaviour of GPU gather changes.

**Comment by dantkz** [comment]
@Androbin I'm okay with it.

**Comment by rmlarsen** [comment]
@Androbin @dantkz Thanks.

**Comment by Androbin** [comment]
@dantkz Can we leave `testBadIndicesGPU` like this?

**Comment by dantkz** [comment]
@Androbin No, this `testBadIndicesGPU` will fail on GPU, because scatter_nd and gather_nd do not check the boundaries on GPU for efficiency.

**Comment by Androbin** [comment]
@ebrevdo Is there a way to catch the CUDA error or shall we disable for now?

**Comment by Androbin** [comment]
@dantkz Why doesn't this fail for current `master` then?

**Comment by dantkz** [comment]
@Androbin Last time I checked (a while back), the master branch does the test on CPU only.

**Comment by Androbin** [comment]
> Last time I checked (a while back), the master branch does the test on CPU only.

@dantkz Shouldn't [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/gather_nd_op_test.py#L201) make it use the GPU?
`with self.test_session(use_gpu=True):`

Doesn't seem to crash there...

**Comment by Androbin** [comment]
The build fails with some cryptic error message:
`undefined symbol: _ZN10tensorflow7functor16ScatterNdFunctorIN5Eigen9GpuDeviceEiiLNS_13scatter_nd_op8UpdateOpE0ELi6EEclERKS3_iNS2_5arrayIlLm6EEENS2_9TensorMapINS2_6TensorIiLi2ELi1ElEELi16ENS2_11MakePointerEEENSB_INSC_IKiLi2ELi1ElEELi16ESE_EESI_SF_`

**Comment by dantkz** [comment]
> @dantkz Shouldn't this line make it use the GPU?
> with self.test_session(use_gpu=True):
> 
> Doesn't seem to crash there...
I think `(use_gpu=True)` makes the op run on GPU only if the corresponding GPU kernel exists. There is a separate flag (force_gpu=True).
In the test code, the inputs are ints, and master branch only has CPU kernel for ints. Again, I'm basing this on the master branch from a while back.

**Comment by Androbin** [comment]
Okay, disabling GPU for now.

**Comment by rmlarsen** [comment]
@ebrevdo another look, please?

**Comment by Androbin** [comment]
We're getting this weird error all over the place:
`ImportError: /tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/examples/adding_an_op/cuda_op_test.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow7functor16ScatterNdFunctorIN5Eigen9GpuDeviceEiiLNS_13scatter_nd_op8UpdateOpE0ELi6EEclERKS3_iNS2_5arrayIlLm6EEENS2_9TensorMapINS2_6TensorIiLi2ELi1ElEELi16ENS2_11MakePointerEEENSB_INSC_IKiLi2ELi1ElEELi16ESE_EESI_SF_`

The last part looks somewhat like `tensorflow functor ScatterNdFunctor Eigen GpuDevice scatter_nd_op UpdateOp array TensorMap Tensor MakePointer`

**Comment by ebrevdo** [comment]
Looks like you're adding a declaration for some higher level template but
not for an implementation.  The demangled error:

tensorflow::functor::ScatterNdFunctor<Eigen::GpuDevice, int, int,
(tensorflow::scatter_nd_op::UpdateOp)0, 6>::operator()(Eigen::GpuDevice
const&, int, Eigen::array<long, 6ul>, Eigen::TensorMap<Eigen::Tensor<int,
2, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorMap<Eigen::Tensor<int
const, 2, 1, long>, 16, Eigen::MakePointer>,
Eigen::TensorMap<Eigen::Tensor<int const, 2, 1, long>, 16,
Eigen::MakePointer>, Eigen::TensorMap<Eigen::Tensor<int, 2, 1, long>, 16,
Eigen::MakePointer>)

Perhaps you forgot to remove a TF_call somewhere?  Here it looks like you
still have a TF_call for int type on GPU.  You removed it somewhere in the
impl but not in the declaration.


On Mon, Jan 29, 2018 at 12:04 PM, Robin Richtsfeld <notifications@github.com

**Comment by Androbin** [comment]
I see. @dantkz do we yet have CudaAtomic* kernels for int64?
In other words, should we comment [DECLARE_GPU_SPECS](https://github.com/tensorflow/tensorflow/pull/16368/files#diff-5d2c10864fe0081c8272db95dd2fad87R49) or uncomment [DEFINE_GPU_SPECS](https://github.com/tensorflow/tensorflow/pull/16368/files#diff-6e486a435530b37fa19b6d23d1fea1ceR41)?

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dantkz** [comment]
@Androbin I think you've hit the issue that stopped me after I had merged master branch. Gather_nd and scatter_nd stopped working with int64 declarations somewhere between tf.1.3 and tf1.4 versions. I can't figure out which of the CudaAtomic* kernels is causing the problem. Can you check if int32 compiles and it is int64 kernel missing?

**Comment by Androbin** [comment]
@ebrevdo Let's run tests without the scatter op int64 version.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Androbin** [comment]
@ebrevdo Let's run tests without the scatter op int64 version.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Androbin** [comment]
This time, I commented all int64 versions. If it works now, we can start re-adding them.

**Comment by rmlarsen** [comment]
@ebrevdo another look?

**Comment by tensorflowbutler** [comment]
Nagging Reviewer : It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

**Comment by ppwwyyxx** [comment]
Any updates? @ebrevdo 
It has been __eight__ months since the original PR.

**Comment by Androbin** [comment]
@dantkz Even with all new references to `int64`, the builds fail:
https://source.cloud.google.com/results/invocations/edcda7d3-0a86-4618-b940-91951312aeb3/log
Maybe it's not about `dtypes`, but about order or something?

**Comment by Androbin** [comment]
@rmlarsen The CLA-Bot has a hiccup again.
@ebrevdo Would you mind elaborating on https://github.com/tensorflow/tensorflow/pull/16368#issuecomment-361370094?

**Comment by ppwwyyxx** [comment]
@Androbin You declared the scatter_nd op with int32, but did not declare or define the corresponding kernels.
Maybe let's do one thing at a time. Removing the changes on scatter_nd op should at least make it build.

File: tensorflow/core/kernels/gather_op.cc [hunk 12]
```diff
@@ -153,6 +153,8 @@ TF_CALL_uint64(REGISTER_GATHER_CPU);
 // Registration of the GPU implementations.
 #define REGISTER_GATHER_GPU(type) REGISTER_GATHER_ALL_INDICES(GPU, type)
 
+// The following fails to compile due to lack of CudaAtomic* kernels for int64.
+//TF_CALL_int64(REGISTER_GATHER_GPU);
```
Comment (ppwwyyxx) [inline tensorflow/core/kernels/gather_op.cc]: You define int32 kernels for gather but did not register the corresponding op. So the change will have no effect.

Also, with int64 I compiled and saw no error. Not sure what was the error you saw or was it an issue with cuda version.

Comment (Androbin) [reply tensorflow/core/kernels/gather_op.cc]: I think @ebrevdo asked to remove int32 for GPU, seems like I've missed some.

I think @dantkz was the one to report this issue originally.
But if it works for you, we're probably fine now.

Comment (ppwwyyxx) [reply tensorflow/core/kernels/gather_op.cc]: Well if you removed int32 this PR seems to be purely about improving the tests for badindices.

Comment (Androbin) [reply tensorflow/core/kernels/gather_op.cc]: We can however add int64 for GPU.

Comment (Androbin) [reply tensorflow/core/kernels/gather_op.cc]: Or maybe that was only for scatter and gather, not scatter_nd and gather_nd?

**Comment by Androbin** [comment]
@ppwwyyxx I've gone through all comments once more and updated the code:
* `tf.gather` and `tf.scatter` now support `int64` on GPU
* `tf.gather_nd` and `tf.scatter_nd` now support `int32` and `int64` on GPU

**Comment by Androbin** [comment]
See [earlier comments](https://github.com/tensorflow/tensorflow/pull/13382#discussion_r143081981) by @ebrevdo and @zheng-xq.
I'm not entirely sure about the change in `dense_update_functor_gpu`.

File: tensorflow/python/kernel_tests/gather_op_test.py [hunk 13]
```diff
@@ -27,7 +27,8 @@
 from tensorflow.python.ops import gradients_impl
 from tensorflow.python.platform import test
 
-_TEST_TYPES = (dtypes.float32, dtypes.complex64, dtypes.complex128)
+_TEST_TYPES = (dtypes.int32, dtypes.int64, dtypes.float32,
```
Comment (ppwwyyxx) [inline tensorflow/python/kernel_tests/gather_op_test.py]: You have not added int32 for gather.

File: tensorflow/core/kernels/gather_nd_op.cc (hunk 2 above)
Comment (ppwwyyxx) [reply tensorflow/core/kernels/gather_nd_op.cc]: @Androbin maybe int32 support still needs to be reverted?

File: tensorflow/python/kernel_tests/gather_op_test.py (hunk 13 above)
Comment (Androbin) [reply tensorflow/python/kernel_tests/gather_op_test.py]: Touché

File: tensorflow/core/kernels/gather_nd_op.cc (hunk 2 above)
Comment (Androbin) [reply tensorflow/core/kernels/gather_nd_op.cc]: I honestly don't know. It seems to be a design question. [Not long ago](https://github.com/tensorflow/tensorflow/pull/13382#discussion_r143081981), he said:
> I'm perfectly OK with scatter_nd and gather_nd getting GPU kernels for int32/int64, but not scatter/gather.

Comment (Androbin) [reply tensorflow/core/kernels/gather_nd_op.cc]: Maybe the team changed opinions, or it's just a misunderstanding here.

**Comment by ppwwyyxx** [comment]
Could you run the builds and tests locally? Otherwise the progress will be really slow.
I did see cuda atomic error with int64 now, but it only happens with scatter and scatter_nd. Gather with int64 can build.

**Comment by Androbin** [comment]
Okay, I have removed `int64` versions of `scatter` and `scatter_nd`:
* `tf.gather` now supports `int64` on GPU
* `tf.gather_nd` now supports `int32` and `int64` on GPU
* `tf.scatter_nd` now supports `int32` on GPU

@ppwwyyxx I'm trying to test locally, but I seem to be doing it wrong...

**Comment by Androbin** [comment]
@ebrevdo Could you clarify if the `int32` `_nd` versions are fine?

**Comment by ebrevdo** [comment]
I'm okay with it. We have a couple of important GPU workloads e.g. those that deal with text like the transformer model where this may create a performance regression.  It's hard to tell where this would make a difference.  I say we push the _nd int32 versions and roll back if we see regressions.

**Comment by Androbin** [comment]
@rmlarsen I think we've fixed the bemangled errors. Let's restart the builds.

**Comment by ppwwyyxx** [comment]
@Androbin You'll probably need https://github.com/ppwwyyxx/tensorflow/commit/2919f8202fb09a335637cfffe15535e27f115f1a#diff-5f4f48f44c131a218fdb75162e12b138 for the tests to pass.

**Comment by rmlarsen** [comment]
@Androbin Could you please fix the linter errors: https://source.cloud.google.com/results/invocations/c0838386-0b52-4be9-843a-90c453b7ea76/log

**Comment by Androbin** [comment]
@rmlarsen Indentation is fixed now.

**Comment by Androbin** [comment]
@rmlarsen Indentation is fixed now.

**Comment by ppwwyyxx** [comment]
@rmlarsen Seems like the tests have passed but the CI reports some unknown error.

**Comment by rmlarsen** [comment]
Well, maybe if we keep running it :-/

**Comment by Androbin** [comment]
Now the logs explicitly state they were "successful", have "passed", the entire invocation (which overall previously failed for some reason).
@rmlarsen Maybe it's just a hiccup? Someone might want to reboot them...

**Review by rmlarsen — APPROVED** [review]

**Comment by rmlarsen** [comment]
@Androbin thanks for your patience.
