### PR TITLE
[TF-TRT] Fix TRTEngineOP Inference Shape

### LINKED ISSUE #52934: [TF-TRT] - TRTEngineOP do not show output shape
TRTEngineOP node attribute `_output_shapes` returns an empty list. We need to fix that.

@bixia1 @tfeher  FYI

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
@bixia1 for review
CC: @tfeher

This PR addresses that TRTEngineOP do not mention any output shape in the Graphdef, which limit graphdef analysis, and can block large scale deployment with framework like TRITON Inference Server.

Fix : #52934

### CODE REVIEW

File: tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc [hunk 1]
```diff
@@ -366,18 +368,31 @@ Status CreateTRTNode(const ConversionParams& params,
...
+        // Set the shapes and data types of the output edge.
+        tensorflow::TensorShapeProto out_shape;
+        conn.inside_shape.AsProto(&out_shape);
+
+        if (output_shapes.size() <= conn.port_number) {
+          output_shape_protos.resize(conn.port_number + 1);
+          output_shapes.resize(conn.port_number + 1);
+        }
+        output_shape_protos.at(conn.port_number) = out_shape;
+        output_shapes.at(conn.port_number) = conn.inside_shape;
```
Comment (bixia1) [inline tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:380]: Can we find a way to share this code snippet with the input case below?

File: tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+from tensorflow.python.saved_model import signature_constants
+from tensorflow.python.saved_model import tag_constants
+
+from tensorflow.python.ops import array_ops
+from tensorflow.python.ops import math_ops
+from tensorflow.python.ops import nn
+
+
+class TRTEngineOpInputOutputShapeTest(trt_test.TfTrtIntegrationTestBase):
+  """Testing conversion of Conv2D (data_format=NCHW) in TF-TRT conversion."""
```
Comment (bixia1) [inline tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py:36]: This is copied pasted from another test? Let's fix the comment.

File: tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+    c = nn.relu(b)
+    d1 = c + c
+    d2 = math_ops.reduce_sum(d1)
+
+    d1 = array_ops.identity(d1, name="output_0")
+    d2 = array_ops.identity(d2, name="output_1")
+    return d1, d2
+
+  def GetParams(self):
+    # TODO(aaroey): test graph with different dtypes.
```
Comment (bixia1) [inline tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py:49]: Either rewrite the TODO or delete it?

File: tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+      for out_shape in func.outputs
+    ]
+
+    assert (func.inputs[0].dtype == dtypes.float32)
+    assert (func.outputs[0].dtype == dtypes.float32)
+    assert (func.outputs[1].dtype == dtypes.float32)
+
+    assert (input_shape == [None, 2, 1, 4])
+    assert (output_shapes[0] == [None, 2, 4])
+    assert (output_shapes[1] == [])
```
Comment (bixia1) [inline tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py:84]: We don't use assert to check test result, instead use self.assertEqual etc.

File: tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py (hunk 3 above)
Comment (DEKHTIARJonathan) [reply tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py:49]: Fixed

File: tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py (hunk 4 above)
Comment (DEKHTIARJonathan) [reply tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py:84]: Fixed

File: tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py (hunk 2 above)
Comment (DEKHTIARJonathan) [reply tensorflow/python/compiler/tensorrt/test/trt_engine_op_shape_test.py:36]: Fixed

File: tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc (hunk 1 above)
Comment (DEKHTIARJonathan) [reply tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:380]: I'm gonna try to do smthg on that. WIP

Comment (DEKHTIARJonathan) [reply tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc]: Fixed

**Comment by DEKHTIARJonathan** [comment]
@bixia1 all comments have been addressed

**Review by bixia1 — APPROVED** [review]

**Comment by bixia1** [comment]
I got this error when trying to merge it:
WARN: Cannot migrate http://github.com/tensorflow/tensorflow/pull/53327 because it is missing the following labels: [cla: yes]
