### PR TITLE
Fixed a bug in the xnnpack delegate option for label_image.

### LINKED ISSUE #56367: [TensorFlow Lite label_image]  Abort occurs with xnnpack_delegate option.
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

v2.9.1 (or master)

### Custom Code

No

### OS Platform and Distribution

Raspberry Pi OS (bullseye)

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/Compiler version

gcc version 10.2.1 20210110 (Debian 10.2.1-6) 

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current Behaviour?

```shell
Build tensorflow-lite and label_image from source (with CMake).
Execute with the `--xnnpack_delegate` option.

label_image \
  --tflite_model /tmp/mobilenet_v1_1.0_224.tflite \
  --labels /tmp/labels.txt \
  --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp \
  --xnnpack_delegate 1
Type mismatch while accessing parameter.
Abort
```
```


### Standalone code to reproduce the issue

```shell
Clone repository.

git clone -b v2.9.1 https://github.com/tensorflow/tensorflow.git
```

Build tensorflow-lite and label_image
```
mkdir build && cd build
cmake ../tensorflow/tensorflow/lite/
cmake --build . -j$(nproc)
cmake --build . -j$(nproc) -t label_image
```

Download tflite model
```
wget https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz
tar xf mobilenet_v1_1.0_224.tgz
wget  https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_1.0_224_frozen.tgz
tar xf mobilenet_v1_1.0_224_frozen.tgz
cp mobilenet_v1_1.0_224/labels.txt ./
```

Exec label_image (with use_xnnpack option)
```
./examples/label_image/label_image \
  --tflite_model ./mobilenet_v1_1.0_224.tflite \
  --labels ./labels.txt \
  --image ../tensorflow/tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp
```
```


### Relevant log output

_No response_</details>

### PR DESCRIPTION
**Pull request by NobuoTsukamoto**
Fixed #56367 .

### CODE REVIEW

File: tensorflow/lite/examples/label_image/label_image.cc [hunk 1]
```diff
@@ -126,7 +126,7 @@ class DelegateProviders {
                      "XNNPACK delegate isn't supported on the platform!";
       } else {
         params_.Set<bool>("use_xnnpack", true);
-        params_.Set<bool>("num_threads", s.number_of_threads);
+        params_.Set<int32_t>("num_threads", s.number_of_threads);
```
Comment (terryheo) [inline tensorflow/lite/examples/label_image/label_image.cc:129]: So it interfered xnnpack delegate option?

**Review by terryheo — APPROVED** [review]

File: tensorflow/lite/examples/label_image/label_image.cc (hunk 1 above)
Comment (NobuoTsukamoto) [reply tensorflow/lite/examples/label_image/label_image.cc:129]: Yes. Cannot be executed with the xnnpack delegate option.
```
Type mismatch while accessing parameter.
Abort
```


When specifying the xnnpack delegate option, the specification in `Interpreter::SetNumThreads` does not work. Must be specified in `DelegateProviders`.

Comment (terryheo) [reply tensorflow/lite/examples/label_image/label_image.cc:129]: Got it. Thanks for the confirmation.
