### PR TITLE
Resolve issue 17698: Session JNI interface has memory leak

### LINKED ISSUE #17698: Session JNI interface has memory leak
System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): Master
Python version: 3.6
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from source): N/A
CUDA/cuDNN version: None
GPU model and memory: None
Exact command to reproduce: Run the snippet below.

Describe the problem
Read the tensorflow_jni.cc code in the code section as blow.

```
  TF_Graph* graph = reinterpret_cast<TF_Graph*>(graph_handle);
  TF_Status* status = TF_NewStatus();
  TF_SessionOptions* opts = TF_NewSessionOptions();
  const char* ctarget = nullptr;
  jbyte* cconfig = nullptr;
  if (target != nullptr) {
    ctarget = env->GetStringUTFChars(target, nullptr);
  }
  if (config != nullptr) {
    cconfig = env->GetByteArrayElements(config, nullptr);
    TF_SetConfig(opts, cconfig,
                 static_cast<size_t>(env->GetArrayLength(config)), status);
    if (!throwExceptionIfNotOK(env, status)) {
      env->ReleaseByteArrayElements(config, cconfig, JNI_ABORT);
      //Not release the status, opts
      return 0;
    }
  }
```
After throw exception, it look like not release the status, opts memory.

### PR DESCRIPTION
**Pull request by weberxie**
Quick fix https://github.com/tensorflow/tensorflow/issues/17698

### CODE REVIEW

File: tensorflow/java/src/main/native/session_jni.cc [hunk 1]
```diff
@@ -127,6 +127,8 @@ JNIEXPORT jlong JNICALL Java_org_tensorflow_Session_allocate2(
                  static_cast<size_t>(env->GetArrayLength(config)), status);
     if (!throwExceptionIfNotOK(env, status)) {
       env->ReleaseByteArrayElements(config, cconfig, JNI_ABORT);
+      TF_DeleteSessionOptions(opts);
+      TF_DeleteStatus(status);
```
Comment (asimshankar) [inline tensorflow/java/src/main/native/session_jni.cc]: Thanks for the fix!
I think we might also be leaking `ctarget`, perhaps we can move the block that calls `GetStringUTFChars` to fill in `ctarget` after this `if (config != nullptr)` block so that we don't leak it?

Comment (weberxie) [reply tensorflow/java/src/main/native/session_jni.cc]: Thanks for your reminder, this may be the better way. I'll update this commit.

**Review by asimshankar — APPROVED** [review]
Thanks!
