### PR TITLE
Fix:  Validate variable dtype before restoring checkpoint

### LINKED ISSUE #20487: Validate variable dtype before restoring checkpoint
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: [Yes](https://stackoverflow.com/questions/51137417/wrong-output-for-restored-variable-in-tensorflow-graph)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.0-dev20180620
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0 / 7
- **GPU model and memory**: GeForce GTX 1080 / 8 Gb
- **Exact command to reproduce**: Run the two scripts below in "Source code/logs"

### Describe the problem
A warning/error should be raised when a variable is loaded with a different dtype as that which was saved. 

In the code below, the variable `global_step` is saved as a `tf.int32`, but treated as a `tf.float32` when restored. When this happens, the `global_step` variable appears to have a value of 7e-45 instead of the expected value of 5. 

### Source code / logs
 [Link to Stackoverflow Post with the code/question](https://stackoverflow.com/questions/51137417/wrong-output-for-restored-variable-in-tensorflow-graph)

[Original post copied here]
**Script that saves the checkpoints:**

    import tensorflow as tf

    a = tf.Variable(3.0, name='a')
    b = tf.Variable(5.0, name='b')
    
    b = tf.assign_add(b, a)
    
    n_steps = 5
    
    global_step = tf.Variable(0, name='global_step', trainable=False)
    
    saver = tf.train.Saver()
    
    with tf.Session() as sess:
    
        sess.run(tf.global_variables_initializer())
        
        for step in range(n_steps):
            print(sess.run(b))
    
            global_step.assign_add(1).eval()
            print(global_step.eval())
    
            saver.save(sess, './my_test_model', global_step=global_step)

**Script that restores checkpoint:**

    import tensorflow as tf
    
    from tensorflow.python.tools.inspect_checkpoint import print_tensors_in_checkpoint_file
    
    # List ALL tensors.
    print_tensors_in_checkpoint_file(tf.train.latest_checkpoint('./'), all_tensors=True, tensor_name='')
    
    tf.reset_default_graph()
    
    a = tf.get_variable('a', shape=[])
    b = tf.get_variable('b', shape=[])
    global_step = tf.get_variable('global_step', shape=[])
    
    saver = tf.train.Saver()
    
    with tf.Session() as sess:
            
        ckpt = tf.train.latest_checkpoint('./')
        if ckpt:
            print(ckpt)
        
            saver.restore(sess, ckpt)
        
        else:
            print('Nothing restored')
        
        print(a.eval())
        print(b.eval())
        print(global_step.eval())

**Output**
```
tensor_name:  a
3.0
tensor_name:  b
20.0
tensor_name:  global_step
5
./my_test_model-5
INFO:tensorflow:Restoring parameters from ./my_test_model-5
3.0
20.0
7e-45
```

### PR DESCRIPTION
**Pull request by facaiy**
Fix #20487

### CODE REVIEW

File: tensorflow/core/kernels/save_restore_tensor.cc [hunk 1]
```diff
@@ -250,13 +250,23 @@ Status RestoreTensorsV2(OpKernelContext* context, const Tensor& prefix,
...
   for (auto i : sorted_name_idx) {
     const string& tensor_name = tensor_names_flat(i);
     const string& shape_and_slice = shape_and_slices_flat(i);
 
     TF_RETURN_IF_ERROR(
-        reader.LookupTensorShape(tensor_name, &restored_full_shape));
+        reader.LookupDtypeAndShape(tensor_name,
+                                   &original_dtype, &restored_full_shape));
+
+    // Precheck dtype.
```
Comment (drpngx) [inline tensorflow/core/kernels/save_restore_tensor.cc]: remove comment

File: tensorflow/core/kernels/save_restore_tensor.cc [hunk 2]
```diff
@@ -250,13 +250,23 @@ Status RestoreTensorsV2(OpKernelContext* context, const Tensor& prefix,
...
+    if (dtypes[i] != original_dtype) {
+      return errors::InvalidArgument(
```
Comment (drpngx) [inline tensorflow/core/kernels/save_restore_tensor.cc]: It might be more user-friendly to collect all variables that have a mismatch and then report them all.

**Review by drpngx — CHANGES_REQUESTED** [review]
Nice, thanks!

**Comment by facaiy** [comment]
Thank you for your review. Could you take a look again?

File: tensorflow/core/kernels/save_restore_tensor.cc [hunk 3]
```diff
@@ -250,6 +250,28 @@ Status RestoreTensorsV2(OpKernelContext* context, const Tensor& prefix,
...
   TensorShape restored_full_shape;
+  DataType original_dtype;
+  std::vector<string> mismatched_errors;
+  for (auto i : sorted_name_idx) {
+    const string& tensor_name = tensor_names_flat(i);
+    TF_RETURN_IF_ERROR(
+        reader.LookupDtypeAndShape(tensor_name,
+                                   &original_dtype, &restored_full_shape));
+    if (dtypes[i] != original_dtype) {
+      string error_msg = string("tensor_name = ") + tensor_name +
```
Comment (drpngx) [inline tensorflow/core/kernels/save_restore_tensor.cc]: Thanks for the change! Could you use `StrCat`? I think it'll make it easier to read.

File: tensorflow/core/kernels/save_restore_tensor.cc [hunk 4]
```diff
@@ -250,6 +250,28 @@ Status RestoreTensorsV2(OpKernelContext* context, const Tensor& prefix,
   // TODO(zongheng): consider measuring speed and issuing concurrent lookups
   // within a fixed memory budget.
   TensorShape restored_full_shape;
+  DataType original_dtype;
```
Comment (drpngx) [inline tensorflow/core/kernels/save_restore_tensor.cc]: Put that inside the loop.

File: tensorflow/core/kernels/save_restore_tensor.cc [hunk 5]
```diff
@@ -250,6 +250,28 @@ Status RestoreTensorsV2(OpKernelContext* context, const Tensor& prefix,
...
+    if (dtypes[i] != original_dtype) {
+      string error_msg = string("tensor_name = ") + tensor_name +
+                         "; expected dtype " + DataTypeString(dtypes[i]) +
+                         " does not equal original dtype " +
+                         DataTypeString(original_dtype) + '\n';
+      mismatched_errors.emplace_back(error_msg);
+    }
+  }
+  if (!mismatched_errors.empty()) {
+    string error_msg = std::accumulate(mismatched_errors.begin(),
```
Comment (drpngx) [inline tensorflow/core/kernels/save_restore_tensor.cc]: You can use `str_util::Join`. Use `const string error_msg`.

File: tensorflow/core/kernels/save_restore_tensor.cc [hunk 6]
```diff
@@ -250,6 +250,28 @@ Status RestoreTensorsV2(OpKernelContext* context, const Tensor& prefix,
   // TODO(zongheng): consider measuring speed and issuing concurrent lookups
   // within a fixed memory budget.
   TensorShape restored_full_shape;
+  DataType original_dtype;
+  std::vector<string> mismatched_errors;
+  for (auto i : sorted_name_idx) {
```
Comment (drpngx) [inline tensorflow/core/kernels/save_restore_tensor.cc]: Use `size_t` for clarity.

**Review by drpngx — CHANGES_REQUESTED** [review]
Some more minor nits

**Comment by facaiy** [comment]
Thanks. I think all comments have been resolved.

**Review by drpngx — DISMISSED** [review]
Thank you!

**Comment by facaiy** [comment]
The failures seems unrelated, right?

**Review by drpngx — APPROVED** [review]

**Comment by drpngx** [comment]
Unrelated failure, presumably (OOM in `scatter_nd_test`. Running again to check.

**Comment by facaiy** [comment]
Build failure

```
ERROR: /Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/external/gif_archive/BUILD.bazel:8:1: Couldn't build file external/gif_archive/_objs/gif/external/gif_archive/lib/dgif_lib.o: C++ compilation of rule '@gif_archive//:gif' failed: Unexpected IO error.: Running '/Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/execroot/org_tensorflow/_bin/xcode-locator 8.3.3' failed with code 1.
40
This most likely indicates that xcode version 8.3.3 is not available on the host machine.
41
Process exited with status 1
42
stdout: error: Unable to extract CFBundleShortVersionString from URL: file:///Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/external/aws/aws-cpp-sdk-sagemaker/include/aws/sagemaker
```
