### PR TITLE
Change cudnn version checking to check Major version.

### LINKED ISSUE #3225: Make cuDNN compile-time vs. load-time validation use major version only
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
```
➜ ~ ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   322936 Feb 27 11:34 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Feb 27 11:34 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Feb 27 11:34 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Feb 27 11:34 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Feb 27 11:34 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Jul  7 01:57 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.4
lrwxrwxrwx 1 root root       17 Jul  7 01:57 /usr/local/cuda/lib64/libcudnn.so.4 -> libcudnn.so.4.0.7
-rwxr-xr-x 1 root root 61453024 Jul  7 01:57 /usr/local/cuda/lib64/libcudnn.so.4.0.7
-rw-r--r-- 1 root root 62025862 Jul  7 01:57 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:

1. Pip package: `https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
➜ ~ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.9.0
```

### Steps to reproduce
1. `git clone https://github.com/soumith/convnet-benchmarks`
2. Go to `tensorflow` and run `python benchmark_googlenet.py`

### Logs
```
➜ tensorflow git:(master) python benchmark_googlenet.py
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:8a:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:8a:00.0)
E tensorflow/stream_executor/cuda/cuda_dnn.cc:346] Loaded cudnn library: 4004 but source was compiled against 4007.  If using a binary install, upgrade your cudnn library to match.  If building from sources, make sure the library loaded matches the version you specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:459] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)
[1]    18918 abort (core dumped)  python benchmark_googlenet.py
```

Notice the line: **Loaded cudnn library: 4004 but source was compiled against 4007**.  If using a binary install, upgrade your cudnn library to match.  If building from sources, make sure the library loaded matches the version you specified during compile configuration.

### PR DESCRIPTION
**Pull request by vrv**
CuDNN versions with the same major version should be ABI
compatible, which means that if we release a binary
with cudnn version 5.1, it should be compatible with
a system whose runtime loads version 5.0.  This check
would trigger if the cudnn version loaded at runtime is
5 but the compile-time version used was 4.

This change is based off of recommendations from
https://github.com/tensorflow/tensorflow/issues/2525#issuecomment-223523008.

Fixes #3225.

### CODE REVIEW

**Comment by vrv** [comment]
Just FYI to @3XX0 who suggested this and @zer0n who ran into this.

(my GPU machine is off so this is untested at the moment, using our CI to 'test' ;)

File: tensorflow/stream_executor/cuda/cuda_dnn.cc [hunk 1]
```diff
@@ -334,15 +342,18 @@ port::Status CudnnSupport::Init() {
     // Check whether loaded version of CuDNN matches what the source
     // was built with.
     size_t loaded_version = dynload::cudnnGetVersion();
-    bool library_loaded_matches_source = (loaded_version == CUDNN_VERSION);
+    size_t loaded_major_version = cudnnMajorVersion(loaded_version);
+    bool library_loaded_matches_source =
+        (loaded_major_version == cudnnMajorVersion(CUDNN_VERSION));
```
Comment (zheng-xq) [inline tensorflow/stream_executor/cuda/cuda_dnn.cc]: I am not entirely sure it is safe to check only the major version. cudnn versions have three parts: major, minor and patch level. Only the last part can be safely ignored for ABI compatibility.

Comment (vrv) [inline tensorflow/stream_executor/cuda/cuda_dnn.cc]: So if I divide by CUDNN_VERSION by 100 instead of 1000 and rename to cudnnCompatibilityVersion, would that be sufficient?

Comment (zheng-xq) [inline tensorflow/stream_executor/cuda/cuda_dnn.cc]: I would do "version / 100 * 100" and call it "compatibility version". That
way, it is still similar to the original version in terms of scale.

Comment (vrv) [inline tensorflow/stream_executor/cuda/cuda_dnn.cc]: Done.

**Comment by zheng-xq** [comment]
LGTM
