### PR TITLE
Fix compilation failure with RDMA+GDR

### LINKED ISSUE #21696: TensorFlow GDR RDMA verbs compilation failure on 1.10
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux 7.4.1708
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.16.1
- **GCC/Compiler version (if compiling from source)**: 7.2.0
- **CUDA/cuDNN version**: 9.2.1.88
- **GPU model and memory**: nVidia Volta V100 16GB
- **Exact command to reproduce**: bazel build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem

I attempted to compile TensorFlow 1.10.0 using RDMA/VERBS options+GDR options as I'm using an all infiniband EDR network with my Volta V100 HPC environment. The same compile-time strings for Bazel build worked correctly without this error in RC 1.0.8rc1 and this error was not thrown. I am using mvpachi2 + GNU GCC 7.2.0, CUDA 9.2.8.11 + Basel 0.16.0 at compile time. NCCL is at v 2.2.13. The error basel throws after 16xxx objects is as follows:
                                                                                                                                      ^
```
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-self-assign'
ERROR: /opt/ohpc/pub/apps/tensorflow_1.10/tensorflow/BUILD:576:1: Executing genrule //tensorflow:tensorflow_python_api_gen failed (Aborted): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
2018-08-18 16:25:22.109083: F tensorflow/core/framework/allocator_registry.cc:52] New registration for AllocatorFactory with name=BFCRdmaAllocator priority=101 at location tensorflow/contrib/gdr/gdr_memory_manager.cc:204 conflicts with previous registration at location tensorflow/contrib/verbs/rdma_mgr.cc:277

INFO: Elapsed time: 934.788s, Critical Path: 236.40s
INFO: 13405 processes: 13405 local.
FAILED: Build did NOT complete successfully

```

### Source code / logs
The above is about all I've gotten out of it, thus far. There is no obvious compile time log output from Basel-build that I can see of use.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #21696 where
tensorflow failed to compile when both RDMA and GDR are on.
The issue is that the memory allocator of GDR used the same
name as RDMA.

This fix fixes #21696.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: tensorflow/contrib/gdr/gdr_memory_manager.cc [hunk 1]
```diff
@@ -186,22 +186,22 @@ class GdrMemoryManager : public RemoteMemoryManager {
...
-  Allocator* CreateAllocator() override { return new BFCRdmaAllocator; }
+  Allocator* CreateAllocator() override { return new BFCGdrAllocator; }
 
   virtual SubAllocator* CreateSubAllocator(int numa_node) {
     return new BasicCPUAllocator(numa_node);
   }
 };
 
-REGISTER_MEM_ALLOCATOR("BFCRdmaAllocator", 101, BFCRdmaAllocatorFactory);
+REGISTER_MEM_ALLOCATOR("BFCGdrAllocator", 101, BFCGdrAllocatorFactory);
```
Comment (poxvoculi) [inline tensorflow/contrib/gdr/gdr_memory_manager.cc]: If both verbs and gdr are specified, which is to take precedence?  It should have a higher priority here.

**Comment by poxvoculi** [comment]
@byronyi: thoughts?

File: tensorflow/contrib/gdr/gdr_memory_manager.cc (hunk 1 above)
Comment (byronyi) [reply tensorflow/contrib/gdr/gdr_memory_manager.cc]: Since both classes are just workarounds of non-visitable default cpu_allocator, I guess it does not matter as long as one of them is in effect. We could get rid of them once the default allocator is visitable.

**Comment by byronyi** [comment]
@yongtang @poxvoculi LGTM

**Review by poxvoculi — APPROVED** [review]

**Review by poxvoculi — APPROVED** [review]
