### PR TITLE
Fix overflow/crash in tf.range when limits is large

### LINKED ISSUE #46913: tf.keras.layers.RepeatVector crashes(aborts) when n is large
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.keras.layers.RepeatVector` crashes(aborts) when `n` is large

**Describe the expected behavior**
expect an exception message if the input unexpected instead of crash. 

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.keras.layers.RepeatVector(n=9223372036854775807)(np.ones((3, 1)))
~~~

Output:
~~~python
2021-02-04 04:42:07.262027: F tensorflow/core/framework/tensor_shape.cc:353] Check failed: 0 <= new_num_elements (0 vs. -1)
Aborted (core dumped)
~~~

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to address the issue raised in #46913 where
tf.range (and implicitly tf.keras.layers.RepeatVector)
will overflow/crash when limits is large.

The reason of the overflow is that while calculating
the size within the kernel, the conditional statements
comes with `int64 = cond ? int64 : double` will implicitly
convert to double first and then cast back to int64, causing
the overflow and crash.

This PR fixes the issue by casting to int64 in both selections
within the conditional statements first.

This PR fixes #46913.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: tensorflow/core/kernels/sequence_ops.cc [hunk 1]
```diff
@@ -72,9 +72,11 @@ class RangeOp : public OpKernel {
...
     }
     int64_t size = (std::is_integral<T>::value
-                        ? ((std::abs(limit - start) + std::abs(delta) - 1) /
-                           std::abs(delta))
-                        : std::ceil(std::abs((limit - start) / delta)));
+                        ? static_cast<int64>(
+                            (std::abs(limit - start) + std::abs(delta) - 1) /
+                              std::abs(delta))
+                        : static_cast<int64>(
+                            std::ceil(std::abs((limit - start) / delta))));
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/sequence_ops.cc:79]: Let's separate each branch to a separate expression to ease in readability.

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]

**Comment by yongtang** [comment]
Thanks @mihaimaruseac . The PR has been updated.

**Review by mihaimaruseac — APPROVED** [review]
