### PR TITLE
Dataset concatenate -  replace AddDim with AddDimWithStatus

### LINKED ISSUE #58290: `tf.data.experimental.CsvDataset` cause IOT instruction crash
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10, tf-nightly

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current Behaviour?

```shell
Applying shuffle+repeat+batch on `tf.data.experimental.CsvDataset` causes check failed and IOT instruction (core dumped) crashes.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

# The following code is from https://www.tensorflow.org/api_docs/python/tf/data/experimental/CsvDataset
with open('/tmp/my_file0.csv', 'w') as f:
  f.write('abcdefg,4.28E10,5.55E6,12\n')
  f.write('hijklmn,-5.3E14,,2\n')
dataset = tf.data.experimental.CsvDataset(
  "/tmp/my_file0.csv",
  [tf.float32,  # Required field, use dtype or empty tensor
   tf.constant([0.0], dtype=tf.float32),  # Optional field, default to 0.0
   tf.int32,  # Required field, use dtype or empty tensor
  ],
  select_cols=[1,2,3]  # Only parse last three columns
)

# The following operation is causing Check Fail
for e in range(10):
    dataset = dataset.shuffle(1000).repeat().batch(512)
```

### Relevant log output

```shell
F tensorflow/core/framework/tensor_shape.cc:404] Check failed: 0 <= new_num_elements (0 vs. -9223372036854775808)
IOT instruction (core dumped)
```
</details>

### PR DESCRIPTION
**Pull request by bhack**
Fixes: https://github.com/tensorflow/tensorflow/issues/58290

### CODE REVIEW

File: tensorflow/core/kernels/data/concatenate_dataset_op.cc [hunk 1]
```diff
@@ -51,9 +51,11 @@ class ConcatenateDatasetOp::Dataset : public DatasetBase {
 
     auto os_input = input->output_shapes();
     auto os_concatenate = to_concatenate->output_shapes();
+    PartialTensorShape output_tensorshape({});
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/data/concatenate_dataset_op.cc:54]: Just needs to move inside the for loop, otherwise every new iteration would start from the result of the previous one

Comment (bhack) [reply tensorflow/core/kernels/data/concatenate_dataset_op.cc]: Yes I had it locally.. now pushed

**Comment by bhack** [comment]
Thanks, now we are aligned more or less with my first impl. 
Without compiling I was confused by the conditional initialization we already had in master:

https://github.com/tensorflow/tensorflow/blob/03fe5eb323e987facea6bd0767e1880a619d5ac2/tensorflow/core/kernels/data/concatenate_dataset_op.cc#L242-L244

But it was already useless in master as the constructors are the same:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor_shape.h#L532

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by bhack** [comment]
Let me know if we need to rebase it or to extend with a test before merge...

**Comment by mihaimaruseac** [comment]
A test would be great. Thanks

**Comment by bhack** [comment]
> A test would be great. Thanks

At what level? Concatenate? Or more e2e like batch as the original ticket?

**Comment by mihaimaruseac** [comment]
Either should be ok.

**Comment by bhack** [comment]
There is an error on copybara

**Comment by bhack** [comment]
@gbaned Do you have access to the copybara log?

**Comment by bhack** [comment]
@gbaned Can you see the log?

**Comment by gbaned** [comment]
> @gbaned Can you see the log?

Hi @bhack I can't see the log, I have re-triggered the checks and I will keep you posted if I can see. Thank you.

**Comment by mihaimaruseac** [comment]
I did a manual import.

**Comment by mihaimaruseac** [comment]
Actually, the automated import succeeded too, this time

**Comment by bhack** [comment]
Thanks
