### PR TITLE
Fix tf.tile crash when n is large

### LINKED ISSUE #46911: tf.keras.backend.tile crash(aborts) when n is large
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.keras.backend.tile` crash(aborts) when `n` is large

**Describe the expected behavior**
expect an exception message if the input unexpected instead of crash. 

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.keras.backend.tile(x=np.ones((1,1,1)), n=[100000000,100000000, 100000000])
~~~
Output
~~~python
2021-02-04 04:10:34.072054: F tensorflow/core/framework/tensor_shape.cc:353] Check failed: 0 <= new_num_elements (0 vs. -1)
Aborted (core dumped)
~~~

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to fix the issue raised in #46911 where tf.tile
will crash when n is large. This PR add additional check
to make sure an error message is rendered (instead of crash).

This PR fixes #46911.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: tensorflow/core/kernels/tile_ops.cc [hunk 1]
```diff
@@ -188,6 +189,18 @@ class TileOp : public OpKernel {
...
+        for (int ii = 0; ii < input_dims; ++ii) {
+          if (ii != 0) {
+            strings::StrAppend(&msg, ", ");
+          }
+          strings::StrAppend(&msg, multiples_array[ii]);
+        }
+        OP_REQUIRES(context, false, errors::InvalidArgument(
+            "Shape [", msg, "] has too many elements"));
+      }
       output_shape.AddDim(input.dim_size(i) * multiples_array[i]);
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/tile_ops.cc:204]: Let's instead change this to use [`AddDimWithStatus`](https://github.com/tensorflow/tensorflow/blob/51d911b4661b290f0e207fc7cf1ec79b9e411a58/tensorflow/core/framework/tensor_shape.h#L208-L210) and wrap that in `OP_REQUIRES_OK`.

Also, if we want to display a shape in an error message, `shape.DebugString()` is the best API to use.

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]

**Comment by yongtang** [comment]
Thanks @mihaimaruseac. The PR has been updated. Please take a look.

**Review by mihaimaruseac — APPROVED** [review]

**Review by gbaned — APPROVED** [review]
