### PR TITLE
Fix random crashes in SessionRun()

### LINKED ISSUE #13129: random crashes while serving multiple frozen models in parallel using go api
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

Yes, I have written custom code

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Linux x86_64 SLES12

- **TensorFlow installed from (source or binary)**:

Source, latest master at the moment

- **TensorFlow version (use command below)**:

('v1.3.0-rc1-2265-g6e7539b', '1.4.0-dev')
I also tried r1.3 with similar result.

- **Python version**: 

Python 2.7.9

- **Bazel version (if compiling from source)**:

Build label: 0.5.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Aug 25 10:00:00 2017 (1503655200)
Build timestamp: 1503655200
Build timestamp as int: 1503655200

- **CUDA/cuDNN version**:

Not used.

- **GPU model and memory**:

Not used.

- **Exact command to reproduce**:

$ ./tfcrash --n_models 16 --n_images 100

An output of this program can be different. The bug has random nature. In some cases the process just segfaults. Typical output is:

$ ./tfcrash --n_models 16 --n_images 100
2017/09/18 16:45:43 setting 8 cpu
2017/09/18 16:45:43 launching 16 models
2017/09/18 16:45:43 feeding 100 images
2017/09/18 16:45:43 waiting
2017/09/18 16:45:51 session.Run() failed: Expects arg[0] to be uint8 but INVALID is provided

Or:

$ ./tfcrash 
2017/09/18 16:57:54 setting 8 cpu
2017/09/18 16:57:54 launching 16 models
2017/09/18 16:57:54 feeding 100 images
2017/09/18 16:57:54 waiting
Segmentation fault (core dumped)

### Describe the problem

I'm trying to serve predictions from multiple frozen models that I have trained and generated previously using python script. My programming language for serving predictions is golang. I have found that sometimes my process crashes randomly. Exact conditions needed to reproduce this behaviour are unknown. It is also unknown if this bug related to golang bindings or tensorflow itself.
I also tried different builds of tensorflow, all of them are affected so far, including one built with cuda support. I also noticed that setting lower numbers for --n_images and --n_models parameters decreases probability of bug reproduction. In my experience setting --n_models to 16 and up gives 100% probability of crash.

I tried both go-1.8.3 and go-1.9 with similar result.

### Source code / logs

I wrote a short program (less than 100 lines in go) which is able to reproduce crash with >90% probability:
https://gist.github.com/a33c892b17d9ec1da1e40e4fb68fdcf9

The model file (type: .frozen.pb, size: 34Mb): https://drive.google.com/file/d/0B9jZHp3Hh0s2MnAxekRGYlVTVHM/

### PR DESCRIPTION
**Pull request by anight**
This patch fixes https://github.com/tensorflow/tensorflow/issues/13129

The problem was with usage of runtime.SetFinalizer() in golang bindings. When a variable become unreferenced GC can harvest it any moment after. According to this https://tip.golang.org/pkg/runtime/#SetFinalizer:

> For example, if p points to a struct that contains a file descriptor d, and p has a finalizer that closes that file descriptor, and if the last use of p in a function is a call to syscall.Write(p.d, buf, size), then p may be unreachable as soon as the program enters syscall.Write. The finalizer may run at that moment, closing p.d, causing syscall.Write to fail because it is writing to a closed file descriptor (or, worse, to an entirely different file descriptor opened by a different goroutine). To avoid this problem, call runtime.KeepAlive(p) after the call to syscall.Write.

In our case unreferenced variable was "feeds", i.e. input tensors. After investigations I have found out that func (t *Tensor) finalize() { C.TF_DeleteTensor(t.c) } was called a way before SessionRun() was finished and that was the cause of crash in my case.

### CODE REVIEW

File: tensorflow/go/session.go [hunk 1]
```diff
@@ -89,6 +89,10 @@ func (s *Session) Run(feeds map[Output]*Tensor, fetches []Output, targets []*Ope
 		ptrOutput(c.fetches), ptrTensor(c.fetchTensors), C.int(len(fetches)),
 		ptrOperation(c.targets), C.int(len(targets)),
 		nil, status.c)
+
+	// Make sure GC won't harvest input tensors until SessionRun() is finished
+	runtime.KeepAlive(feeds)
```
Comment (asimshankar) [inline tensorflow/go/session.go]: Going by the documentation on `SetFinalizer` you pointed out, perhaps this should be:

```
runtime.KeepAlive(c)
```

Probably achieves the same effect, but seems more future proof if `c` is enhanced in the future?

Comment (asimshankar) [inline tensorflow/go/session.go]: Translating the documentation on `SetFinalizer` you linked to, shouldn't this be `runtime.KeepAlive(c)` instead?

Comment (anight) [reply tensorflow/go/session.go]: This does not seem right because "c" has no references to "feeds" either.
I have just checked with runtime.KeepAlive(c) and it keeps crashing, as expected.

Comment (asimshankar) [reply tensorflow/go/session.go]: Or is it that individual fields of `c` are being independently GCed?

Comment (asimshankar) [reply tensorflow/go/session.go]: Ah, sorry, yeah, you're right - I was not needing the `feeds` vs. `c.feeds` correctly.
Thanks very much!

**Review by asimshankar — COMMENTED** [review]
Thanks for the fix!

**Review by asimshankar — APPROVED** [review]

**Comment by asimshankar** [comment]
Jenkins, test this please

File: tensorflow/go/session.go (hunk 1 above)
Comment (anight) [reply tensorflow/go/session.go]: That is because "c.feeds" does not reference "feeds". Instead it references t.c, which is different object for GC unrelated to "feeds" in general.

Comment (asimshankar) [reply tensorflow/go/session.go]: It may make sense to also call `runtime.KeepAlive(targets)` and `runtime.KeepAlive(fetches)`?

Comment (asimshankar) [reply tensorflow/go/session.go]: Would it also make sense to call `runtime.KeepAlive(fetches)` and `runtime.KeepAlive(targets)`?

Comment (anight) [reply tensorflow/go/session.go]: For Operation object there is no finalizer destructor defined, so that means op.c could only point to some constant node of a graph (have not checked this though). In that case Operation object can be harvested by GC independently from it's ".c" part and without any side effects.

**Review by asimshankar — APPROVED** [review]

**Comment by asimshankar** [comment]
Jenkins, test this please

**Comment by caisq** [comment]
The test failures are unrelated. Merging the PR.
