### PR TITLE
CMSIS-NN: Fix incorrect flags for non-DSP/MVE processors

### LINKED ISSUE #42951: CMSIS-NN: Incorrect flags for non-DSP/MVE processors (convolution op only)
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): 5a16264ba6f12883726d12d484d4cd61405ddab7
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arm internal testing using models for Cortex-M3

**Describe the problem**
CalculateOpData() in cmsis-nn/conv.cc is inside a '#if defined(__ARM_FEATURE_DSP) || defined(__ARM_FEATURE_MVE)' flag which is not set for a Cortex-M3 or similar that do not have DSP or MVE extensions. This results in uninitialized quantization parameters being passed on to the convolution API in the Eval() procedure. This could result in an assert in debug builds or atleast an incorrect output from convolution.

**Please provide the exact sequence of commands/steps when you ran into the problem** 
Just a visual code check.

### PR DESCRIPTION
**Pull request by felix-johnny**
Fixes #42951

CalculateOpData() was not invoked for target Arm Cortex-M
processors without DSP or MVE extension like Cortex-M3 or Cortex-M0.

The fix is to remove the usage of feature flags __ARM_FEATURE_DSP
and __ARM_FEATURE_MVE and replace them with an appropriate
'if' condition where applicable. It is also part of the general
work to move the processor feature flags completely to CMSIS-NN.

Two reinterpret_casts are replaced with static casts along the
area where the feature flag change is done.

### CODE REVIEW

File: tensorflow/lite/micro/kernels/cmsis-nn/conv.cc [hunk 1]
```diff
@@ -240,126 +239,119 @@ TfLiteStatus EvalQuantizedPerChannel(
...
+    // the parameters passed
+    TFLITE_DCHECK_EQ(
+        arm_convolve_wrapper_s8(
+            &ctx, &conv_params, &quant_params, &input_dims,
+            tflite::micro::GetTensorData<int8_t>(input), &filter_dims,
+            tflite::micro::GetTensorData<int8_t>(filter), &bias_dims,
+            tflite::micro::GetTensorData<int32_t>(bias), &output_dims,
+            tflite::micro::GetTensorData<int8_t>(output)),
+        ARM_MATH_SUCCESS);
   } else {
```
Comment (freddan80) [inline tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:332]: Removing the macro will slightly increase the mem footprint for this CMSIS-NN kernel. But since dilation support will be available soon, this is only a temporary issue.

**Review by freddan80 — COMMENTED** [review]
Looks good to me!

**Review by freddan80 — DISMISSED** [review]

File: tensorflow/lite/micro/kernels/cmsis-nn/conv.cc [hunk 2]
```diff
@@ -240,126 +239,119 @@ TfLiteStatus EvalQuantizedPerChannel(
...
-      &ctx, &conv_params, &quant_params, &input_dims,
-      tflite::micro::GetTensorData<int8_t>(input), &filter_dims,
-      tflite::micro::GetTensorData<int8_t>(filter), &bias_dims,
-      tflite::micro::GetTensorData<int32_t>(bias), &output_dims,
-      tflite::micro::GetTensorData<int8_t>(output));
-
-  if (status == ARM_MATH_SUCCESS) {
-    return kTfLiteOk;
+  // Call to reference implementation can be removed when dilation is supported
+  // in the optimized implementations.
```
Comment (advaitjain) [inline tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:246]: let's move this comment close to where the reference implementation is being used. Feels a bit out of place here.

File: tensorflow/lite/micro/kernels/cmsis-nn/conv.cc [hunk 3]
```diff
@@ -240,126 +239,119 @@ TfLiteStatus EvalQuantizedPerChannel(
...
+  if (1 == conv_params.dilation.h && 1 == conv_params.dilation.w) {
```
Comment (advaitjain) [inline tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:247]: in google code, we avoid using yoda-style comparisons. Would be great if the cmsis kernels could follow that convention too.

```cc
if (conv_params.dilation.h == 1 && conv_params.dilation.w == 1)
```

File: tensorflow/lite/micro/kernels/cmsis-nn/conv.cc (hunk 1 above)
Comment (advaitjain) [reply tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:332]: can we make a github issue for supporting dilation in the cmsis kernels? and add a TODO(#link to issue): remove calls to reference kernels once dilation is supported with optimized code.

**Review by advaitjain — CHANGES_REQUESTED** [review]
Thanks, only minor comments.

File: tensorflow/lite/micro/kernels/cmsis-nn/conv.cc (hunk 2 above)
Comment (felix-johnny) [reply tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:246]: I'll remove this comment and replace it with the TODO instead.

**Review by advaitjain — APPROVED** [review]
In the future, please merge upstream/master instead of rebasing.

Rebase changes the commit history which prevents the pull request reviewer from seeing changes since the last review, which makes incremental reviews hard.

**Comment by felix-johnny** [comment]
@advaitjain It was a merge commit and not a rebase that was done. But, for some reason, I couldn't push it and got a reject from the server. Hence the force push. I guess, at the end of the day it might as well as have been a rebase because the history is lost because of the force push. Will contact the team next time I encounter this for a better resolution.

File: tensorflow/lite/micro/kernels/cmsis-nn/conv.cc [hunk 4]
```diff
@@ -240,128 +239,122 @@ TfLiteStatus EvalQuantizedPerChannel(
...
-  arm_status status = arm_convolve_wrapper_s8(
-      &ctx, &conv_params, &quant_params, &input_dims,
-      tflite::micro::GetTensorData<int8_t>(input), &filter_dims,
-      tflite::micro::GetTensorData<int8_t>(filter), &bias_dims,
-      tflite::micro::GetTensorData<int32_t>(bias), &output_dims,
-      tflite::micro::GetTensorData<int8_t>(output));
-
-  if (status == ARM_MATH_SUCCESS) {
-    return kTfLiteOk;
+  // TODO(#43557) Remove checks for dilation and call to reference
```
Comment (rthadur) [inline tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:245]: @felix-johnny can you please remove TODO , this is blocking internal checks

**Review by rthadur — CHANGES_REQUESTED** [review]

File: tensorflow/lite/micro/kernels/cmsis-nn/conv.cc (hunk 4 above)
Comment (advaitjain) [reply tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:245]: > @felix-johnny can you please remove TODO , this is blocking internal checks

I'll take care of this. The todo is useful and I'll modify the internal checks to accept todos in this format as well.

Comment (rthadur) [reply tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:245]: I have done this internally to accept todos.
