### PR TITLE
Fixing decode_raw_op for complex numbers on big endian

### LINKED ISSUE #33496: //tensorflow/python/kernel_tests:decode_raw_op_test fails with Assertion error
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 19.04 s390x
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.0.0
- Python version: 2.7.16
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
The above test fails with the output array mismatch in [testToComplex64](https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/python/kernel_tests/decode_raw_op_test.py#L105) and [testToComplex128](https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/python/kernel_tests/decode_raw_op_test.py#L118).

The cause of failure seems to be in the byte swapping code to solve endianness problem [here](https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/core/kernels/decode_raw_op.cc#L88). The code doesn't seem to work as intentioned for **complex data**.

**Describe the expected behavior**
The test should pass on s390x.

**Code to reproduce the issue**
```
bazel test //tensorflow/python/kernel_tests:decode_raw_op_test
```

**Other info / logs**
```
AssertionError:
Arrays are not equal

not equal where = (array([0, 0]), array([1, 2]))
not equal lhs = [[ 2.-2.j -3.+3.j]]
not equal rhs = [-2.+2.j  3.-3.j]
Mismatch: 0%
Max absolute difference: 8.48528137
Max relative difference: 2.
 x: matrix([[ 1.+1.j,  2.-2.j, -3.+3.j, -4.-4.j]])
 y: array([[ 1.+1.j, -2.+2.j,  3.-3.j, -4.-4.j]])

======================================================================
FAIL: testToComplex64 (__main__.DecodeRawOpTest)
testToComplex64 (__main__.DecodeRawOpTest)
----------------------------------------------------------------------
AssertionError:
Arrays are not equal

not equal where = (array([0, 0]), array([1, 2]))
not equal lhs = [[ 2.-2.j -3.+3.j]]
not equal rhs = [-2.+2.j  3.-3.j]
Mismatch: 0%
Max absolute difference: 8.485281
Max relative difference: 2.
 x: matrix([[ 1.+1.j,  2.-2.j, -3.+3.j, -4.-4.j]], dtype=complex64)
 y: array([[ 1.+1.j, -2.+2.j,  3.-3.j, -4.-4.j]], dtype=complex64)

----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by namrata-ibm**
The //tensorflow/python/kernel_tests:decode_raw_op_test fails as the current code for handling reversal of byte ordering of elements on big endian does not handle complex numbers correctly.
Fixes #33496

### CODE REVIEW

**Comment by namrata-ibm** [comment]
@jhseu , Could you please check?

File: tensorflow/core/kernels/decode_raw_op.cc [hunk 1]
```diff
@@ -87,14 +87,21 @@ class DecodeRawOp : public OpKernel {
     } else {
       // Otherwise, the data is not in the host's byte order, and rather than a
       // direct copy, we need to reverse the byte ordering of each element.
+      int64 element_size;
+      if (DataTypeString(out_type_) == "complex64" || DataTypeString(out_type_) == "complex128") {
```
Comment (jaingaurav) [inline tensorflow/core/kernels/decode_raw_op.cc]: Can you change the test to `(out_type_ == DT_COMPLEX64) || (out_type_ == DT_COMPLEX128)` in order to avoid the string conversion?

**Review by jaingaurav — CHANGES_REQUESTED** [review]
Would it be possible to add a test pls?

File: tensorflow/core/kernels/decode_raw_op.cc (hunk 1 above)
Comment (namrata-ibm) [reply tensorflow/core/kernels/decode_raw_op.cc]: Corrected, Thank you!

**Comment by jaingaurav** [comment]
Thanks @namrata-ibm! Could you please extend DecodeRawOpTest.testEndianness in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/decode_raw_op_test.py to include tests for complex values so that we can ensure your code is tested? Note I have recently cleaned up the file to be more 2.0 friendly.

**Comment by gbaned** [comment]
@namrata-ibm Could you please check reviewer comments and keep us posted. Thanks!

**Comment by namrata-ibm** [comment]
Apologies for delay in reply!
@jaingaurav Is it ok to add a change as below:
```diff  
  def testEndianness(self):
    self.assertAllEqual(
        [[0x04030201]],
        parsing_ops.decode_raw(
            ["\x01\x02\x03\x04"], dtypes.int32, little_endian=True))
    self.assertAllEqual(
        [[0x01020304]],
        parsing_ops.decode_raw(
            ["\x01\x02\x03\x04"], dtypes.int32, little_endian=False))
+    self.assertAllEqual(
+        [[1+2j]],
+        parsing_ops.decode_raw(
+            [b'\x00\x00\x80?\x00\x00\x00@'], dtypes.complex64, little_endian=True))
+    self.assertAllEqual(
+        [[1+2j]],
+        parsing_ops.decode_raw(
+            [b'?\x80\x00\x00@\x00\x00\x00'], dtypes.complex64, little_endian=False))

```
This verifies that input data representing a complex number "1+2j" needs swap midway(4 bytes each) for correctly identifying the real and imaginary data instead of full data reversal(8 bytes for complex64). This test passes on both x86_64 and s390x.

**Comment by jaingaurav** [comment]
@namrata-ibm: Yes, that looks perfect.

**Review by jaingaurav — DISMISSED** [review]

**Comment by gbaned** [comment]
@namrata-ibm Could you please address Ubuntu Sanity errors? Thanks!

**Review by jaingaurav — APPROVED** [review]

**Comment by jaingaurav** [comment]
Thanks for the fix @namrata-ibm!
