### PR TITLE
Properly handle CUDA stream setting in GpuCudaMallocAsyncAllocator

### LINKED ISSUE #56134: GpuCudaMallocAsyncAllocator fails if the same GPU device is initialised multiple times
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.7.1

### Custom Code

No

### OS Platform and Distribution

_No response_

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

CUDA 11.2, cuDNN 8.1.1

### GPU model and memory

NVIDIA GTX 1080

### Current Behaviour?

When [https://github.com/tensorflow/tensorflow/blob/v2.7.1/tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc#L391](GpuCudaMallocAsyncAllocator) is used instead of the default one (either via environment variable or config setting), and the same GPU device is initialised more than once (e.g. if there are multiple TensorFlow sessions within a single process) it fails with the ["Trying to set the stream twice. This isn't supported."](https://github.com/tensorflow/tensorflow/blob/v2.7.1/tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc#L391) error.

Apparently this is happening because the `GpuCudaMallocAsyncAllocator` is global and its `cuda_stream_` field is filled on the first `SetStreamAndPreallocateMemory`. I was able to fix this by making some changes in the code, and I am going to submit a PR containing those.

### Standalone code to reproduce the issue

```cpp
#include <tensorflow/core/public/session.h>

tensorflow::GraphDef graph_def2;

auto options = tensorflow::SessionOptions();
options.config.mutable_gpu_options()->mutable_experimental()->set_use_cuda_malloc_async(true);

tensorflow::GraphDef graph_def1;
// Load graph_def1
tensorflow::Session* session1 = nullptr;
tensorflow::NewSession(options, &session1);
session1->Create(graph_def1);

tensorflow::GraphDef graph_def2;
// Load graph_def2
tensorflow::Session* session2 = nullptr;
tensorflow::NewSession(options, &session2);
session2->Create(graph_def2);
```

### Relevant log output

```shell
2022-05-17 14:17:05.253418: I tensorflow/core/common_runtime/gpu/gpu_process_state.cc:214] Using CUDA malloc Async allocator for GPU: 0
2022-05-17 14:17:05.253515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7234 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1
2022-05-17 14:17:05.422828: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7234 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1
2022-05-17 14:17:05.423011: F tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:390] Trying to set the stream twice. This isn't supported.
```
</details>

### PR DESCRIPTION
**Pull request by dev0x13**
Fix #56134.
Since each physical GPU device has a single compute CUDA stream and [GpuCudaMallocAsyncAllocator always uses the device's compute stream](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/gpu_device.cc#L1553) we can can bypass the repeated CUDA stream setting without throwing an error.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @rohan100jain Can you please review this PR ? Thank you!

**Comment by dev0x13** [comment]
@rohan100jain @gbaned Are there any changes that this MR will be reviewed?

**Comment by gbaned** [comment]
Hi @rohan100jain Can you please review this PR ? Thank you!

File: tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc [hunk 1]
```diff
@@ -386,7 +386,9 @@ bool GpuCudaMallocAsyncAllocator::ClearStats() {
 
 void GpuCudaMallocAsyncAllocator::SetStreamAndPreallocateMemory(void* stream) {
 #if TF_CUDA_MALLOC_ASYNC_SUPPORTED
-  if (cuda_stream_ != nullptr) {
+  CUstream new_cuda_stream = *(reinterpret_cast<CUstream*>(stream));
```
Comment (cantonios) [inline tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:389]: Prefer `static_cast`, it is well-defined here.

**Review by cantonios — CHANGES_REQUESTED** [review]

File: tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc (hunk 1 above)
Comment (dev0x13) [reply tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc]: Fixed, thanks

**Review by cantonios — APPROVED** [review]
