### PR TITLE
[Crash fix] Fix cudaMallocAsync crashes.

### LINKED ISSUE #48869: Flag TF_GPU_ALLOCATOR=cuda_malloc_async ( to work with large tensors),  results in: " Error in py_call_impl(callable, dots$args, dots$keywords) :    InternalError: No allocator statistics "
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): my code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10/Rstudio
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): "v2.5.0-rc0-36-g0d1805aede0"
- Python version: 3.7.3

- CUDA/cuDNN version: 11.2.1
- GPU model and memory: 3070/8G

**Describe the current behavior**
To work with large files, like 3GB, it returns an error asking for setting that flag. 
The flat set, TF_GPU_ALLOCATOR=cuda_malloc_async , it can handle the
object fine, but tensorflow no longer is able to run training, or load
saved models, even from keras.applications

**Describe the expected behavior**
Load models without any error

**Standalone code to reproduce the issue**
on rstudio, but i belive would be the same on python 

a<- application_densenet121(input_shape = c(256,256,3), include_top = F)

2021-05-02 07:59:46.375811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3070 computeCapability: 8.6
coreClock: 1.815GHz coreCount: 46 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2021-05-02 07:59:46.376160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-05-02 07:59:46.376323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-02 07:59:46.376479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-05-02 07:59:46.376581: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InternalError: No allocator statistics 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

This error, " Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InternalError: No allocator statistics "
happens in many other circunstancies, loading saved model, or even to run any model.

happend on tf 2.5.0-rc1/ 2.5.0-rc2/2.4.1. If disable the flag, the error doesnt happen, but 
tensorflow cant handle larger tensors, like images over 2GB.

### PR DESCRIPTION
**Pull request by nouiz**
The first commit fixes #48869. The second commit fixes another follow up crashes when using TF_GPU_ALLOCATOR=cuda_malloc_async.

The 2 fixes are:
- The Allocator API have the statistics optional. But the function [BaseGPUDeviceFactory::CreateGPUDevice()](https://github.com/tensorflow/tensorflow/blob/aa08697dcb98135ee39ba00ee08b5c1a28cfde61/tensorflow/core/common_runtime/gpu/gpu_device.cc#L1403) check that they are available.
- Bad handling of the ptr to the compute stream. It is a ptr to the compute stream that is passed, not the compute stream itself.
@sanjoy @chsigg

### CODE REVIEW

File: tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h [hunk 1]
```diff
@@ -85,7 +85,7 @@ class GpuCudaMallocAsyncAllocator : public Allocator {
 
   void SetStream(void* stream) override {
 #if TF_CUDA_MALLOC_ASYNC_SUPPORTED
-    cuda_stream_ = reinterpret_cast<CUstream>(stream);
+    cuda_stream_ = *(reinterpret_cast<CUstream*>(stream));
```
Comment (sanjoy) [inline tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h:88]: I did not notice this earlier, but a setter for an immutable property seems like a code smell to me.  Have you tried passing in the stream via the constructor somehow?

(Does not need to be addressed in this PR.)

**Review by sanjoy — CHANGES_REQUESTED** [review]
Can you please update the PR description to state what the bug was and how this PR fixes it?

File: tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h (hunk 1 above)
Comment (nouiz) [reply tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h:88]: Mostly, the GpuDevice need the gpu_allocator. But the gpu_allocator need the stream created by the GpuDevice.
Fixing this would request a refactoring that will break existing API and I wasn't sure if those API was part of the public API or not. As I wanted this to get in TF2.5, I prefered to stay away from this refactoring.
Relevant code:
https://github.com/tensorflow/tensorflow/blob/aa08697dcb98135ee39ba00ee08b5c1a28cfde61/tensorflow/core/common_runtime/gpu/gpu_device.cc#L1414-L1422

(I also updated the PR description)
(I amended the test commit to remove a commented left over line)

**Review by sanjoy — APPROVED** [review]

**Review by gbaned — APPROVED** [review]

**Comment by nouiz** [comment]
I updated this PR. Now the new configuration options is experimental.
I added what got lost in my rebase the use of that new configuration option.
I also updated the test to verify that the right allocator got used. If you have another idea how to do this, tell me.

File: tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h [hunk 2]
```diff
@@ -106,6 +110,10 @@ class GpuCudaMallocAsyncAllocator : public Allocator {
   CUmemoryPool pool_;
 #endif  // TF_CUDA_MALLOC_ASYNC_SUPPORTED
 
+  // Just a counter for the number of time this class is instanciated.
```
Comment (sanjoy) [inline tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h:113]: s/instanciated/instantiated/ everywhere.

Also s/nb/number

File: tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h [hunk 3]
```diff
@@ -106,6 +110,10 @@ class GpuCudaMallocAsyncAllocator : public Allocator {
...
+  // Only useful for tests.
+  static int nb_instanciated_;
```
Comment (sanjoy) [inline tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h:115]: Does this need to be an `std::atomic`?

File: tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h [hunk 4]
```diff
@@ -85,10 +85,14 @@ class GpuCudaMallocAsyncAllocator : public Allocator {
 
   void SetStream(void* stream) override {
 #if TF_CUDA_MALLOC_ASYNC_SUPPORTED
-    cuda_stream_ = reinterpret_cast<CUstream>(stream);
+    cuda_stream_ = *(static_cast<CUstream*>(stream));
 #endif
   }
 
+  static int NbInstantiated() {
```
Comment (sanjoy) [inline tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h:92]: Maybe call this `GetInstantiatedCountTestOnly`?

**Review by sanjoy — CHANGES_REQUESTED** [review]
Minor comments.

File: tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h (hunk 4 above)
Comment (nouiz) [reply tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h]: Done.

File: tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h (hunk 2 above)
Comment (nouiz) [reply tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h]: Done.

File: tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h (hunk 3 above)
Comment (nouiz) [reply tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.h]: Implemented. Note the current TF GpuDevice create them serially. But having it atomic is more future proof.

**Review by sanjoy — APPROVED** [review]

**Comment by nouiz** [comment]
Just checking if things are good on your side. It was approved 6 days ago and didn't get in yet.

**Comment by penpornk** [comment]
@nouiz Could you please help resolve the merge conflict? Thank you!

**Comment by nouiz** [comment]
Rebased.

**Review by akuegel — APPROVED** [review]

**Comment by penpornk** [comment]
@nouiz Thank you! It seems there are still conflicting files though, namely:
```
tensorflow/core/protobuf/config.proto
tensorflow/tools/api/golden/v1/tensorflow.-g-p-u-options.pbtxt
```
Could you please help resolve the conflicts again? Sorry for the inconvenience!

**Comment by nouiz** [comment]
I fixed the new conflict.
I also found a bug in the changes that caused the first merge conflict. I added the fix as it made my tests fail in CUDA 11.3.

File: tensorflow/core/common_runtime/gpu/gpu_device_test.cc [hunk 5]
```diff
@@ -114,6 +117,33 @@ class GPUDeviceTest : public ::testing::Test {
...
+  std::vector<std::unique_ptr<Device>> devices;
+  Status status;
+  int number_instantiated = GpuCudaMallocAsyncAllocator::GetInstantiatedCountTestOnly();
+  { // The new scope is to trigger the destruction of the object.
+    status = DeviceFactory::GetFactory("GPU")->CreateDevices(
+        opts, kDeviceNamePrefix, &devices);
+    EXPECT_EQ(devices.size(), 1);
+    Device* device = devices[0].get();
+    auto* device_info = device->tensorflow_gpu_device_info();
+    CHECK(device_info);
```
Comment (penpornk) [inline tensorflow/core/common_runtime/gpu/gpu_device_test.cc:132]: Could you please use `DCHECK` instead? We don't use `CHECK` in new code anymore. Sorry we didn't notice this earlier!

**Review by penpornk — CHANGES_REQUESTED** [review]
Thank you very much!

File: tensorflow/core/common_runtime/gpu/gpu_device_test.cc (hunk 5 above)
Comment (nouiz) [reply tensorflow/core/common_runtime/gpu/gpu_device_test.cc:132]: This is a test. I really want a crash even in no-debug mode.
So I pushed a change to use an EXPECT instead.

**Review by sanjoy — APPROVED** [review]

File: tensorflow/core/protobuf/config.proto [hunk 6]
```diff
@@ -208,6 +208,9 @@ message GPUOptions {
     // size exceeds the requested memory by 5% of the total virtual device/gpu
     // memory size.
     double internal_fragmentation_fraction = 10;
+
+    // When true, use CUDA cudaMallocAsync API instead of TF gpu allocator.
+    bool use_cuda_malloc_async = 11;
   }
```
Comment (ruler501) [inline tensorflow/core/protobuf/config.proto:214]: Is this correct? Assigning an integer constant to a bool seems wrong.

Comment (akuegel) [reply tensorflow/core/protobuf/config.proto:214]: This is not assigning a value, but assigning an ID. So this is fine.

**Comment by akuegel** [comment]
> Just to be sure, I see many "Internal CI build failed". Do they block this PR? What is their cause? The windows error is that bazel didn't found the strategy "sandboxed". That have been reverted to my knowledge.

The problem was an unused variable. @penpornk has adjusted your patch internally, then that patch needed approval internally, now it is theoretically ready to land (if the tests pass).

**Comment by nouiz** [comment]
Thanks for the update.

**Comment by nouiz** [comment]
In some of the refactoring of cudaMallocAsync, when there is an OOM a deadlock was added.
Here is a commit that fix it: https://github.com/tensorflow/tensorflow/commit/4cab1820acd4f9fa031bc59884e4bc461d33c3fa

I wasn't sure if you wanted to include it in this PR or not. I can make another PR with the trivial fix if you want. Just tell me how you want to handle it.

**Comment by akuegel** [comment]
> In some of the refactoring of cudaMallocAsync, when there is an OOM a deadlock was added.
> Here is a commit that fix it: [4cab182](https://github.com/tensorflow/tensorflow/commit/4cab1820acd4f9fa031bc59884e4bc461d33c3fa)
> 
> I wasn't sure if you wanted to include it in this PR or not. I can make another PR with the trivial fix if you want. Just tell me how you want to handle it.

I think landing that separately is fine. As far as I can tell, the problem is a missing BUILD dependency for the new header include in the gpu_device_test. I added this as review comment on the internal change, hopefully that is the only remaining thing needed to fix to get it landed.

**Comment by nouiz** [comment]
Any update? I think TF2.6 cutoff is soon. It would be great to get it included so people can start to use it manually.
Is there anything I can do to help?

**Comment by penpornk** [comment]
@nouiz Apologies for the delay! A couple of tests failed the heapcheck (memory leaks). (You'll have to build them and run the binary with pprof to reproduce. The problem is these tests seem to have problems building in my open source environment right now -- so I'm not sure if you'll be able to build them.)
```
$ bazel build --config=cuda --config=opt  \
   //tensorflow/core/common_runtime/gpu:gpu_device_test
$ bazel build --config=cuda --config=opt \
   //tensorflow/core/common_runtime/gpu:gpu_device_test_gpu
```

Any idea where the leak could come from? I'm sorry I haven't had time to take a closer look at what the PR is doing yet. I'll try to do that today. Will try to get this into 2.6.

**Comment by nouiz** [comment]
I looked at the code. But I do not understand what could leak.
Here there is a different cast: https://github.com/tensorflow/tensorflow/pull/49173/files#diff-d54c8000677cfd5b7bbc09963559b66949e9738b944210ee215dff19730ee296R88

I do not know pprof. Is there any options I must specify? I'll try to reproduce the error. Just in case I can help.

**Comment by penpornk** [comment]
@nouiz Thank you very much for offering to help! :)
I think I've fixed the leaks. (I added the code that delete `gpu_bfc_allocator` back. But not the suballocator.) 
```c++
      delete gpu_bfc_allocator;
      gpu_bfc_allocator = nullptr;
```

The merge is now stuck because of some (seemingly unrelated) infra issues instead. I'll keep you posted.

Just for reference, here is how to use `pprof` to check for memory leaks (paths are based on Ubuntu 18.04 -- may be different on different OSes):
```
# Install pprof and TCMalloc
$ sudo apt install libgoogle-perftools-dev google-perftools
$ export PPROF_PATH=/usr/bin/google-pprof

# Build the test
$ bazel build --config=cuda --config=opt //tensorflow/core/common_runtime/gpu:gpu_device_test

# Run the test with TCMalloc and pprof's heapcheck enabled.
$ HEAPCHECK=normal LD_PRELOAD=/usr/lib/libtcmalloc.so TF2_BEHAVIOR=1 \
    bazel-bin/tensorflow/core/common_runtime/gpu/gpu_device_test
```

**Comment by penpornk** [comment]
Thank you very much again for your patience!

> I do not see a call to pprof. Shoudn't it be:
> ```
> HEAPCHECK=normal LD_PRELOAD=/usr/lib/libtcmalloc.so TF2_BEHAVIOR=1
> $PPROF_PATH bazel-bin/tensorflow/core/common_runtime/gpu/gpu_device_test
> ```
> Or something like that?

Great question. [Heap checker](https://gperftools.github.io/gperftools/heap_checker.html) is part of TCMalloc. So we only need to link the binary to TCMalloc and turn on heap checker with the environment variable `HEAPCHECK`. It uses `pprof` underneath, that's why we need to install and set the path to `pprof`. :)
