### PR TITLE
Fix cmake build issues with GPU on Linux

### LINKED ISSUE #17232: Cmake build doesn't work on ubuntu 16.04
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: Latest from master branch
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: 5.4
- **CUDA/cuDNN version**: Cuda 9.1, cuDNN 7.0.5
- **GPU model and memory**: GeForce GTX TITAN X, 12288 MB
- **Exact command to reproduce**:
git clone https://github.com/tensorflow/tensorflow
cd tensorflow/tensorflow/contrib/cmake/
mkdir build && cd build 
ccmake .. [correct cuda version and add nccl library, idk why that was mandatory though.]
make -j

### Describe the problem
I am trying to compile tensorflow with cmake on ubuntu 16.04. Some issues I have faced till now:

**1. cuda/extras/CUPTI/include/cupti.h no found (In cupti_wrapper.h)**
Temp fix: I saw "cuda/extras/CUPTI/include" is already included in the cmake. So, changed "cuda/extras/CUPTI/include/cupti.h" => "cupti.h" and it works.

**2. src/nccl.h not found (In nccl_manager.h and nccl_ops.cc)**
Temp fix: nccl v2 doesnt have src folder but nccl.h can be found in /usr/include/. So, changed
"src/nccl.h" => nccl.h and it works

**3. GRPC is not linked to libpywrap_tensorflow_internal.so (Not fixed yet)**
`[100%] Running SWIG to generate Python wrappers
[100%] Building CXX object CMakeFiles/pywrap_tensorflow_internal.dir/pywrap_tensorflow_internal.cc.o
[100%] Linking CXX shared library libpywrap_tensorflow_internal.so
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `on_txt_done_cb(void*, int, int, unsigned char*, int)':
grpc_ares_wrapper.cc:(.text+0x256): undefined reference to `ares_parse_txt_reply_ext'
grpc_ares_wrapper.cc:(.text+0x267): undefined reference to `ares_strerror'
grpc_ares_wrapper.cc:(.text+0x363): undefined reference to `ares_free_data'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `on_srv_query_done_cb(void*, int, int, unsigned char*, int)':
grpc_ares_wrapper.cc:(.text+0x65a): undefined reference to `ares_parse_srv_reply'
grpc_ares_wrapper.cc:(.text+0x677): undefined reference to `ares_free_data'
grpc_ares_wrapper.cc:(.text+0x683): undefined reference to `ares_strerror'
grpc_ares_wrapper.cc:(.text+0x7cf): undefined reference to `ares_gethostbyname'
grpc_ares_wrapper.cc:(.text+0x830): undefined reference to `ares_gethostbyname'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `on_hostbyname_done_cb(void*, int, int, hostent*)':
grpc_ares_wrapper.cc:(.text+0x964): undefined reference to `ares_strerror'
grpc_ares_wrapper.cc:(.text+0xb7d): undefined reference to `ares_inet_ntop'
grpc_ares_wrapper.cc:(.text+0xc62): undefined reference to `ares_inet_ntop'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `grpc_dns_lookup_ares_impl(char const*, char const*, char const*, grpc_pollset_set*, grpc_closure*, grpc_lb_addresses**, bool, char**)':
`
**4. Can't fix with GRPC OFF in ccmake (Not fixed yet)**

There are so many issues in CMake and I am not able to build directly on ubuntu 16.04. Can someone look into this? Thanks!

### PR DESCRIPTION
**Pull request by yongtang**
This fix is an attempt to fix the build issues with GPU on Linux.

Previously cmake on Linux only works for CPU build.

This fix addresses multiple issues on cmake file so that GPU build could work on Linux as well.

The build is performed on Ubuntu 16.04 + CUDA 9.0 + NCCL v21, with the following command:
```
$ mkdir build && cd build
$ cmake -Dtensorflow_ENABLE_GPU=ON \
  -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.0/ \
  -Dtensorflow_CUDNN_INCLUDE=/usr/local/cuda-9.0/include/ \
  -DCMAKE_BUILD_TYPE=Release ../tensorflow/contrib/cmake
$ make -j 4 all
```

This fix fixes #17232.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: tensorflow/core/platform/default/gpu/cupti_wrapper.h [hunk 1]
```diff
@@ -23,7 +23,7 @@ limitations under the License.
 #if defined(WIN32)
 #include "extras/CUPTI/include/cupti.h"
 #else
-#include "cuda/extras/CUPTI/include/cupti.h"
+#include "cupti.h"
```
Comment (mrry) [inline tensorflow/core/platform/default/gpu/cupti_wrapper.h]: This seems like it would break the existing non-Windows GPU build, wouldn't it?

Comment (yongtang) [reply tensorflow/core/platform/default/gpu/cupti_wrapper.h]: @mrry Thanks for the review. In 
https://github.com/tensorflow/tensorflow/blob/968addadfd4e4f5688eedc31f92a9066329ff6a7/third_party/gpus/cuda/BUILD.tpl#L167-L178

The `cupti_headers` actually adds `"cuda/extras/CUPTI/include/"` to the include path.

As `cupti_wrapper.h` depends on https://github.com/tensorflow/tensorflow/blob/968addadfd4e4f5688eedc31f92a9066329ff6a7/tensorflow/core/platform/default/gpu/BUILD#L18

The bazel build for GPU build should be fine I think.

**Comment by martinwicke** [comment]
@mrry, good to go? Looks like the Windows build is fine.

**Comment by mrry** [comment]
@martinwicke Fine by me. You might want to keep an eye on it in the merge, though (unless you've already tested it on the internal build), since that's where a lot of this path complication comes from.

**Review by mrry — APPROVED** [review]

**Comment by mrry** [comment]
(Never mind, it's in `platform/default`, so shouldn't create a merge issue.)

File: tensorflow/contrib/cmake/CMakeLists.txt [hunk 2]
```diff
@@ -467,6 +467,10 @@ if (tensorflow_ENABLE_GPU)
   include_directories(${tensorflow_source_dir}/third_party/gpus)
   # add cuda libraries to tensorflow_EXTERNAL_LIBRARIES
   list(APPEND tensorflow_EXTERNAL_LIBRARIES ${CUDA_LIBRARIES})
+  if(NOT WIN32)
+    # add gomp to tensorflow_EXTERNAL_LIBRARIES, needed by libcusolver.so
+    list(APPEND tensorflow_EXTERNAL_LIBRARIES gomp)
```
Comment (peci1) [inline tensorflow/contrib/cmake/CMakeLists.txt]: I'm not sure if this is the right way to do it.

On Ubuntu 16.04, I indeed had a file `/usr/lib/x86_64-linux-gnu/libgomp.so`, but on 14.04 and 18.04, I only have `/usr/lib/x86_64-linux-gnu/libgomp.so.1`, which is not found by the linker. There are several `libgomp.so`s in subdirectories for each installed gcc version, e.g. `/usr/lib/gcc/x86_64-linux-gnu/6/libgomp.so`. These subdirectories are not however on the linker path, so linking a dependent project fails.

What works for me (and IMHO is the correct way) is `find_package(OpenMP)` and then exporting `OpenMP_CXX_FLAGS` to dependent projects (using an extras file?). With gcc, it adds `-fopenmp` to both compile and link steps. 

In https://github.com/tensorflow/tensorflow/commit/9e197152c04ebb81f055067534bd93322d182f0e there was some alteration of the CXX flags done (just for the current project, not for dependent ones), but as stated in the discussion to https://github.com/tensorflow/tensorflow/pull/18973 , it'd be better to find the flags using the `find_package` call. This is just a reminder that the work should be coordinated.

Comment (yongtang) [reply tensorflow/contrib/cmake/CMakeLists.txt]: @peci1 I only tested on Ubuntu 16.04 as it was the version Nvidia support for CUDA (Nvidia supports ubuntu 16.04 and 17.04 at that time, I couldn't find 14.04 or 18.04), but let me take a look at Ubuntu 18.04 and see if it is possible to address the issue you mentioned.

Comment (aceveggie) [reply tensorflow/contrib/cmake/CMakeLists.txt]: Can't seem to find much documentation on support for cmake on Ubuntu 18.04.

Comment (yongtang) [reply tensorflow/contrib/cmake/CMakeLists.txt]: @aceveggie I haven't been able to find the cuda install on ubuntu 18.04, or the cuda docker images based on Ubuntu 18.04: https://hub.docker.com/r/nvidia/cuda/

I can look into fixing any potential issues of CMAKE+CUDA once Nvidia supports 18.04.

Comment (peci1) [reply tensorflow/contrib/cmake/CMakeLists.txt]: Installing the 17.04 or 17.10 binary packages works on 18.04 without a problem (I've built TF both with bazel and CMake on 18.04 with CUDA 9.0 and 9.1). But I understand it still lacks official support.
