### PR TITLE
[tf.py_func()] Check Python interpreter state before call

### LINKED ISSUE #21277: Using TensorFlow's Datasets API causes process to hang in session destructor
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

Yes

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

MacOS High Sierra (10.13.1), though we've also seen this happen on Linux as well, we believe.

- **TensorFlow installed from (source or binary)**:

Source (but happens with the binary version as well)

- **TensorFlow version (use command below)**:

v1.8.0-0-g93bc2e2072 1.8.0

- **Python version**:

Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)

- **Bazel version (if compiling from source)**:

0.10.1

- **GCC/Compiler version (if compiling from source)**:

Apple LLVM version 9.0.0 (clang-900.0.39.2)

- **CUDA/cuDNN version**:

N/A

- **GPU model and memory**:

N/A

- **Exact command to reproduce**:

Unfortunately the issue isn't that easy to reproduce without running our application (I haven't managed to produce a smaller test case).

### Describe the problem

**Summary:**

We are using TensorFlow's Datasets API. More specifically, we're using `tf.data.Dataset.from_generator` to create a dataset based on a generator function.

When Python comes to garbage collect our `tf.Session` object its destructor makes a call into TensorFlow to delete the session (`tf_session.TF_DeleteSession`). This call hangs because it's trying to execute a `tf.py_func` function, but cannot acquire Python's global interpreter lock. The function its trying to execute appears to be the "finalize" function from our dataset.

This looks to me like a bug in TensorFlow, as (my understanding is) that we shouldn't be able to write code that causes this to happen. Although it's clearly a consequence of our specific use of TensorFlow I can't see that we're doing anything in our application that we shouldn't be.

**More Details:**

When our `tf.Session` object is garbage collected in Python, its destructor (`__del__` method) hangs indefinitely. The problem appears to be this call in `BaseSession`:

    tf_session.TF_DeleteSession(self._session)

Running lldb shows the following stack trace:

    * thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
      * frame #0: 0x0000000101855e7e libsystem_kernel.dylib`__psynch_cvwait + 10
        frame #1: 0x000000010188d662 libsystem_pthread.dylib`_pthread_cond_wait + 732
        frame #2: 0x00000001019b6cb0 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
        frame #3: 0x000000011279a63b libtensorflow_framework.so`nsync::nsync_mu_semaphore_p_with_deadline(nsync::nsync_semaphore_s_*, timespec) + 283
        frame #4: 0x0000000112796eb7 libtensorflow_framework.so`nsync::nsync_cv_wait_with_deadline_generic(nsync::nsync_cv_s_*, void*, void (*)(void*), void (*)(void*), timespec, nsync::nsync_note_s_*) + 423
        frame #5: 0x0000000112797621 libtensorflow_framework.so`nsync::nsync_cv_wait(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*) + 49
        frame #6: 0x00000001090810e3 _pywrap_tensorflow_internal.so`tensorflow::Notification::WaitForNotification() + 67
        frame #7: 0x0000000109d4d809 _pywrap_tensorflow_internal.so`tensorflow::CapturedFunction::RunInstantiated(std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> > const&, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) + 649
        frame #8: 0x0000000109cffa21 _pywrap_tensorflow_internal.so`tensorflow::(anonymous namespace)::GeneratorDatasetOp::Dataset::Iterator::~Iterator() + 97
        frame #9: 0x0000000109cffb8e _pywrap_tensorflow_internal.so`tensorflow::(anonymous namespace)::GeneratorDatasetOp::Dataset::Iterator::~Iterator() + 14
        frame #10: 0x0000000109cfd669 _pywrap_tensorflow_internal.so`tensorflow::(anonymous namespace)::FlatMapDatasetOp::Dataset::Iterator::~Iterator() + 105
        frame #11: 0x0000000109cfd6de _pywrap_tensorflow_internal.so`tensorflow::(anonymous namespace)::FlatMapDatasetOp::Dataset::Iterator::~Iterator() + 14
        frame #12: 0x00000001019e98fd libc++.1.dylib`std::__1::__shared_weak_count::__release_shared() + 43
        frame #13: 0x0000000109d0a579 _pywrap_tensorflow_internal.so`tensorflow::(anonymous namespace)::IteratorResource::~IteratorResource() + 169
        frame #14: 0x0000000109d0a5fe _pywrap_tensorflow_internal.so`tensorflow::(anonymous namespace)::IteratorResource::~IteratorResource() + 14
        frame #15: 0x000000011226db4d libtensorflow_framework.so`tensorflow::ResourceMgr::DoDelete(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 301
        frame #16: 0x000000011226dd50 libtensorflow_framework.so`tensorflow::ResourceMgr::DoDelete(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::type_index, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 192
        frame #17: 0x0000000109d0c558 _pywrap_tensorflow_internal.so`tensorflow::(anonymous namespace)::OneShotIteratorOp::~OneShotIteratorOp() + 104
        frame #18: 0x0000000109d0c71e _pywrap_tensorflow_internal.so`tensorflow::(anonymous namespace)::OneShotIteratorOp::~OneShotIteratorOp() + 14
        frame #19: 0x00000001122670ff libtensorflow_framework.so`tensorflow::OpSegment::Item::~Item() + 63
        frame #20: 0x0000000112267ffd libtensorflow_framework.so`tensorflow::OpSegment::RemoveHold(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 205
        frame #21: 0x000000010b880b42 _pywrap_tensorflow_internal.so`tensorflow::DirectSession::~DirectSession() + 546
        frame #22: 0x000000010b88108e _pywrap_tensorflow_internal.so`tensorflow::DirectSession::~DirectSession() + 14
        frame #23: 0x000000010935dfd3 _pywrap_tensorflow_internal.so`TF_DeleteSession + 931
        frame #24: 0x0000000109006e5a _pywrap_tensorflow_internal.so`_wrap_TF_DeleteSession(_object*, _object*) + 122
        frame #25: 0x00000001007bb688 Python`_PyCFunction_FastCallDict + 568
        frame #26: 0x00000001008443e4 Python`call_function + 612
        frame #27: 0x0000000100849d84 Python`_PyEval_EvalFrameDefault + 21892
        frame #28: 0x00000001008447cc Python`_PyFunction_FastCallDict + 828
        frame #29: 0x000000010075f984 Python`_PyObject_FastCallDict + 356
        frame #30: 0x000000010075faa0 Python`_PyObject_Call_Prepend + 208
        frame #31: 0x000000010075f8d4 Python`_PyObject_FastCallDict + 180
        frame #32: 0x00000001007d6579 Python`slot_tp_finalize + 121
        frame #33: 0x000000010089b18a Python`collect + 1418
        frame #34: 0x000000010089b8c3 Python`_PyGC_CollectIfEnabled + 99
        frame #35: 0x000000010087af57 Python`Py_FinalizeEx + 119
        frame #36: 0x000000010087b0e0 Python`Py_Exit + 16
        frame #37: 0x000000010087ef4c Python`handle_system_exit + 252
        frame #38: 0x000000010087f1a5 Python`PyErr_PrintEx + 437
        frame #39: 0x0000000100880a1d Python`PyRun_SimpleStringFlags + 125
        frame #40: 0x00000001008992a4 Python`Py_Main + 1812
        frame #41: 0x0000000100000dfe Python
        frame #42: 0x0000000100000c34 Python

It appears that the session's destructor is waiting for an op to complete. The culprit seems to be `PyFuncOp`, which doesn't get past this line:

    py_threadstate = PyGILState_Ensure();

So it looks like this op is trying to acquire the GIL but can't. My assumption is that this py_func is the "finalize" function for the dataset (from `_GeneratorDataset`).

My assumption is that when Python calls `tf_session.TF_DeleteSession(self._session)` that the GIL should be released, and so `PyFuncOp` should then be able to acquire it again. Indeed, when I write an isolated test to try and reproduce this I don't see this problem, and the GIL is acquired successfully.

Unfortunately, as I mention, I have been unsuccessful in writing an isolated test case to reproduce the problem. The problem only seems to happen when we use our application in a particular scenario, but I haven't been able to isolate exactly what it is about this scenario that causes the problem.

### PR DESCRIPTION
**Pull request by mrry**
Attempting to acquire the GIL in a destructor when the process is terminating can fail, leading to a hang. Fixes #21277.

### CODE REVIEW

File: tensorflow/python/lib/core/py_func.cc [hunk 1]
```diff
@@ -500,6 +500,11 @@ class PyFuncOp : public OpKernel {
       call.ins.push_back(ctx->input(i));
     }
 
+    OP_REQUIRES(
+        ctx, Py_IsInitialized(),
+        errors::FailedPrecondition("Python interpreter state is not initialized. "
+                                   "The process may be terminated."));
+
```
Comment (asimshankar) [inline tensorflow/python/lib/core/py_func.cc]: Should we add a comment explaining why we have this check and that we are aware of (and seek suggestions) of the race between checking Py_IsInitialized() and assuming it is still true in the Py_* function calls below?

**Review by asimshankar — DISMISSED** [review]

File: tensorflow/python/lib/core/py_func.cc (hunk 1 above)
Comment (mrry) [reply tensorflow/python/lib/core/py_func.cc]: Good idea! Done.

**Review by asimshankar — APPROVED** [review]
