### PR TITLE
Range kenrel: align CPU and GPU impl

### LINKED ISSUE #58133: `tf.range` have accumulate floating point error on CPU
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

_No response_

### Python version

_No response_

### Bazel version

_No response_

### GCC/Compiler version

_No response_

### CUDA/cuDNN version

_No response_

### GPU model and memory

_No response_

### Current Behaviour?

`tf.range` have accumulate greater and greater floating point error on CPU. In the example below, `range(- 10, 10, 0.01)` gives `[... 9.980267 9.990267]` when the correct result should be `[... 9.98 9.99]`, and this deviation is too much in my opinion.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
with tf.device('cpu'):
    tensor1 = tf.range(- 10, 10, 0.01) # [-10., -9.99 ... 9.980267 9.990267]
    print(tensor1)
with tf.device('gpu'):
    tensor2 = tf.range(- 10, 10, 0.01) # [-10., -9.99 ... 9.98 9.99]
    print(tensor2)
assert np.allclose(tensor1, tensor2) # AssertionError
```

### Relevant log output

```shell
tf.Tensor([-10.        -9.99      -9.98     ...   9.970266   9.980267   9.990267], shape=(2000,), dtype=float32)
tf.Tensor([-10.        -9.99      -9.98     ...   9.969999   9.98       9.99    ], shape=(2000,), dtype=float32)
AssertionError
```
</details>

### PR DESCRIPTION
**Pull request by bhack**
Fixes https://github.com/tensorflow/tensorflow/issues/58133

### CODE REVIEW

File: tensorflow/core/kernels/sequence_ops.cc [hunk 1]
```diff
@@ -38,10 +38,8 @@ struct RangeFunctor<CPUDevice, T> {
   void operator()(OpKernelContext* context, int64_t size, T start, T delta,
                   typename TTypes<T>::Flat output) const {
     (void)context;
-    T val = start;
     for (int64_t i = 0; i < size; ++i) {
-      output(i) = T(val);
-      val += delta;
+      output(i) = start + static_cast<T>(i) * delta;
```
Comment (bhack) [inline tensorflow/core/kernels/sequence_ops.cc:42]: https://github.com/tensorflow/tensorflow/blob/ce4f713b287e591f5a04002eccca90c26f741af7/tensorflow/core/kernels/sequence_ops_gpu.cu.cc#L34-L36

Comment (bhack) [inline tensorflow/core/kernels/sequence_ops.cc:42]: https://github.com/tensorflow/tensorflow/blob/ce4f713b287e591f5a04002eccca90c26f741af7/tensorflow/core/kernels/sequence_ops_gpu.cu.cc#L34-L36

**Review by cantonios — APPROVED** [review]
