### PR TITLE
Fixed incorrect ptxas usage affecting performance when using CUDA

### LINKED ISSUE #40036: Tensorflow 2.2 takes much more time than 2.1/2.0 to start training with "keras.fit"
**System information**
- OS Platform and Distribution:Ubuntu 18.04
- TensorFlow installed from (source or binary):conda (I trided pip, same)
- TensorFlow version:2.2
- Python version:3.7
- CUDA/cuDNN version: 10.1
- GPU model and memory:  Titan RTX * 2  = 48GB

Tensorflow 2.2 takes much more time than 2.1/2.0 to start training, after called "keras.fit".

```
2020-06-01 10:16:44.991459: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-01 10:16:46.235945: W tensorflow/stream_executor/gpu/asm_compiler.cc:81] Running ptxas --version returned 256
2020-06-01 10:16:46.328871: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code 256, output: 
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
2020-06-01 10:16:48.148004: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-01 10:23:36.473814: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.
```

It stucks about 7 mins to start training.

However, in 2.1

```
INFO:tensorflow:batch_all_reduce: 436 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
I0531 20:55:03.956965 139684401002304 cross_device_ops.py:760] batch_all_reduce: 436 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
INFO:tensorflow:batch_all_reduce: 436 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
I0531 20:55:14.695299 139684401002304 cross_device_ops.py:760] batch_all_reduce: 436 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
2020-05-31 20:55:39.932592: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-31 20:55:41.811100: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-31 20:55:48.718710: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
```

### PR DESCRIPTION
**Pull request by dev0x13**
This PR fixes #40036 issue. Now unsuccessful `ptxas` invocation attempts are being cached as well. This helps to avoid a lot of unnecessary actions and IO operations if `ptxas` is not found or is incompatible.

### CODE REVIEW

**Comment by TiantianZhang** [comment]
hi, TF2.3 still have the problem"incorrect ptxas usage affecting performance when using CUDA". Which version will solve this? Thanks!

**Comment by dev0x13** [comment]
@TiantianZhang This fix is applicable for the TF 2.3 codebase, however it's up to TF maintainers whether to release patches for TF 2.2 and 2.3 or not.

**Comment by TiantianZhang** [comment]
> @TiantianZhang This fix is applicable for the TF 2.3 codebase, however it's up to TF maintainers whether to release patches for TF 2.2 and 2.3 or not.

Thank you very much! I think everyone who have this problem can just changed the code like your commit to avoid this problem.

**Comment by mihaimaruseac** [comment]
After approving, you can try patching the other branches (and mention that you are cherrypicking). if we do a patch release (for security reasons) we might consider taking in the cherrypick, depending on complexity and timeline.

File: tensorflow/stream_executor/gpu/asm_compiler.cc [hunk 1]
```diff
@@ -108,23 +108,27 @@ static void WarnIfBadPtxasVersion(const std::string& ptxas_path) {
...
   }
 
+  // Failed compilation attempts are cached.
+  if (TF_PREDICT_FALSE(!it->second.ok())) {
+    return it->second.status();
+  }
+
   CHECK(it != ptx_cache.end());
-  const std::vector<uint8>& compiled = it->second;
+  const std::vector<uint8>& compiled = it->second.ValueOrDie();
```
Comment (timshen91) [inline tensorflow/stream_executor/gpu/asm_compiler.cc:131]: This shouldn't be a hard error. Do `TF_ASSIGN_OR_RETURN(const std::vector<uint8>& compiled, it->second);` instead.

File: tensorflow/stream_executor/gpu/asm_compiler.cc [hunk 2]
```diff
@@ -108,23 +108,27 @@ static void WarnIfBadPtxasVersion(const std::string& ptxas_path) {
...
   if (it == ptx_cache.end()) {
-    TF_ASSIGN_OR_RETURN(
-        std::vector<uint8> compiled,
-        CompileGpuAsm(device_ordinal, ptx, compilation_options));
+    auto compiled = CompileGpuAsm(device_ordinal, ptx, compilation_options);
     it = ptx_cache.emplace(cache_key, std::move(compiled)).first;
   }
 
+  // Failed compilation attempts are cached.
+  if (TF_PREDICT_FALSE(!it->second.ok())) {
```
Comment (timshen91) [inline tensorflow/stream_executor/gpu/asm_compiler.cc:126]: This should order after `CHECK(it != ptx_cache.end())`.

File: tensorflow/stream_executor/gpu/asm_compiler.cc (hunk 1 above)
Comment (dev0x13) [reply tensorflow/stream_executor/gpu/asm_compiler.cc]: Fixed, thank you

File: tensorflow/stream_executor/gpu/asm_compiler.cc (hunk 2 above)
Comment (dev0x13) [reply tensorflow/stream_executor/gpu/asm_compiler.cc:128]: Fixed, thank you

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Multiple tests are failing after this

Errors look like

```
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Failed to load in-memory CUBIN: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
	 [[{{node Qr}}]]
  (1) Internal: Failed to load in-memory CUBIN: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
	 [[{{node Qr}}]]
	 [[Qr/_5]]
```

Probably caused by

```
2020-11-30 16:52:46.015358: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xla_compile_on_demand_op.cc:173 : Internal: Failed to load in-memory CUBIN: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
```

Can you fix please? For example, `bazel test //tensorflow/compiler/xla/tests:dot_operation_test_gpu` should pass.

File: tensorflow/stream_executor/gpu/asm_compiler.cc (hunk 1 above)
Comment (dev0x13) [reply tensorflow/stream_executor/gpu/asm_compiler.cc:136]: Had to rollback to the first version since TF_ASSIGN_OR_RETURN is apparently moving the StatusOr value, which is unwanted in this particular case.

**Comment by dev0x13** [comment]
@mihaimaruseac I've fixed the failing tests. Seems like `TF_ASSIGN_OR_RETURN` was silently moving PTX compilation result instead of returning it by reference.
Sorry for letting this happen, I thought these tests are failing for some other reason, not because of my changes. Could you rerun the CI pipeline to validate the fix? Thank you in advance!

**Review by mihaimaruseac — APPROVED** [review]
