### PR TITLE
Prevent crash of tensorflow if shape is too large for tf.sparse.reorder

### LINKED ISSUE #45392: tf.sparse.reorder crashes Tensorflow if number of possible entries of dense_shape overflows 64 bit int
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.12.1-38388-gea6516dcad 2.4.0
- Python version: 3.7.6
- Bazel version (if compiling from source): using bazelisk
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce RTX 2080Ti, 11G

**Describe the current behavior**

`tf.sparse.reorder` crashes if number of possible entries of dense_shape overflows 64 bit int.

**Describe the expected behavior**
`tf.sparse.reorder` should not crash

**Standalone code to reproduce the issue**

```
import tensorflow as tf
t = tf.SparseTensor(indices=[[0, 0, 0, 0, 0, 0]], values=[0.0], dense_shape=[4096, 4096, 4096, 4096, 4096, 4096])
tf.sparse.reorder(t)
```

https://colab.research.google.com/drive/1mfRgXxnMwskSTIZ7ctuAXXtYU430s8pg?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to address the issue raised in #45392 where tensorflow crashes if shape of sparse tensor is too large for tf.sparse.reorder

This PR adds additional checks and exit gracefully if the shape is too large.

This PR fixes #45392.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by eiennohito** [comment]
In my opinion, sparse tensors should work if the number of **possible** elements overflow 64 bit.

**Comment by yongtang** [comment]
@eiennohito The PR has been updated and now it should be possible to see reorder work with large sparse tensors.

File: tensorflow/core/kernels/sparse_reorder_op.cc [hunk 1]
```diff
@@ -27,6 +27,7 @@ limitations under the License.
 #include "tensorflow/core/framework/types.h"
 #include "tensorflow/core/lib/gtl/inlined_vector.h"
 #include "tensorflow/core/util/sparse/sparse_tensor.h"
+#include "tensorflow/core/util/overflow.h"
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/sparse_reorder_op.cc:30]:
```suggestion
```

This is no longer needed

File: tensorflow/core/kernels/sparse_reorder_op.cc [hunk 2]
```diff
@@ -54,9 +55,10 @@ class SparseReorderOp : public OpKernel {
                     "Input shape should be a vector but received shape ",
                     input_shape_in.shape().DebugString()));
 
-    const TensorShape input_shape(input_shape_in.vec<int64>());
+    gtl::ArraySlice<int64> input_shape(
+        input_shape_in.vec<int64>().data(), input_shape_in.NumElements());
 
-    gtl::InlinedVector<int64, 8> std_order(input_shape.dims());
+    gtl::InlinedVector<int64, 8> std_order(input_shape.begin(), input_shape.end());
```
Comment (mihaimaruseac) [inline tensorflow/core/kernels/sparse_reorder_op.cc:61]: Let's add comments here for why we are using the iterator based versions instead of the constructors that take a single argument.

**Review by mihaimaruseac — COMMENTED** [review]
LGTM, minor nits to have the code future proof in face of refactorings that might reintroduce the bug.

File: tensorflow/core/kernels/sparse_reorder_op.cc (hunk 1 above)
Comment (yongtang) [reply tensorflow/core/kernels/sparse_reorder_op.cc]: @mihaimaruseac Thanks. The extraneous include has been removed.

File: tensorflow/core/kernels/sparse_reorder_op.cc (hunk 2 above)
Comment (yongtang) [reply tensorflow/core/kernels/sparse_reorder_op.cc]: Thanks @mihaimaruseac. I checked again, as `std_order` is actually initialized through the following line `std::iota(...)`, `std_order` only needs to be initialized with appropriate size (no need to get the copy of the shape). For that I have replace the initialization of `std_order` with `gtl::InlinedVector<int64, 8> std_order(input_shape.size())`.

**Comment by yongtang** [comment]
Thanks @mihaimaruseac for the review. The PR has been updated. The Sanity test failure seems to be unrelated to this PR (also fails with other PRs/commits). Please take a look and let me know if there are any other issues.

**Comment by bhack** [comment]
@yongtang Yes probably it was caused by https://github.com/tensorflow/tensorflow/pull/43040 merge

**Review by mihaimaruseac — APPROVED** [review]

**Comment by gbaned** [comment]
@yongtang  Can you please address Ubuntu Sanity errors? Thanks!

**Comment by yongtang** [comment]
@mihaimaruseac @gbaned The Sanity tests have been fixed against the latest master HEAD. Please take a look.

**Review by mihaimaruseac — APPROVED** [review]
